/**
 * Curated fixture of representative EU-funded / EU-associated projects.
 *
 * This is deliberately a small, hand-picked set (~25-30 entries) rather than
 * a bulk Kohesio import — see `app/api/eu-projects/route.ts` header for the
 * production-scale plan (spatial index / Kohesio proxy).
 *
 * Data discipline:
 * - Geometry is Point-only. LineString/Polygon corridor geometries are not
 *   invented; only a representative site/terminus point is used even for
 *   linear infrastructure (e.g. a tunnel portal or a hub city).
 * - `budgetEUR` is `null` unless a stable, widely reported figure exists —
 *   most entries below use `null` deliberately.
 * - `status` defaults to "unknown" unless the project's phase is common,
 *   long-standing public knowledge (e.g. a decade-long construction
 *   megaproject). No cancelled/abandoned/completed status is inferred
 *   without explicit, durable public evidence.
 * - Countries follow EUIM convention (Greece = EL). Only EUIM-in-scope
 *   countries are included (`isCountryInEUIMScope`); UK is excluded.
 */

import type { EuProject } from "./types";

const TEN_T_SOURCES = ["ten-t-dg-move"];
const KOHESIO_SOURCES = ["kohesio"];
const CINEA_SOURCES = ["cinea-cef"];
const CORDIS_SOURCES = ["cordis"];

export const EU_PROJECTS_FIXTURE: readonly EuProject[] = [
  // --- Transport & Infrastructure ---
  {
    id: "eu-project-fehmarnbelt-fixed-link",
    name: "Fehmarnbelt Fixed Link",
    category: "transport",
    countryCode: "DK",
    countryCodes: ["DK", "DE"],
    longitude: 11.34,
    latitude: 54.62,
    status: "under_construction",
    budgetEUR: null,
    fundingProgram: "TEN-T / CEF",
    description:
      "Immersed rail-and-road tunnel under the Fehmarn Belt connecting Denmark and Germany, part of the TEN-T Scandinavian–Mediterranean corridor.",
    officialUrl: "https://femern.com/",
    sourceIds: [...TEN_T_SOURCES, ...CINEA_SOURCES],
    isMajor: true,
  },
  {
    id: "eu-project-rail-baltica",
    name: "Rail Baltica",
    category: "transport",
    countryCode: "LT",
    countryCodes: ["EE", "LV", "LT", "PL"],
    longitude: 23.9,
    latitude: 54.9,
    status: "under_construction",
    budgetEUR: null,
    fundingProgram: "TEN-T / CEF",
    description:
      "Standard-gauge high-speed rail line linking the Baltic states to the European rail network, part of the North Sea–Baltic TEN-T corridor.",
    officialUrl: "https://www.rail-baltica.org/",
    sourceIds: [...TEN_T_SOURCES, ...CINEA_SOURCES],
    isMajor: true,
  },
  {
    id: "eu-project-lyon-turin-base-tunnel",
    name: "Lyon–Turin base tunnel (Mont Cenis)",
    category: "transport",
    countryCode: "FR",
    countryCodes: ["FR", "IT"],
    longitude: 6.354,
    latitude: 45.267,
    status: "under_construction",
    budgetEUR: null,
    fundingProgram: "TEN-T / CEF",
    description:
      "Cross-border rail base tunnel between France and Italy on the Mediterranean TEN-T corridor.",
    officialUrl: "https://www.telt-sas.com/",
    sourceIds: [...TEN_T_SOURCES, ...CINEA_SOURCES],
    isMajor: true,
  },
  {
    id: "eu-project-brenner-base-tunnel",
    name: "Brenner Base Tunnel",
    category: "transport",
    countryCode: "AT",
    countryCodes: ["AT", "IT"],
    longitude: 11.507,
    latitude: 47.002,
    status: "under_construction",
    budgetEUR: null,
    fundingProgram: "TEN-T / CEF",
    description:
      "Rail base tunnel under the Alps between Austria and Italy on the Scandinavian–Mediterranean TEN-T corridor.",
    officialUrl: "https://www.bbt-se.com/",
    sourceIds: [...TEN_T_SOURCES, ...CINEA_SOURCES],
    isMajor: true,
  },
  {
    id: "eu-project-seine-nord-europe-canal",
    name: "Canal Seine-Nord Europe",
    category: "transport",
    countryCode: "FR",
    longitude: 2.94,
    latitude: 49.75,
    status: "under_construction",
    budgetEUR: null,
    fundingProgram: "TEN-T / CEF",
    description:
      "New inland-waterway canal connecting the Seine and Scheldt river basins for large freight barges.",
    officialUrl: "https://www.canal-seine-nord-europe.fr/",
    sourceIds: [...TEN_T_SOURCES, ...KOHESIO_SOURCES],
    isMajor: true,
  },
  {
    id: "eu-project-via-baltica-upgrade",
    name: "Via Baltica upgrade (Poland section)",
    category: "transport",
    countryCode: "PL",
    longitude: 22.3,
    latitude: 53.4,
    status: "unknown",
    budgetEUR: null,
    fundingProgram: "Cohesion Fund",
    description:
      "Road corridor upgrade forming part of the Via Baltica route between Warsaw and the Baltic states.",
    officialUrl: null,
    sourceIds: [...KOHESIO_SOURCES],
    isMajor: false,
  },

  // --- Sport, Arts & Culture ---
  {
    id: "eu-project-m9-museum-mestre",
    name: "M9 – Museo del '900",
    category: "sportCulture",
    countryCode: "IT",
    longitude: 12.238,
    latitude: 45.489,
    status: "operational",
    budgetEUR: null,
    fundingProgram: "ERDF",
    description:
      "Museum and urban regeneration project in Mestre (Venice) co-funded through EU regional development funds.",
    officialUrl: "https://www.m9museum.it/",
    sourceIds: [...KOHESIO_SOURCES],
    isMajor: false,
  },
  {
    id: "eu-project-kaunas-culture-legacy",
    name: "Kaunas 2022 cultural infrastructure legacy",
    category: "sportCulture",
    countryCode: "LT",
    longitude: 23.904,
    latitude: 54.899,
    status: "unknown",
    budgetEUR: null,
    fundingProgram: null,
    description:
      "Cultural venue investments associated with Kaunas' term as European Capital of Culture 2022.",
    officialUrl: null,
    sourceIds: [...KOHESIO_SOURCES],
    isMajor: false,
  },
  {
    id: "eu-project-go-2025-cross-border-culture",
    name: "GO! 2025 Nova Gorica–Gorizia cross-border culture programme",
    category: "sportCulture",
    countryCode: "SI",
    countryCodes: ["SI", "IT"],
    longitude: 13.651,
    latitude: 45.956,
    status: "ongoing",
    budgetEUR: null,
    fundingProgram: null,
    description:
      "Joint European Capital of Culture 2025 programme and venue investments spanning the Slovenia–Italy border twin cities.",
    officialUrl: "https://www.go2025.eu/",
    sourceIds: [...KOHESIO_SOURCES],
    isMajor: false,
  },
  {
    id: "eu-project-plovdiv-culture-legacy",
    name: "Plovdiv 2019 cultural infrastructure legacy",
    category: "sportCulture",
    countryCode: "BG",
    longitude: 24.75,
    latitude: 42.14,
    status: "unknown",
    budgetEUR: null,
    fundingProgram: null,
    description:
      "Cultural venue and public space investments associated with Plovdiv's term as European Capital of Culture 2019.",
    officialUrl: null,
    sourceIds: [...KOHESIO_SOURCES],
    isMajor: false,
  },

  // --- Protection, Defence & Security ---
  {
    id: "eu-project-military-mobility-pesco",
    name: "Military Mobility (PESCO project)",
    category: "protection",
    countryCode: "BE",
    longitude: 4.398,
    latitude: 50.877,
    status: "ongoing",
    budgetEUR: null,
    fundingProgram: "PESCO / CEF Military Mobility",
    description:
      "Permanent Structured Cooperation project improving dual-use transport infrastructure for military mobility across the EU.",
    officialUrl: "https://www.eeas.europa.eu/eeas/military-mobility_en",
    sourceIds: [...TEN_T_SOURCES],
    isMajor: true,
  },
  {
    id: "eu-project-eurosur-upgrade",
    name: "EUROSUR border-surveillance upgrade",
    category: "protection",
    countryCode: "PL",
    longitude: 21.017,
    latitude: 52.232,
    status: "ongoing",
    budgetEUR: null,
    fundingProgram: null,
    description:
      "Continued development of the European Border Surveillance System coordinated with Frontex.",
    officialUrl: "https://www.frontex.europa.eu/",
    sourceIds: [...KOHESIO_SOURCES],
    isMajor: false,
  },
  {
    id: "eu-project-resceu-firefighting-fleet",
    name: "rescEU firefighting aerial fleet capacity",
    category: "protection",
    countryCode: "EL",
    longitude: 23.945,
    latitude: 38.12,
    status: "ongoing",
    budgetEUR: null,
    fundingProgram: null,
    description:
      "EU civil-protection reserve capacity (aircraft, helicopters) pre-positioned to support wildfire response across member states.",
    officialUrl: "https://civil-protection-humanitarian-aid.ec.europa.eu/what/civil-protection/resceu_en",
    sourceIds: [...KOHESIO_SOURCES],
    isMajor: false,
  },
  {
    id: "eu-project-baltic-sea-cable-protection",
    name: "Baltic Sea critical undersea infrastructure protection",
    category: "protection",
    countryCode: "EE",
    longitude: 24.77,
    latitude: 59.45,
    status: "unknown",
    budgetEUR: null,
    fundingProgram: null,
    description:
      "Coordinated EU / member-state initiative to monitor and protect undersea cables and pipelines in the Baltic Sea.",
    officialUrl: null,
    sourceIds: [...KOHESIO_SOURCES],
    isMajor: false,
  },

  // --- Public & Social ---
  {
    id: "eu-project-barcelona-superblocks",
    name: "Barcelona Superblocks (Superilles) urban regeneration",
    category: "publicSocial",
    countryCode: "ES",
    longitude: 2.174,
    latitude: 41.403,
    status: "ongoing",
    budgetEUR: null,
    fundingProgram: "ERDF",
    description:
      "EU-co-funded urban regeneration programme reclaiming street space for pedestrians and public life in Barcelona.",
    officialUrl: "https://www.barcelona.cat/superilles/",
    sourceIds: [...KOHESIO_SOURCES],
    isMajor: false,
  },
  {
    id: "eu-project-lesvos-reception-centre",
    name: "Lesvos migrant reception and identification centre (Mavrovouni)",
    category: "publicSocial",
    countryCode: "EL",
    longitude: 26.59,
    latitude: 39.12,
    status: "operational",
    budgetEUR: null,
    fundingProgram: "AMIF",
    description:
      "EU-co-funded reception and identification infrastructure for asylum seekers arriving on Lesvos.",
    officialUrl: null,
    sourceIds: [...KOHESIO_SOURCES],
    isMajor: false,
  },
  {
    id: "eu-project-housing-first-helsinki",
    name: "Housing First homelessness programme",
    category: "publicSocial",
    countryCode: "FI",
    longitude: 24.94,
    latitude: 60.17,
    status: "ongoing",
    budgetEUR: null,
    fundingProgram: "ESF+",
    description:
      "Social-housing-led homelessness reduction programme, part-funded through European Social Fund+ actions.",
    officialUrl: null,
    sourceIds: [...KOHESIO_SOURCES],
    isMajor: false,
  },
  {
    id: "eu-project-roma-inclusion-romania",
    name: "Roma community inclusion programme",
    category: "publicSocial",
    countryCode: "RO",
    longitude: 26.1,
    latitude: 44.43,
    status: "ongoing",
    budgetEUR: null,
    fundingProgram: "ESF+",
    description:
      "European Social Fund+ co-funded programme supporting education, housing and employment access for Roma communities.",
    officialUrl: null,
    sourceIds: [...KOHESIO_SOURCES],
    isMajor: false,
  },

  // --- Research & Innovation ---
  {
    id: "eu-project-cern-hl-lhc",
    name: "High-Luminosity LHC upgrade (CERN)",
    category: "research",
    countryCode: "CH",
    countryCodes: ["CH", "FR"],
    longitude: 6.055,
    latitude: 46.234,
    status: "under_construction",
    budgetEUR: null,
    fundingProgram: "Horizon Europe",
    description:
      "Major upgrade of the Large Hadron Collider to increase its luminosity, involving EU member-state research institutions.",
    officialUrl: "https://home.cern/science/accelerators/high-luminosity-lhc",
    sourceIds: [...CORDIS_SOURCES],
    isMajor: true,
  },
  {
    id: "eu-project-eli-np-romania",
    name: "Extreme Light Infrastructure – Nuclear Physics (ELI-NP)",
    category: "research",
    countryCode: "RO",
    longitude: 26.03,
    latitude: 44.35,
    status: "operational",
    budgetEUR: null,
    fundingProgram: "ERDF",
    description:
      "Pan-European high-power laser research facility near Bucharest, part of the ELI distributed research infrastructure.",
    officialUrl: "https://www.eli-np.ro/",
    sourceIds: [...CORDIS_SOURCES, ...KOHESIO_SOURCES],
    isMajor: true,
  },
  {
    id: "eu-project-ebrains-human-brain",
    name: "EBRAINS research infrastructure (Human Brain Project legacy)",
    category: "research",
    countryCode: "BE",
    longitude: 4.35,
    latitude: 50.85,
    status: "ongoing",
    budgetEUR: null,
    fundingProgram: "Horizon Europe",
    description:
      "Distributed digital research infrastructure for brain science, continuing the EU Human Brain Project flagship.",
    officialUrl: "https://www.ebrains.eu/",
    sourceIds: [...CORDIS_SOURCES],
    isMajor: false,
  },
  {
    id: "eu-project-graphene-flagship",
    name: "Graphene Flagship",
    category: "research",
    countryCode: "SE",
    longitude: 11.97,
    latitude: 57.69,
    status: "completed",
    budgetEUR: null,
    fundingProgram: "Horizon 2020",
    description:
      "EU Future and Emerging Technologies flagship coordinating graphene and related 2D-materials research, coordinated from Chalmers University.",
    officialUrl: "https://graphene-flagship.eu/",
    sourceIds: [...CORDIS_SOURCES],
    isMajor: false,
  },

  // --- Environment & Climate ---
  {
    id: "eu-project-danube-delta-rewilding",
    name: "Danube Delta rewilding (LIFE programme)",
    category: "environment",
    countryCode: "RO",
    longitude: 29.6,
    latitude: 45.2,
    status: "ongoing",
    budgetEUR: null,
    fundingProgram: "LIFE",
    description:
      "EU LIFE programme-funded wetland restoration and rewilding project in the Danube Delta.",
    officialUrl: "https://cinea.ec.europa.eu/programmes/life_en",
    sourceIds: [...CINEA_SOURCES, ...KOHESIO_SOURCES],
    isMajor: false,
  },
  {
    id: "eu-project-vistula-river-restoration",
    name: "Vistula River ecological restoration (LIFE programme)",
    category: "environment",
    countryCode: "PL",
    longitude: 18.6,
    latitude: 51.4,
    status: "ongoing",
    budgetEUR: null,
    fundingProgram: "LIFE",
    description:
      "River-basin restoration project supported by the EU LIFE programme along the Vistula River.",
    officialUrl: "https://cinea.ec.europa.eu/programmes/life_en",
    sourceIds: [...CINEA_SOURCES],
    isMajor: false,
  },
  {
    id: "eu-project-room-for-the-river-nl",
    name: "Room for the River (Ruimte voor de Rivier)",
    category: "environment",
    countryCode: "NL",
    longitude: 5.85,
    latitude: 51.85,
    status: "completed",
    budgetEUR: null,
    fundingProgram: null,
    description:
      "National flood-protection and river-widening programme along Dutch rivers, completed in the 2010s.",
    officialUrl: null,
    sourceIds: [...KOHESIO_SOURCES],
    isMajor: false,
  },
  {
    id: "eu-project-posidonia-seagrass-restoration",
    name: "Mediterranean Posidonia seagrass restoration (LIFE programme)",
    category: "environment",
    countryCode: "ES",
    countryCodes: ["ES", "FR", "IT"],
    longitude: 3.02,
    latitude: 39.57,
    status: "ongoing",
    budgetEUR: null,
    fundingProgram: "LIFE",
    description:
      "Multi-country LIFE programme project restoring Posidonia oceanica seagrass meadows in the Mediterranean.",
    officialUrl: "https://cinea.ec.europa.eu/programmes/life_en",
    sourceIds: [...CINEA_SOURCES],
    isMajor: false,
  },
  {
    id: "eu-project-alpine-glacier-monitoring",
    name: "Alpine glacier monitoring network (LIFE programme)",
    category: "environment",
    countryCode: "AT",
    longitude: 12.69,
    latitude: 47.07,
    status: "unknown",
    budgetEUR: null,
    fundingProgram: "LIFE",
    description:
      "Climate-monitoring network tracking glacier retreat across the Alps, part-funded through the LIFE programme.",
    officialUrl: null,
    sourceIds: [...CINEA_SOURCES],
    isMajor: false,
  },
];
