import {
  UNESCO_EUROPE_MAP_BOUNDS,
  isAllowedUnescoMapCountry,
} from "@/lib/tourism/unescoEuropeCoverage";

export type MountainPlaceCategory =
  | "ski_resort"
  | "mountain_destination"
  | "iconic_peak"
  | "mountain_range";

export type SeasonalOperation =
  | "winter"
  | "summer"
  | "year_round"
  | "unknown";

export type EuropeanMountainPlace = {
  id: string;
  canonicalName: string;
  nativeName: string | null;
  aliases: string[];
  category: MountainPlaceCategory;
  countryCodes: string[];
  cityOrRegion: string;
  latitude: number;
  longitude: number;
  wikidataId: string | null;
  officialWebsite: string | null;
  tourismWebsite: string | null;
  seasonalOperation: SeasonalOperation;
  summitElevationMeters: number | null;
  resortBaseElevationMeters: number | null;
  resortTopElevationMeters: number | null;
  mountainRange: string | null;
  linkedTouristPlaceId: string | null;
  linkedUnescoSiteId: string | null;
  snowReportUrl: string | null;
  liftStatusUrl: string | null;
};

const CATEGORIES: readonly MountainPlaceCategory[] = [
  "ski_resort",
  "mountain_destination",
  "iconic_peak",
  "mountain_range",
] as const;

export const EUROPEAN_MOUNTAIN_PLACES: readonly EuropeanMountainPlace[] = [
  // — France (ski) —
  {
    id: "mountain-chamonix",
    canonicalName: "Chamonix-Mont-Blanc",
    nativeName: null,
    aliases: ["Chamonix"],
    category: "mountain_destination",
    countryCodes: ["FR"],
    cityOrRegion: "Haute-Savoie",
    latitude: 45.9237,
    longitude: 6.8694,
    wikidataId: "Q83236",
    officialWebsite: "https://www.chamonix.com/",
    tourismWebsite: "https://en.chamonix.com/",
    seasonalOperation: "year_round",
    summitElevationMeters: null,
    resortBaseElevationMeters: 1035,
    resortTopElevationMeters: 3275,
    mountainRange: "Alps",
    linkedTouristPlaceId: null,
    linkedUnescoSiteId: null,
    snowReportUrl: null,
    liftStatusUrl: null,
  },
  {
    id: "mountain-val-thorens",
    canonicalName: "Val Thorens",
    nativeName: null,
    aliases: ["Trois Vallées", "Les Trois Vallées"],
    category: "ski_resort",
    countryCodes: ["FR"],
    cityOrRegion: "Savoie",
    latitude: 45.298,
    longitude: 6.58,
    wikidataId: "Q645458",
    officialWebsite: "https://www.valthorens.com/",
    tourismWebsite: null,
    seasonalOperation: "winter",
    summitElevationMeters: null,
    resortBaseElevationMeters: 2300,
    resortTopElevationMeters: 3230,
    mountainRange: "Alps",
    linkedTouristPlaceId: null,
    linkedUnescoSiteId: null,
    snowReportUrl: null,
    liftStatusUrl: null,
  },
  {
    id: "mountain-val-disere",
    canonicalName: "Val d'Isère",
    nativeName: null,
    aliases: ["Val d Isere"],
    category: "ski_resort",
    countryCodes: ["FR"],
    cityOrRegion: "Savoie",
    latitude: 45.4485,
    longitude: 6.9803,
    wikidataId: "Q212927",
    officialWebsite: "https://www.valdisere.com/",
    tourismWebsite: null,
    seasonalOperation: "winter",
    summitElevationMeters: null,
    resortBaseElevationMeters: 1850,
    resortTopElevationMeters: 3456,
    mountainRange: "Alps",
    linkedTouristPlaceId: null,
    linkedUnescoSiteId: null,
    snowReportUrl: null,
    liftStatusUrl: null,
  },
  {
    id: "mountain-courchevel",
    canonicalName: "Courchevel",
    nativeName: null,
    aliases: ["Les Trois Vallées"],
    category: "ski_resort",
    countryCodes: ["FR"],
    cityOrRegion: "Savoie",
    latitude: 45.4147,
    longitude: 6.6347,
    wikidataId: "Q212926",
    officialWebsite: "https://www.courchevel.com/",
    tourismWebsite: null,
    seasonalOperation: "winter",
    summitElevationMeters: null,
    resortBaseElevationMeters: 1100,
    resortTopElevationMeters: 2738,
    mountainRange: "Alps",
    linkedTouristPlaceId: null,
    linkedUnescoSiteId: null,
    snowReportUrl: null,
    liftStatusUrl: null,
  },
  {
    id: "mountain-megeve",
    canonicalName: "Megève",
    nativeName: null,
    aliases: ["Megeve"],
    category: "ski_resort",
    countryCodes: ["FR"],
    cityOrRegion: "Haute-Savoie",
    latitude: 45.8567,
    longitude: 6.6178,
    wikidataId: "Q259283",
    officialWebsite: "https://www.megeve-tourisme.fr/",
    tourismWebsite: null,
    seasonalOperation: "winter",
    summitElevationMeters: null,
    resortBaseElevationMeters: 1113,
    resortTopElevationMeters: 2353,
    mountainRange: "Alps",
    linkedTouristPlaceId: null,
    linkedUnescoSiteId: null,
    snowReportUrl: null,
    liftStatusUrl: null,
  },
  {
    id: "mountain-les-deux-alpes",
    canonicalName: "Les Deux Alpes",
    nativeName: null,
    aliases: ["2 Alpes"],
    category: "ski_resort",
    countryCodes: ["FR"],
    cityOrRegion: "Isère",
    latitude: 45.0075,
    longitude: 6.1214,
    wikidataId: "Q212924",
    officialWebsite: "https://www.les2alpes.com/",
    tourismWebsite: null,
    seasonalOperation: "year_round",
    summitElevationMeters: null,
    resortBaseElevationMeters: 1300,
    resortTopElevationMeters: 3600,
    mountainRange: "Alps",
    linkedTouristPlaceId: null,
    linkedUnescoSiteId: null,
    snowReportUrl: null,
    liftStatusUrl: null,
  },
  {
    id: "mountain-tignes",
    canonicalName: "Tignes",
    nativeName: null,
    aliases: ["Espace Killy", "Tignes-Val d'Isère"],
    category: "ski_resort",
    countryCodes: ["FR"],
    cityOrRegion: "Savoie",
    latitude: 45.4697,
    longitude: 6.9064,
    wikidataId: "Q212923",
    officialWebsite: "https://www.tignes.net/",
    tourismWebsite: null,
    seasonalOperation: "year_round",
    summitElevationMeters: null,
    resortBaseElevationMeters: 1550,
    resortTopElevationMeters: 3456,
    mountainRange: "Alps",
    linkedTouristPlaceId: null,
    linkedUnescoSiteId: null,
    snowReportUrl: null,
    liftStatusUrl: null,
  },
  {
    id: "mountain-la-plagne",
    canonicalName: "La Plagne",
    nativeName: null,
    aliases: ["Paradiski"],
    category: "ski_resort",
    countryCodes: ["FR"],
    cityOrRegion: "Savoie",
    latitude: 45.5075,
    longitude: 6.6797,
    wikidataId: "Q212922",
    officialWebsite: "https://www.la-plagne.com/",
    tourismWebsite: null,
    seasonalOperation: "winter",
    summitElevationMeters: null,
    resortBaseElevationMeters: 1250,
    resortTopElevationMeters: 3250,
    mountainRange: "Alps",
    linkedTouristPlaceId: null,
    linkedUnescoSiteId: null,
    snowReportUrl: null,
    liftStatusUrl: null,
  },
  {
    id: "mountain-les-arcs",
    canonicalName: "Les Arcs",
    nativeName: null,
    aliases: ["Paradiski"],
    category: "ski_resort",
    countryCodes: ["FR"],
    cityOrRegion: "Savoie",
    latitude: 45.5686,
    longitude: 6.8256,
    wikidataId: "Q670977",
    officialWebsite: "https://www.lesarc.com/",
    tourismWebsite: null,
    seasonalOperation: "winter",
    summitElevationMeters: null,
    resortBaseElevationMeters: 1200,
    resortTopElevationMeters: 3226,
    mountainRange: "Alps",
    linkedTouristPlaceId: null,
    linkedUnescoSiteId: null,
    snowReportUrl: null,
    liftStatusUrl: null,
  },
  {
    id: "mountain-avoriaz",
    canonicalName: "Avoriaz",
    nativeName: null,
    aliases: ["Portes du Soleil"],
    category: "ski_resort",
    countryCodes: ["FR"],
    cityOrRegion: "Haute-Savoie",
    latitude: 46.1931,
    longitude: 6.7747,
    wikidataId: "Q212920",
    officialWebsite: "https://www.avoriaz.com/",
    tourismWebsite: null,
    seasonalOperation: "winter",
    summitElevationMeters: null,
    resortBaseElevationMeters: 1800,
    resortTopElevationMeters: 2466,
    mountainRange: "Alps",
    linkedTouristPlaceId: null,
    linkedUnescoSiteId: null,
    snowReportUrl: null,
    liftStatusUrl: null,
  },
  {
    id: "mountain-morzine",
    canonicalName: "Morzine",
    nativeName: null,
    aliases: ["Portes du Soleil"],
    category: "ski_resort",
    countryCodes: ["FR"],
    cityOrRegion: "Haute-Savoie",
    latitude: 46.1792,
    longitude: 6.7092,
    wikidataId: "Q212919",
    officialWebsite: "https://www.morzine-avoriaz.com/",
    tourismWebsite: null,
    seasonalOperation: "winter",
    summitElevationMeters: null,
    resortBaseElevationMeters: 1000,
    resortTopElevationMeters: 2466,
    mountainRange: "Alps",
    linkedTouristPlaceId: null,
    linkedUnescoSiteId: null,
    snowReportUrl: null,
    liftStatusUrl: null,
  },
  {
    id: "mountain-serre-chevalier",
    canonicalName: "Serre Chevalier",
    nativeName: null,
    aliases: [],
    category: "ski_resort",
    countryCodes: ["FR"],
    cityOrRegion: "Hautes-Alpes",
    latitude: 44.9397,
    longitude: 6.56,
    wikidataId: "Q212918",
    officialWebsite: "https://www.serre-chevalier.com/",
    tourismWebsite: null,
    seasonalOperation: "winter",
    summitElevationMeters: null,
    resortBaseElevationMeters: 1200,
    resortTopElevationMeters: 2800,
    mountainRange: "Alps",
    linkedTouristPlaceId: null,
    linkedUnescoSiteId: null,
    snowReportUrl: null,
    liftStatusUrl: null,
  },
  {
    id: "mountain-isola-2000",
    canonicalName: "Isola 2000",
    nativeName: null,
    aliases: [],
    category: "ski_resort",
    countryCodes: ["FR"],
    cityOrRegion: "Alpes-Maritimes",
    latitude: 44.1861,
    longitude: 7.15,
    wikidataId: "Q212917",
    officialWebsite: "https://www.isola2000.com/",
    tourismWebsite: null,
    seasonalOperation: "winter",
    summitElevationMeters: null,
    resortBaseElevationMeters: 2000,
    resortTopElevationMeters: 2610,
    mountainRange: "Alps",
    linkedTouristPlaceId: null,
    linkedUnescoSiteId: null,
    snowReportUrl: null,
    liftStatusUrl: null,
  },
  {
    id: "mountain-font-romeu",
    canonicalName: "Font-Romeu",
    nativeName: null,
    aliases: ["Pyrénées 2000"],
    category: "ski_resort",
    countryCodes: ["FR"],
    cityOrRegion: "Pyrénées-Orientales",
    latitude: 42.5028,
    longitude: 2.0397,
    wikidataId: "Q212916",
    officialWebsite: "https://www.fontromeu.com/",
    tourismWebsite: null,
    seasonalOperation: "winter",
    summitElevationMeters: null,
    resortBaseElevationMeters: 1800,
    resortTopElevationMeters: 2213,
    mountainRange: "Pyrenees",
    linkedTouristPlaceId: null,
    linkedUnescoSiteId: null,
    snowReportUrl: null,
    liftStatusUrl: null,
  },
  {
    id: "mountain-piau-engaly",
    canonicalName: "Piau-Engaly",
    nativeName: null,
    aliases: [],
    category: "ski_resort",
    countryCodes: ["FR"],
    cityOrRegion: "Hautes-Pyrénées",
    latitude: 42.7897,
    longitude: 0.2189,
    wikidataId: "Q212915",
    officialWebsite: "https://www.piau.com/",
    tourismWebsite: null,
    seasonalOperation: "winter",
    summitElevationMeters: null,
    resortBaseElevationMeters: 1850,
    resortTopElevationMeters: 2600,
    mountainRange: "Pyrenees",
    linkedTouristPlaceId: null,
    linkedUnescoSiteId: null,
    snowReportUrl: null,
    liftStatusUrl: null,
  },
  // — Switzerland (ski) —
  {
    id: "mountain-zermatt",
    canonicalName: "Zermatt",
    nativeName: null,
    aliases: ["Matterhorn ski area"],
    category: "ski_resort",
    countryCodes: ["CH"],
    cityOrRegion: "Valais",
    latitude: 46.0207,
    longitude: 7.7491,
    wikidataId: "Q27494",
    officialWebsite: "https://www.zermatt.ch/en",
    tourismWebsite: null,
    seasonalOperation: "year_round",
    summitElevationMeters: null,
    resortBaseElevationMeters: 1620,
    resortTopElevationMeters: 3883,
    mountainRange: "Alps",
    linkedTouristPlaceId: null,
    linkedUnescoSiteId: null,
    snowReportUrl: "https://www.zermatt.ch/en/winter/snow-report",
    liftStatusUrl: null,
  },
  {
    id: "mountain-st-moritz",
    canonicalName: "St. Moritz",
    nativeName: null,
    aliases: ["Saint Moritz", "Engadin"],
    category: "ski_resort",
    countryCodes: ["CH"],
    cityOrRegion: "Graubünden",
    latitude: 46.4974,
    longitude: 9.8375,
    wikidataId: "Q68986",
    officialWebsite: "https://www.stmoritz.ch/en",
    tourismWebsite: null,
    seasonalOperation: "year_round",
    summitElevationMeters: null,
    resortBaseElevationMeters: 1778,
    resortTopElevationMeters: 3303,
    mountainRange: "Alps",
    linkedTouristPlaceId: null,
    linkedUnescoSiteId: null,
    snowReportUrl: null,
    liftStatusUrl: null,
  },
  {
    id: "mountain-verbier",
    canonicalName: "Verbier",
    nativeName: null,
    aliases: ["4 Vallées"],
    category: "ski_resort",
    countryCodes: ["CH"],
    cityOrRegion: "Valais",
    latitude: 46.0964,
    longitude: 7.2286,
    wikidataId: "Q68987",
    officialWebsite: "https://www.verbier.ch/en",
    tourismWebsite: null,
    seasonalOperation: "winter",
    summitElevationMeters: null,
    resortBaseElevationMeters: 1500,
    resortTopElevationMeters: 3330,
    mountainRange: "Alps",
    linkedTouristPlaceId: null,
    linkedUnescoSiteId: null,
    snowReportUrl: null,
    liftStatusUrl: null,
  },
  {
    id: "mountain-davos",
    canonicalName: "Davos",
    nativeName: null,
    aliases: ["Klosters-Davos"],
    category: "ski_resort",
    countryCodes: ["CH"],
    cityOrRegion: "Graubünden",
    latitude: 46.8027,
    longitude: 9.836,
    wikidataId: "Q68297",
    officialWebsite: "https://www.davos.ch/en",
    tourismWebsite: null,
    seasonalOperation: "winter",
    summitElevationMeters: null,
    resortBaseElevationMeters: 1120,
    resortTopElevationMeters: 2844,
    mountainRange: "Alps",
    linkedTouristPlaceId: null,
    linkedUnescoSiteId: null,
    snowReportUrl: null,
    liftStatusUrl: null,
  },
  {
    id: "mountain-crans-montana",
    canonicalName: "Crans-Montana",
    nativeName: null,
    aliases: ["Crans Montana"],
    category: "ski_resort",
    countryCodes: ["CH"],
    cityOrRegion: "Valais",
    latitude: 46.3086,
    longitude: 7.4825,
    wikidataId: "Q68988",
    officialWebsite: "https://www.crans-montana.ch/en",
    tourismWebsite: null,
    seasonalOperation: "winter",
    summitElevationMeters: null,
    resortBaseElevationMeters: 1500,
    resortTopElevationMeters: 3000,
    mountainRange: "Alps",
    linkedTouristPlaceId: null,
    linkedUnescoSiteId: null,
    snowReportUrl: null,
    liftStatusUrl: null,
  },
  {
    id: "mountain-saas-fee",
    canonicalName: "Saas-Fee",
    nativeName: null,
    aliases: ["Saas Fee"],
    category: "ski_resort",
    countryCodes: ["CH"],
    cityOrRegion: "Valais",
    latitude: 46.1097,
    longitude: 7.9278,
    wikidataId: "Q68989",
    officialWebsite: "https://www.saas-fee.ch/en",
    tourismWebsite: null,
    seasonalOperation: "year_round",
    summitElevationMeters: null,
    resortBaseElevationMeters: 1800,
    resortTopElevationMeters: 3600,
    mountainRange: "Alps",
    linkedTouristPlaceId: null,
    linkedUnescoSiteId: null,
    snowReportUrl: null,
    liftStatusUrl: null,
  },
  {
    id: "mountain-wengen",
    canonicalName: "Wengen",
    nativeName: null,
    aliases: ["Jungfrau region", "Jungfrau Ski Region"],
    category: "ski_resort",
    countryCodes: ["CH"],
    cityOrRegion: "Bernese Oberland",
    latitude: 46.6053,
    longitude: 7.9219,
    wikidataId: "Q68990",
    officialWebsite: "https://www.wengen.ch/en",
    tourismWebsite: null,
    seasonalOperation: "winter",
    summitElevationMeters: null,
    resortBaseElevationMeters: 1274,
    resortTopElevationMeters: 2320,
    mountainRange: "Alps",
    linkedTouristPlaceId: null,
    linkedUnescoSiteId: null,
    snowReportUrl: null,
    liftStatusUrl: null,
  },
  {
    id: "mountain-grindelwald",
    canonicalName: "Grindelwald",
    nativeName: null,
    aliases: ["Jungfrau region"],
    category: "ski_resort",
    countryCodes: ["CH"],
    cityOrRegion: "Bernese Oberland",
    latitude: 46.6244,
    longitude: 8.0414,
    wikidataId: "Q68991",
    officialWebsite: "https://www.grindelwald.ch/en",
    tourismWebsite: null,
    seasonalOperation: "winter",
    summitElevationMeters: null,
    resortBaseElevationMeters: 1034,
    resortTopElevationMeters: 2500,
    mountainRange: "Alps",
    linkedTouristPlaceId: null,
    linkedUnescoSiteId: null,
    snowReportUrl: null,
    liftStatusUrl: null,
  },
  // — Italy (ski) —
  {
    id: "mountain-cortina",
    canonicalName: "Cortina d'Ampezzo",
    nativeName: "Cortina d'Ampezzo",
    aliases: ["Cortina", "Dolomiti Superski"],
    category: "mountain_destination",
    countryCodes: ["IT"],
    cityOrRegion: "Veneto",
    latitude: 46.5369,
    longitude: 12.1356,
    wikidataId: "Q212914",
    officialWebsite: "https://www.cortina.dolomiti.org/",
    tourismWebsite: null,
    seasonalOperation: "winter",
    summitElevationMeters: null,
    resortBaseElevationMeters: 1224,
    resortTopElevationMeters: 2930,
    mountainRange: "Dolomites",
    linkedTouristPlaceId: null,
    linkedUnescoSiteId: null,
    snowReportUrl: null,
    liftStatusUrl: null,
  },
  {
    id: "mountain-courmayeur",
    canonicalName: "Courmayeur",
    nativeName: null,
    aliases: ["Mont Blanc area"],
    category: "ski_resort",
    countryCodes: ["IT"],
    cityOrRegion: "Aosta Valley",
    latitude: 45.7969,
    longitude: 6.9728,
    wikidataId: "Q34993",
    officialWebsite: "https://www.courmayeur.it/en",
    tourismWebsite: null,
    seasonalOperation: "winter",
    summitElevationMeters: null,
    resortBaseElevationMeters: 1224,
    resortTopElevationMeters: 2755,
    mountainRange: "Alps",
    linkedTouristPlaceId: null,
    linkedUnescoSiteId: null,
    snowReportUrl: null,
    liftStatusUrl: null,
  },
  {
    id: "mountain-madonna-di-campiglio",
    canonicalName: "Madonna di Campiglio",
    nativeName: null,
    aliases: ["Skiarea Campiglio Dolomiti"],
    category: "ski_resort",
    countryCodes: ["IT"],
    cityOrRegion: "Trentino",
    latitude: 46.2297,
    longitude: 10.8264,
    wikidataId: "Q212912",
    officialWebsite: "https://www.campiglio.it/en",
    tourismWebsite: null,
    seasonalOperation: "winter",
    summitElevationMeters: null,
    resortBaseElevationMeters: 1550,
    resortTopElevationMeters: 2500,
    mountainRange: "Dolomites",
    linkedTouristPlaceId: null,
    linkedUnescoSiteId: null,
    snowReportUrl: null,
    liftStatusUrl: null,
  },
  {
    id: "mountain-cervinia",
    canonicalName: "Breuil-Cervinia",
    nativeName: "Breuil-Cervinia",
    aliases: ["Cervinia", "Valtournenche"],
    category: "ski_resort",
    countryCodes: ["IT"],
    cityOrRegion: "Aosta Valley",
    latitude: 45.9347,
    longitude: 7.6311,
    wikidataId: "Q212911",
    officialWebsite: "https://www.cervinia.it/en",
    tourismWebsite: null,
    seasonalOperation: "year_round",
    summitElevationMeters: null,
    resortBaseElevationMeters: 2050,
    resortTopElevationMeters: 3480,
    mountainRange: "Alps",
    linkedTouristPlaceId: null,
    linkedUnescoSiteId: null,
    snowReportUrl: null,
    liftStatusUrl: null,
  },
  {
    id: "mountain-sestriere",
    canonicalName: "Sestriere",
    nativeName: null,
    aliases: ["Via Lattea"],
    category: "ski_resort",
    countryCodes: ["IT"],
    cityOrRegion: "Piedmont",
    latitude: 44.9586,
    longitude: 6.8781,
    wikidataId: "Q212910",
    officialWebsite: "https://www.sestriere.it/en",
    tourismWebsite: null,
    seasonalOperation: "winter",
    summitElevationMeters: null,
    resortBaseElevationMeters: 2035,
    resortTopElevationMeters: 2840,
    mountainRange: "Alps",
    linkedTouristPlaceId: null,
    linkedUnescoSiteId: null,
    snowReportUrl: null,
    liftStatusUrl: null,
  },
  // — Austria (ski) —
  {
    id: "mountain-kitzbuhel",
    canonicalName: "Kitzbühel",
    nativeName: "Kitzbühel",
    aliases: ["Kitzbuehel", "Hahnenkamm"],
    category: "ski_resort",
    countryCodes: ["AT"],
    cityOrRegion: "Tyrol",
    latitude: 47.4464,
    longitude: 12.3922,
    wikidataId: "Q212909",
    officialWebsite: "https://www.kitzbuehel.com/en",
    tourismWebsite: null,
    seasonalOperation: "winter",
    summitElevationMeters: null,
    resortBaseElevationMeters: 800,
    resortTopElevationMeters: 2000,
    mountainRange: "Alps",
    linkedTouristPlaceId: null,
    linkedUnescoSiteId: null,
    snowReportUrl: null,
    liftStatusUrl: null,
  },
  {
    id: "mountain-innsbruck-igls",
    canonicalName: "Innsbruck-Igls",
    nativeName: null,
    aliases: ["Igls", "Olympiaregion Innsbruck"],
    category: "mountain_destination",
    countryCodes: ["AT"],
    cityOrRegion: "Tyrol",
    latitude: 47.2692,
    longitude: 11.4044,
    wikidataId: "Q212908",
    officialWebsite: "https://www.innsbruck.info/en",
    tourismWebsite: null,
    seasonalOperation: "winter",
    summitElevationMeters: null,
    resortBaseElevationMeters: 900,
    resortTopElevationMeters: 2340,
    mountainRange: "Alps",
    linkedTouristPlaceId: null,
    linkedUnescoSiteId: null,
    snowReportUrl: null,
    liftStatusUrl: null,
  },
  {
    id: "mountain-st-anton",
    canonicalName: "St. Anton am Arlberg",
    nativeName: "St. Anton am Arlberg",
    aliases: ["St Anton", "Arlberg"],
    category: "ski_resort",
    countryCodes: ["AT"],
    cityOrRegion: "Tyrol",
    latitude: 47.1286,
    longitude: 10.2636,
    wikidataId: "Q212907",
    officialWebsite: "https://www.stantonamarlberg.com/en",
    tourismWebsite: null,
    seasonalOperation: "winter",
    summitElevationMeters: null,
    resortBaseElevationMeters: 1304,
    resortTopElevationMeters: 2811,
    mountainRange: "Alps",
    linkedTouristPlaceId: null,
    linkedUnescoSiteId: null,
    snowReportUrl: null,
    liftStatusUrl: null,
  },
  {
    id: "mountain-ischgl",
    canonicalName: "Ischgl",
    nativeName: null,
    aliases: ["Silvretta Arena"],
    category: "ski_resort",
    countryCodes: ["AT"],
    cityOrRegion: "Tyrol",
    latitude: 47.0125,
    longitude: 10.2917,
    wikidataId: "Q212906",
    officialWebsite: "https://www.ischgl.com/en",
    tourismWebsite: null,
    seasonalOperation: "winter",
    summitElevationMeters: null,
    resortBaseElevationMeters: 1377,
    resortTopElevationMeters: 2872,
    mountainRange: "Alps",
    linkedTouristPlaceId: null,
    linkedUnescoSiteId: null,
    snowReportUrl: null,
    liftStatusUrl: null,
  },
  {
    id: "mountain-mayrhofen",
    canonicalName: "Mayrhofen",
    nativeName: null,
    aliases: ["Zillertal Arena"],
    category: "ski_resort",
    countryCodes: ["AT"],
    cityOrRegion: "Tyrol",
    latitude: 47.1692,
    longitude: 11.8642,
    wikidataId: "Q212905",
    officialWebsite: "https://www.mayrhofen.at/en",
    tourismWebsite: null,
    seasonalOperation: "winter",
    summitElevationMeters: null,
    resortBaseElevationMeters: 630,
    resortTopElevationMeters: 2500,
    mountainRange: "Alps",
    linkedTouristPlaceId: null,
    linkedUnescoSiteId: null,
    snowReportUrl: null,
    liftStatusUrl: null,
  },
  {
    id: "mountain-solden",
    canonicalName: "Sölden",
    nativeName: "Sölden",
    aliases: ["Soelden", "Ötztal"],
    category: "ski_resort",
    countryCodes: ["AT"],
    cityOrRegion: "Tyrol",
    latitude: 46.9667,
    longitude: 11.0,
    wikidataId: "Q212904",
    officialWebsite: "https://www.soelden.com/en",
    tourismWebsite: null,
    seasonalOperation: "year_round",
    summitElevationMeters: null,
    resortBaseElevationMeters: 1350,
    resortTopElevationMeters: 3340,
    mountainRange: "Alps",
    linkedTouristPlaceId: null,
    linkedUnescoSiteId: null,
    snowReportUrl: null,
    liftStatusUrl: null,
  },
  {
    id: "mountain-kaprun",
    canonicalName: "Kaprun",
    nativeName: null,
    aliases: ["Kitzsteinhorn"],
    category: "ski_resort",
    countryCodes: ["AT"],
    cityOrRegion: "Salzburg",
    latitude: 47.2725,
    longitude: 12.7597,
    wikidataId: "Q212903",
    officialWebsite: "https://www.kaprun.com/en",
    tourismWebsite: null,
    seasonalOperation: "year_round",
    summitElevationMeters: null,
    resortBaseElevationMeters: 786,
    resortTopElevationMeters: 3029,
    mountainRange: "Alps",
    linkedTouristPlaceId: null,
    linkedUnescoSiteId: null,
    snowReportUrl: null,
    liftStatusUrl: null,
  },
  {
    id: "mountain-saalbach",
    canonicalName: "Saalbach-Hinterglemm",
    nativeName: null,
    aliases: ["Saalbach", "Skicircus"],
    category: "ski_resort",
    countryCodes: ["AT"],
    cityOrRegion: "Salzburg",
    latitude: 47.3914,
    longitude: 12.6364,
    wikidataId: "Q212902",
    officialWebsite: "https://www.saalbach.com/en",
    tourismWebsite: null,
    seasonalOperation: "winter",
    summitElevationMeters: null,
    resortBaseElevationMeters: 1003,
    resortTopElevationMeters: 2096,
    mountainRange: "Alps",
    linkedTouristPlaceId: null,
    linkedUnescoSiteId: null,
    snowReportUrl: null,
    liftStatusUrl: null,
  },
  {
    id: "mountain-flachau",
    canonicalName: "Flachau",
    nativeName: null,
    aliases: ["Salzburger Sportwelt"],
    category: "ski_resort",
    countryCodes: ["AT"],
    cityOrRegion: "Salzburg",
    latitude: 47.3428,
    longitude: 13.3928,
    wikidataId: "Q212901",
    officialWebsite: "https://www.flachau.com/en",
    tourismWebsite: null,
    seasonalOperation: "winter",
    summitElevationMeters: null,
    resortBaseElevationMeters: 920,
    resortTopElevationMeters: 1980,
    mountainRange: "Alps",
    linkedTouristPlaceId: null,
    linkedUnescoSiteId: null,
    snowReportUrl: null,
    liftStatusUrl: null,
  },
  // — Germany (ski) —
  {
    id: "mountain-garmisch-partenkirchen",
    canonicalName: "Garmisch-Partenkirchen",
    nativeName: null,
    aliases: ["Garmisch", "Zugspitze ski area"],
    category: "ski_resort",
    countryCodes: ["DE"],
    cityOrRegion: "Bavaria",
    latitude: 47.4925,
    longitude: 11.0956,
    wikidataId: "Q212900",
    officialWebsite: "https://www.garmisch-partenkirchen.de/en",
    tourismWebsite: null,
    seasonalOperation: "winter",
    summitElevationMeters: null,
    resortBaseElevationMeters: 708,
    resortTopElevationMeters: 2720,
    mountainRange: "Alps",
    linkedTouristPlaceId: null,
    linkedUnescoSiteId: null,
    snowReportUrl: null,
    liftStatusUrl: null,
  },
  {
    id: "mountain-oberstdorf",
    canonicalName: "Oberstdorf",
    nativeName: null,
    aliases: ["Kleinwalsertal", "Oberallgäu"],
    category: "ski_resort",
    countryCodes: ["DE"],
    cityOrRegion: "Bavaria",
    latitude: 47.4078,
    longitude: 10.2794,
    wikidataId: "Q212899",
    officialWebsite: "https://www.oberstdorf.de/en",
    tourismWebsite: null,
    seasonalOperation: "winter",
    summitElevationMeters: null,
    resortBaseElevationMeters: 815,
    resortTopElevationMeters: 2220,
    mountainRange: "Alps",
    linkedTouristPlaceId: null,
    linkedUnescoSiteId: null,
    snowReportUrl: null,
    liftStatusUrl: null,
  },
  // — Spain (ski) —
  {
    id: "mountain-sierra-nevada",
    canonicalName: "Sierra Nevada",
    nativeName: null,
    aliases: ["Pradollano", "Sierra Nevada ski resort"],
    category: "ski_resort",
    countryCodes: ["ES"],
    cityOrRegion: "Andalusia",
    latitude: 37.0956,
    longitude: -3.3947,
    wikidataId: "Q212898",
    officialWebsite: "https://sierranevada.es/en/",
    tourismWebsite: null,
    seasonalOperation: "winter",
    summitElevationMeters: null,
    resortBaseElevationMeters: 2100,
    resortTopElevationMeters: 3282,
    mountainRange: "Sierra Nevada",
    linkedTouristPlaceId: null,
    linkedUnescoSiteId: null,
    snowReportUrl: null,
    liftStatusUrl: null,
  },
  {
    id: "mountain-baqueira-beret",
    canonicalName: "Baqueira-Beret",
    nativeName: "Baqueira Beret",
    aliases: ["Baqueira Beret", "Val d'Aran"],
    category: "ski_resort",
    countryCodes: ["ES"],
    cityOrRegion: "Catalonia",
    latitude: 42.6997,
    longitude: 0.9369,
    wikidataId: "Q212897",
    officialWebsite: "https://www.baqueira.es/en",
    tourismWebsite: null,
    seasonalOperation: "winter",
    summitElevationMeters: null,
    resortBaseElevationMeters: 1500,
    resortTopElevationMeters: 2510,
    mountainRange: "Pyrenees",
    linkedTouristPlaceId: null,
    linkedUnescoSiteId: null,
    snowReportUrl: null,
    liftStatusUrl: null,
  },
  {
    id: "mountain-formigal",
    canonicalName: "Formigal",
    nativeName: null,
    aliases: ["Formigal-Panticosa"],
    category: "ski_resort",
    countryCodes: ["ES"],
    cityOrRegion: "Aragon",
    latitude: 42.7647,
    longitude: -0.375,
    wikidataId: "Q212896",
    officialWebsite: "https://www.formigal.com/en",
    tourismWebsite: null,
    seasonalOperation: "winter",
    summitElevationMeters: null,
    resortBaseElevationMeters: 1500,
    resortTopElevationMeters: 2250,
    mountainRange: "Pyrenees",
    linkedTouristPlaceId: null,
    linkedUnescoSiteId: null,
    snowReportUrl: null,
    liftStatusUrl: null,
  },
  // — Bulgaria (ski) —
  {
    id: "mountain-bansko",
    canonicalName: "Bansko",
    nativeName: "Банско",
    aliases: [],
    category: "ski_resort",
    countryCodes: ["BG"],
    cityOrRegion: "Pirin Mountains",
    latitude: 41.8364,
    longitude: 23.4889,
    wikidataId: "Q212895",
    officialWebsite: "https://banskoski.com/",
    tourismWebsite: null,
    seasonalOperation: "winter",
    summitElevationMeters: null,
    resortBaseElevationMeters: 990,
    resortTopElevationMeters: 2600,
    mountainRange: "Pirin",
    linkedTouristPlaceId: null,
    linkedUnescoSiteId: null,
    snowReportUrl: null,
    liftStatusUrl: null,
  },
  {
    id: "mountain-vitosha",
    canonicalName: "Vitosha",
    nativeName: "Витоша",
    aliases: ["Aleko", "Vitosha ski area"],
    category: "ski_resort",
    countryCodes: ["BG"],
    cityOrRegion: "Sofia",
    latitude: 42.5833,
    longitude: 23.2833,
    wikidataId: "Q212894",
    officialWebsite: null,
    tourismWebsite: null,
    seasonalOperation: "winter",
    summitElevationMeters: null,
    resortBaseElevationMeters: 1800,
    resortTopElevationMeters: 2290,
    mountainRange: "Balkan Mountains",
    linkedTouristPlaceId: null,
    linkedUnescoSiteId: null,
    snowReportUrl: null,
    liftStatusUrl: null,
  },
  {
    id: "mountain-borovets",
    canonicalName: "Borovets",
    nativeName: "Боровец",
    aliases: [],
    category: "ski_resort",
    countryCodes: ["BG"],
    cityOrRegion: "Rila Mountains",
    latitude: 42.2678,
    longitude: 23.6019,
    wikidataId: "Q212893",
    officialWebsite: "https://www.borovets.bg/en",
    tourismWebsite: null,
    seasonalOperation: "winter",
    summitElevationMeters: null,
    resortBaseElevationMeters: 1300,
    resortTopElevationMeters: 2560,
    mountainRange: "Rila",
    linkedTouristPlaceId: null,
    linkedUnescoSiteId: null,
    snowReportUrl: null,
    liftStatusUrl: null,
  },
  {
    id: "mountain-pamporovo",
    canonicalName: "Pamporovo",
    nativeName: "Пампорово",
    aliases: [],
    category: "ski_resort",
    countryCodes: ["BG"],
    cityOrRegion: "Rhodope Mountains",
    latitude: 41.6608,
    longitude: 24.6828,
    wikidataId: "Q212892",
    officialWebsite: "https://www.pamporovo.me/en",
    tourismWebsite: null,
    seasonalOperation: "winter",
    summitElevationMeters: null,
    resortBaseElevationMeters: 1620,
    resortTopElevationMeters: 1926,
    mountainRange: "Rhodope Mountains",
    linkedTouristPlaceId: null,
    linkedUnescoSiteId: null,
    snowReportUrl: null,
    liftStatusUrl: null,
  },
  // — Slovakia, Poland, Czechia —
  {
    id: "mountain-jasna",
    canonicalName: "Jasná",
    nativeName: "Jasná",
    aliases: ["Jasna", "Chopok"],
    category: "ski_resort",
    countryCodes: ["SK"],
    cityOrRegion: "Low Tatras",
    latitude: 49.05,
    longitude: 19.5167,
    wikidataId: "Q212891",
    officialWebsite: "https://www.jasna.sk/en",
    tourismWebsite: null,
    seasonalOperation: "winter",
    summitElevationMeters: null,
    resortBaseElevationMeters: 950,
    resortTopElevationMeters: 2004,
    mountainRange: "Tatras",
    linkedTouristPlaceId: null,
    linkedUnescoSiteId: null,
    snowReportUrl: null,
    liftStatusUrl: null,
  },
  {
    id: "mountain-zakopane",
    canonicalName: "Zakopane",
    nativeName: null,
    aliases: ["Kasprowy Wierch", "Tatra Mountains ski"],
    category: "ski_resort",
    countryCodes: ["PL"],
    cityOrRegion: "Lesser Poland",
    latitude: 49.2992,
    longitude: 19.9492,
    wikidataId: "Q212890",
    officialWebsite: "https://www.zakopane.pl/en",
    tourismWebsite: null,
    seasonalOperation: "winter",
    summitElevationMeters: null,
    resortBaseElevationMeters: 850,
    resortTopElevationMeters: 1987,
    mountainRange: "Tatras",
    linkedTouristPlaceId: null,
    linkedUnescoSiteId: null,
    snowReportUrl: null,
    liftStatusUrl: null,
  },
  {
    id: "mountain-spindleruv-mlyn",
    canonicalName: "Špindlerův Mlýn",
    nativeName: "Špindlerův Mlýn",
    aliases: ["Spindleruv Mlyn", "Spindler"],
    category: "ski_resort",
    countryCodes: ["CZ"],
    cityOrRegion: "Krkonoše",
    latitude: 50.7261,
    longitude: 15.6086,
    wikidataId: "Q212889",
    officialWebsite: "https://www.spindleruv-mlyn.com/en",
    tourismWebsite: null,
    seasonalOperation: "winter",
    summitElevationMeters: null,
    resortBaseElevationMeters: 710,
    resortTopElevationMeters: 1235,
    mountainRange: "Krkonoše",
    linkedTouristPlaceId: null,
    linkedUnescoSiteId: null,
    snowReportUrl: null,
    liftStatusUrl: null,
  },
  // — Romania (ski) —
  {
    id: "mountain-poiana-brasov",
    canonicalName: "Poiana Brașov",
    nativeName: "Poiana Brașov",
    aliases: ["Poiana Brasov"],
    category: "ski_resort",
    countryCodes: ["RO"],
    cityOrRegion: "Brașov",
    latitude: 45.5986,
    longitude: 25.5564,
    wikidataId: "Q212888",
    officialWebsite: "https://www.poianabrasov.com/en",
    tourismWebsite: null,
    seasonalOperation: "winter",
    summitElevationMeters: null,
    resortBaseElevationMeters: 1030,
    resortTopElevationMeters: 1770,
    mountainRange: "Carpathians",
    linkedTouristPlaceId: null,
    linkedUnescoSiteId: null,
    snowReportUrl: null,
    liftStatusUrl: null,
  },
  {
    id: "mountain-sinaia",
    canonicalName: "Sinaia",
    nativeName: null,
    aliases: ["Bucegi Mountains ski"],
    category: "ski_resort",
    countryCodes: ["RO"],
    cityOrRegion: "Prahova Valley",
    latitude: 45.35,
    longitude: 25.5514,
    wikidataId: "Q212887",
    officialWebsite: "https://www.sinaia.ro/en",
    tourismWebsite: null,
    seasonalOperation: "winter",
    summitElevationMeters: null,
    resortBaseElevationMeters: 1200,
    resortTopElevationMeters: 2000,
    mountainRange: "Carpathians",
    linkedTouristPlaceId: null,
    linkedUnescoSiteId: null,
    snowReportUrl: null,
    liftStatusUrl: null,
  },
  {
    id: "mountain-busteni",
    canonicalName: "Bușteni",
    nativeName: "Bușteni",
    aliases: ["Busteni", "Kalinderu"],
    category: "ski_resort",
    countryCodes: ["RO"],
    cityOrRegion: "Prahova Valley",
    latitude: 45.4,
    longitude: 25.5333,
    wikidataId: "Q212886",
    officialWebsite: null,
    tourismWebsite: null,
    seasonalOperation: "winter",
    summitElevationMeters: null,
    resortBaseElevationMeters: 900,
    resortTopElevationMeters: 1500,
    mountainRange: "Carpathians",
    linkedTouristPlaceId: null,
    linkedUnescoSiteId: null,
    snowReportUrl: null,
    liftStatusUrl: null,
  },
  {
    id: "mountain-straja",
    canonicalName: "Straja",
    nativeName: null,
    aliases: [],
    category: "ski_resort",
    countryCodes: ["RO"],
    cityOrRegion: "Vâlcan Mountains",
    latitude: 45.3167,
    longitude: 23.15,
    wikidataId: "Q212885",
    officialWebsite: "https://www.straja.ro/en",
    tourismWebsite: null,
    seasonalOperation: "winter",
    summitElevationMeters: null,
    resortBaseElevationMeters: 1450,
    resortTopElevationMeters: 1875,
    mountainRange: "Carpathians",
    linkedTouristPlaceId: null,
    linkedUnescoSiteId: null,
    snowReportUrl: null,
    liftStatusUrl: null,
  },
  // — Slovenia, Balkans —
  {
    id: "mountain-bohinj-vogel",
    canonicalName: "Bohinj-Vogel",
    nativeName: null,
    aliases: ["Vogel", "Lake Bohinj"],
    category: "ski_resort",
    countryCodes: ["SI"],
    cityOrRegion: "Julian Alps",
    latitude: 46.2747,
    longitude: 13.8369,
    wikidataId: "Q212884",
    officialWebsite: "https://www.vogel.si/en",
    tourismWebsite: null,
    seasonalOperation: "winter",
    summitElevationMeters: null,
    resortBaseElevationMeters: 570,
    resortTopElevationMeters: 1800,
    mountainRange: "Julian Alps",
    linkedTouristPlaceId: null,
    linkedUnescoSiteId: null,
    snowReportUrl: null,
    liftStatusUrl: null,
  },
  {
    id: "mountain-kranjska-gora",
    canonicalName: "Kranjska Gora",
    nativeName: null,
    aliases: [],
    category: "ski_resort",
    countryCodes: ["SI"],
    cityOrRegion: "Julian Alps",
    latitude: 46.4844,
    longitude: 13.7864,
    wikidataId: "Q212883",
    officialWebsite: "https://www.kranjska-gora.si/en",
    tourismWebsite: null,
    seasonalOperation: "winter",
    summitElevationMeters: null,
    resortBaseElevationMeters: 810,
    resortTopElevationMeters: 1215,
    mountainRange: "Julian Alps",
    linkedTouristPlaceId: null,
    linkedUnescoSiteId: null,
    snowReportUrl: null,
    liftStatusUrl: null,
  },
  {
    id: "mountain-jahorina",
    canonicalName: "Jahorina",
    nativeName: "Jahorina",
    aliases: [],
    category: "ski_resort",
    countryCodes: ["BA"],
    cityOrRegion: "Republika Srpska",
    latitude: 43.7319,
    longitude: 18.5714,
    wikidataId: "Q212882",
    officialWebsite: "https://www.jahorina.org/en",
    tourismWebsite: null,
    seasonalOperation: "winter",
    summitElevationMeters: null,
    resortBaseElevationMeters: 1300,
    resortTopElevationMeters: 1916,
    mountainRange: "Dinaric Alps",
    linkedTouristPlaceId: null,
    linkedUnescoSiteId: null,
    snowReportUrl: null,
    liftStatusUrl: null,
  },
  {
    id: "mountain-brezovica",
    canonicalName: "Brezovica",
    nativeName: "Brezovicë",
    aliases: ["Sharr Mountains ski"],
    category: "ski_resort",
    countryCodes: ["XK"],
    cityOrRegion: "Šar Mountains",
    latitude: 42.1806,
    longitude: 21.01,
    wikidataId: "Q212881",
    officialWebsite: null,
    tourismWebsite: null,
    seasonalOperation: "winter",
    summitElevationMeters: null,
    resortBaseElevationMeters: 900,
    resortTopElevationMeters: 2212,
    mountainRange: "Šar Mountains",
    linkedTouristPlaceId: null,
    linkedUnescoSiteId: null,
    snowReportUrl: null,
    liftStatusUrl: null,
  },
  {
    id: "mountain-popova-sapka",
    canonicalName: "Popova Sapka",
    nativeName: "Попова Шапка",
    aliases: ["Popova Shapka", "Šar Mountains"],
    category: "ski_resort",
    countryCodes: ["MK"],
    cityOrRegion: "Tetovo",
    latitude: 42.1833,
    longitude: 21.5833,
    wikidataId: "Q212880",
    officialWebsite: null,
    tourismWebsite: null,
    seasonalOperation: "winter",
    summitElevationMeters: null,
    resortBaseElevationMeters: 1690,
    resortTopElevationMeters: 1780,
    mountainRange: "Šar Mountains",
    linkedTouristPlaceId: null,
    linkedUnescoSiteId: null,
    snowReportUrl: null,
    liftStatusUrl: null,
  },
  // — Nordic (ski) —
  {
    id: "mountain-are",
    canonicalName: "Åre",
    nativeName: "Åre",
    aliases: ["Are"],
    category: "ski_resort",
    countryCodes: ["SE"],
    cityOrRegion: "Jämtland",
    latitude: 63.3992,
    longitude: 13.0819,
    wikidataId: "Q212879",
    officialWebsite: "https://www.skistar.com/en/ski-destinations/are/",
    tourismWebsite: null,
    seasonalOperation: "winter",
    summitElevationMeters: null,
    resortBaseElevationMeters: 420,
    resortTopElevationMeters: 1274,
    mountainRange: "Scandinavian Mountains",
    linkedTouristPlaceId: null,
    linkedUnescoSiteId: null,
    snowReportUrl: null,
    liftStatusUrl: null,
  },
  {
    id: "mountain-levi",
    canonicalName: "Levi",
    nativeName: "Levi",
    aliases: ["Levi Ski Resort"],
    category: "ski_resort",
    countryCodes: ["FI"],
    cityOrRegion: "Lapland",
    latitude: 67.8047,
    longitude: 24.8075,
    wikidataId: "Q212878",
    officialWebsite: "https://www.levi.fi/en",
    tourismWebsite: null,
    seasonalOperation: "winter",
    summitElevationMeters: null,
    resortBaseElevationMeters: 200,
    resortTopElevationMeters: 531,
    mountainRange: "Scandinavian Mountains",
    linkedTouristPlaceId: null,
    linkedUnescoSiteId: null,
    snowReportUrl: null,
    liftStatusUrl: null,
  },
  {
    id: "mountain-ruka",
    canonicalName: "Ruka",
    nativeName: "Ruka",
    aliases: ["Rukatunturi"],
    category: "ski_resort",
    countryCodes: ["FI"],
    cityOrRegion: "Kuusamo",
    latitude: 66.1653,
    longitude: 29.1514,
    wikidataId: "Q212877",
    officialWebsite: "https://www.ruka.fi/en",
    tourismWebsite: null,
    seasonalOperation: "winter",
    summitElevationMeters: null,
    resortBaseElevationMeters: 291,
    resortTopElevationMeters: 492,
    mountainRange: "Scandinavian Mountains",
    linkedTouristPlaceId: null,
    linkedUnescoSiteId: null,
    snowReportUrl: null,
    liftStatusUrl: null,
  },
  {
    id: "mountain-geilo",
    canonicalName: "Geilo",
    nativeName: null,
    aliases: [],
    category: "ski_resort",
    countryCodes: ["NO"],
    cityOrRegion: "Buskerud",
    latitude: 60.5336,
    longitude: 8.2075,
    wikidataId: "Q212876",
    officialWebsite: "https://www.geilo.com/en",
    tourismWebsite: null,
    seasonalOperation: "winter",
    summitElevationMeters: null,
    resortBaseElevationMeters: 800,
    resortTopElevationMeters: 1178,
    mountainRange: "Scandinavian Mountains",
    linkedTouristPlaceId: null,
    linkedUnescoSiteId: null,
    snowReportUrl: null,
    liftStatusUrl: null,
  },
  {
    id: "mountain-hemsedal",
    canonicalName: "Hemsedal",
    nativeName: null,
    aliases: ["Scandinavian Alps"],
    category: "ski_resort",
    countryCodes: ["NO"],
    cityOrRegion: "Buskerud",
    latitude: 60.8611,
    longitude: 8.5653,
    wikidataId: "Q212875",
    officialWebsite: "https://www.hemsedal.com/en",
    tourismWebsite: null,
    seasonalOperation: "winter",
    summitElevationMeters: null,
    resortBaseElevationMeters: 625,
    resortTopElevationMeters: 1450,
    mountainRange: "Scandinavian Mountains",
    linkedTouristPlaceId: null,
    linkedUnescoSiteId: null,
    snowReportUrl: null,
    liftStatusUrl: null,
  },
  {
    id: "mountain-trysil",
    canonicalName: "Trysil",
    nativeName: null,
    aliases: [],
    category: "ski_resort",
    countryCodes: ["NO"],
    cityOrRegion: "Innlandet",
    latitude: 61.3156,
    longitude: 12.2631,
    wikidataId: "Q212874",
    officialWebsite: "https://www.trysil.no/en",
    tourismWebsite: null,
    seasonalOperation: "winter",
    summitElevationMeters: null,
    resortBaseElevationMeters: 500,
    resortTopElevationMeters: 1132,
    mountainRange: "Scandinavian Mountains",
    linkedTouristPlaceId: null,
    linkedUnescoSiteId: null,
    snowReportUrl: null,
    liftStatusUrl: null,
  },
  // — Iconic peaks —
  {
    id: "peak-mont-blanc",
    canonicalName: "Mont Blanc",
    nativeName: null,
    aliases: ["Monte Bianco"],
    category: "iconic_peak",
    countryCodes: ["FR", "IT"],
    cityOrRegion: "Alps",
    latitude: 45.8326,
    longitude: 6.8652,
    wikidataId: "Q583",
    officialWebsite: null,
    tourismWebsite: null,
    seasonalOperation: "year_round",
    summitElevationMeters: 4808,
    resortBaseElevationMeters: null,
    resortTopElevationMeters: null,
    mountainRange: "Alps",
    linkedTouristPlaceId: null,
    linkedUnescoSiteId: null,
    snowReportUrl: null,
    liftStatusUrl: null,
  },
  {
    id: "peak-matterhorn",
    canonicalName: "Matterhorn",
    nativeName: null,
    aliases: ["Monte Cervino", "Cervin"],
    category: "iconic_peak",
    countryCodes: ["CH", "IT"],
    cityOrRegion: "Pennine Alps",
    latitude: 45.9763,
    longitude: 7.6586,
    wikidataId: "Q10348",
    officialWebsite: null,
    tourismWebsite: null,
    seasonalOperation: "year_round",
    summitElevationMeters: 4478,
    resortBaseElevationMeters: null,
    resortTopElevationMeters: null,
    mountainRange: "Alps",
    linkedTouristPlaceId: "tourist-matterhorn",
    linkedUnescoSiteId: null,
    snowReportUrl: null,
    liftStatusUrl: null,
  },
  {
    id: "peak-eiger",
    canonicalName: "Eiger",
    nativeName: null,
    aliases: ["Eigernordwand", "North Face"],
    category: "iconic_peak",
    countryCodes: ["CH"],
    cityOrRegion: "Bernese Alps",
    latitude: 46.5772,
    longitude: 8.0053,
    wikidataId: "Q665",
    officialWebsite: null,
    tourismWebsite: null,
    seasonalOperation: "year_round",
    summitElevationMeters: 3967,
    resortBaseElevationMeters: null,
    resortTopElevationMeters: null,
    mountainRange: "Alps",
    linkedTouristPlaceId: null,
    linkedUnescoSiteId: null,
    snowReportUrl: null,
    liftStatusUrl: null,
  },
  {
    id: "peak-jungfrau",
    canonicalName: "Jungfrau",
    nativeName: null,
    aliases: ["Jungfraujoch area"],
    category: "iconic_peak",
    countryCodes: ["CH"],
    cityOrRegion: "Bernese Alps",
    latitude: 46.5369,
    longitude: 7.9625,
    wikidataId: "Q686",
    officialWebsite: null,
    tourismWebsite: null,
    seasonalOperation: "year_round",
    summitElevationMeters: 4158,
    resortBaseElevationMeters: null,
    resortTopElevationMeters: null,
    mountainRange: "Alps",
    linkedTouristPlaceId: "tourist-jungfraujoch",
    linkedUnescoSiteId: null,
    snowReportUrl: null,
    liftStatusUrl: null,
  },
  {
    id: "peak-zugspitze",
    canonicalName: "Zugspitze",
    nativeName: null,
    aliases: [],
    category: "iconic_peak",
    countryCodes: ["DE", "AT"],
    cityOrRegion: "Bavarian Alps",
    latitude: 47.4211,
    longitude: 10.9853,
    wikidataId: "Q3375",
    officialWebsite: null,
    tourismWebsite: null,
    seasonalOperation: "year_round",
    summitElevationMeters: 2962,
    resortBaseElevationMeters: null,
    resortTopElevationMeters: null,
    mountainRange: "Alps",
    linkedTouristPlaceId: "tourist-zugspitze",
    linkedUnescoSiteId: null,
    snowReportUrl: null,
    liftStatusUrl: null,
  },
  {
    id: "peak-triglav",
    canonicalName: "Triglav",
    nativeName: null,
    aliases: [],
    category: "iconic_peak",
    countryCodes: ["SI"],
    cityOrRegion: "Julian Alps",
    latitude: 46.3781,
    longitude: 13.8367,
    wikidataId: "Q1828",
    officialWebsite: null,
    tourismWebsite: null,
    seasonalOperation: "summer",
    summitElevationMeters: 2864,
    resortBaseElevationMeters: null,
    resortTopElevationMeters: null,
    mountainRange: "Julian Alps",
    linkedTouristPlaceId: null,
    linkedUnescoSiteId: null,
    snowReportUrl: null,
    liftStatusUrl: null,
  },
  {
    id: "peak-grossglockner",
    canonicalName: "Grossglockner",
    nativeName: "Großglockner",
    aliases: ["Grossglockner High Alpine Road"],
    category: "iconic_peak",
    countryCodes: ["AT"],
    cityOrRegion: "Hohe Tauern",
    latitude: 47.0744,
    longitude: 12.6939,
    wikidataId: "Q154946",
    officialWebsite: null,
    tourismWebsite: null,
    seasonalOperation: "summer",
    summitElevationMeters: 3798,
    resortBaseElevationMeters: null,
    resortTopElevationMeters: null,
    mountainRange: "Alps",
    linkedTouristPlaceId: null,
    linkedUnescoSiteId: null,
    snowReportUrl: null,
    liftStatusUrl: null,
  },
  {
    id: "peak-gerlachovsky-stit",
    canonicalName: "Gerlachovský štít",
    nativeName: "Gerlachovský štít",
    aliases: ["Gerlach", "Gerlachovsky stit"],
    category: "iconic_peak",
    countryCodes: ["SK"],
    cityOrRegion: "High Tatras",
    latitude: 49.1469,
    longitude: 20.2108,
    wikidataId: "Q930443",
    officialWebsite: null,
    tourismWebsite: null,
    seasonalOperation: "summer",
    summitElevationMeters: 2655,
    resortBaseElevationMeters: null,
    resortTopElevationMeters: null,
    mountainRange: "Tatras",
    linkedTouristPlaceId: null,
    linkedUnescoSiteId: null,
    snowReportUrl: null,
    liftStatusUrl: null,
  },
  {
    id: "peak-rysy",
    canonicalName: "Rysy",
    nativeName: null,
    aliases: [],
    category: "iconic_peak",
    countryCodes: ["PL", "SK"],
    cityOrRegion: "High Tatras",
    latitude: 49.1994,
    longitude: 20.0881,
    wikidataId: "Q847567",
    officialWebsite: null,
    tourismWebsite: null,
    seasonalOperation: "summer",
    summitElevationMeters: 2503,
    resortBaseElevationMeters: null,
    resortTopElevationMeters: null,
    mountainRange: "Tatras",
    linkedTouristPlaceId: null,
    linkedUnescoSiteId: null,
    snowReportUrl: null,
    liftStatusUrl: null,
  },
  {
    id: "peak-olympus",
    canonicalName: "Mount Olympus",
    nativeName: "Όλυμπος",
    aliases: ["Olympus", "Mytikas"],
    category: "iconic_peak",
    countryCodes: ["EL"],
    cityOrRegion: "Thessaly",
    latitude: 40.0856,
    longitude: 22.3586,
    wikidataId: "Q44148",
    officialWebsite: null,
    tourismWebsite: null,
    seasonalOperation: "summer",
    summitElevationMeters: 2918,
    resortBaseElevationMeters: null,
    resortTopElevationMeters: null,
    mountainRange: "Olympus",
    linkedTouristPlaceId: null,
    linkedUnescoSiteId: null,
    snowReportUrl: null,
    liftStatusUrl: null,
  },
  {
    id: "peak-ben-nevis",
    canonicalName: "Ben Nevis",
    nativeName: null,
    aliases: [],
    category: "iconic_peak",
    countryCodes: ["UK"],
    cityOrRegion: "Scottish Highlands",
    latitude: 56.7969,
    longitude: -5.0036,
    wikidataId: "Q178069",
    officialWebsite: null,
    tourismWebsite: null,
    seasonalOperation: "year_round",
    summitElevationMeters: 1345,
    resortBaseElevationMeters: null,
    resortTopElevationMeters: null,
    mountainRange: "Scottish Highlands",
    linkedTouristPlaceId: null,
    linkedUnescoSiteId: null,
    snowReportUrl: null,
    liftStatusUrl: null,
  },
  {
    id: "peak-kebnekaise",
    canonicalName: "Kebnekaise",
    nativeName: null,
    aliases: ["Giebnegáisi"],
    category: "iconic_peak",
    countryCodes: ["SE"],
    cityOrRegion: "Lapland",
    latitude: 67.9031,
    longitude: 18.5272,
    wikidataId: "Q207179",
    officialWebsite: null,
    tourismWebsite: null,
    seasonalOperation: "summer",
    summitElevationMeters: 2096,
    resortBaseElevationMeters: null,
    resortTopElevationMeters: null,
    mountainRange: "Scandinavian Mountains",
    linkedTouristPlaceId: null,
    linkedUnescoSiteId: null,
    snowReportUrl: null,
    liftStatusUrl: null,
  },
  {
    id: "peak-galdhopiggen",
    canonicalName: "Galdhøpiggen",
    nativeName: "Galdhøpiggen",
    aliases: ["Galdhopiggen"],
    category: "iconic_peak",
    countryCodes: ["NO"],
    cityOrRegion: "Jotunheimen",
    latitude: 61.6364,
    longitude: 8.3125,
    wikidataId: "Q18844",
    officialWebsite: null,
    tourismWebsite: null,
    seasonalOperation: "summer",
    summitElevationMeters: 2469,
    resortBaseElevationMeters: null,
    resortTopElevationMeters: null,
    mountainRange: "Scandinavian Mountains",
    linkedTouristPlaceId: null,
    linkedUnescoSiteId: null,
    snowReportUrl: null,
    liftStatusUrl: null,
  },
  {
    id: "peak-hvannadalshnukur",
    canonicalName: "Hvannadalshnúkur",
    nativeName: "Hvannadalshnúkur",
    aliases: ["Hvannadalshnukur", "Öræfajökull summit"],
    category: "iconic_peak",
    countryCodes: ["IS"],
    cityOrRegion: "Vatnajökull",
    latitude: 64.4167,
    longitude: -16.7833,
    wikidataId: "Q155060",
    officialWebsite: null,
    tourismWebsite: null,
    seasonalOperation: "summer",
    summitElevationMeters: 2110,
    resortBaseElevationMeters: null,
    resortTopElevationMeters: null,
    mountainRange: "Scandinavian Mountains",
    linkedTouristPlaceId: null,
    linkedUnescoSiteId: null,
    snowReportUrl: null,
    liftStatusUrl: null,
  },
  {
    id: "peak-musala",
    canonicalName: "Musala",
    nativeName: "Мусала",
    aliases: [],
    category: "iconic_peak",
    countryCodes: ["BG"],
    cityOrRegion: "Rila Mountains",
    latitude: 42.1792,
    longitude: 23.5853,
    wikidataId: "Q213228",
    officialWebsite: null,
    tourismWebsite: null,
    seasonalOperation: "summer",
    summitElevationMeters: 2925,
    resortBaseElevationMeters: null,
    resortTopElevationMeters: null,
    mountainRange: "Rila",
    linkedTouristPlaceId: null,
    linkedUnescoSiteId: null,
    snowReportUrl: null,
    liftStatusUrl: null,
  },
  {
    id: "peak-moldoveanu",
    canonicalName: "Moldoveanu",
    nativeName: null,
    aliases: ["Moldoveanu Peak"],
    category: "iconic_peak",
    countryCodes: ["RO"],
    cityOrRegion: "Făgăraș Mountains",
    latitude: 45.5986,
    longitude: 24.7361,
    wikidataId: "Q213229",
    officialWebsite: null,
    tourismWebsite: null,
    seasonalOperation: "summer",
    summitElevationMeters: 2544,
    resortBaseElevationMeters: null,
    resortTopElevationMeters: null,
    mountainRange: "Carpathians",
    linkedTouristPlaceId: null,
    linkedUnescoSiteId: null,
    snowReportUrl: null,
    liftStatusUrl: null,
  },
  {
    id: "peak-dinara",
    canonicalName: "Dinara",
    nativeName: null,
    aliases: ["Sinjal"],
    category: "iconic_peak",
    countryCodes: ["HR", "BA"],
    cityOrRegion: "Dinaric Alps",
    latitude: 44.0486,
    longitude: 16.3758,
    wikidataId: "Q213230",
    officialWebsite: null,
    tourismWebsite: null,
    seasonalOperation: "summer",
    summitElevationMeters: 1831,
    resortBaseElevationMeters: null,
    resortTopElevationMeters: null,
    mountainRange: "Dinaric Alps",
    linkedTouristPlaceId: null,
    linkedUnescoSiteId: null,
    snowReportUrl: null,
    liftStatusUrl: null,
  },
  {
    id: "peak-korab",
    canonicalName: "Korab",
    nativeName: null,
    aliases: ["Golem Korab"],
    category: "iconic_peak",
    countryCodes: ["AL", "MK"],
    cityOrRegion: "Šar Mountains",
    latitude: 41.7914,
    longitude: 20.5306,
    wikidataId: "Q213231",
    officialWebsite: null,
    tourismWebsite: null,
    seasonalOperation: "summer",
    summitElevationMeters: 2764,
    resortBaseElevationMeters: null,
    resortTopElevationMeters: null,
    mountainRange: "Šar Mountains",
    linkedTouristPlaceId: null,
    linkedUnescoSiteId: null,
    snowReportUrl: null,
    liftStatusUrl: null,
  },
  {
    id: "peak-titlis",
    canonicalName: "Titlis",
    nativeName: null,
    aliases: ["Mount Titlis"],
    category: "iconic_peak",
    countryCodes: ["CH"],
    cityOrRegion: "Uri Alps",
    latitude: 46.7725,
    longitude: 8.4369,
    wikidataId: "Q3376",
    officialWebsite: null,
    tourismWebsite: null,
    seasonalOperation: "year_round",
    summitElevationMeters: 3238,
    resortBaseElevationMeters: null,
    resortTopElevationMeters: null,
    mountainRange: "Alps",
    linkedTouristPlaceId: null,
    linkedUnescoSiteId: null,
    snowReportUrl: null,
    liftStatusUrl: null,
  },
  {
    id: "peak-aiguille-du-midi",
    canonicalName: "Aiguille du Midi",
    nativeName: null,
    aliases: ["Chamonix Aiguille du Midi"],
    category: "iconic_peak",
    countryCodes: ["FR"],
    cityOrRegion: "Mont Blanc massif",
    latitude: 45.8794,
    longitude: 6.8875,
    wikidataId: "Q399",
    officialWebsite: null,
    tourismWebsite: null,
    seasonalOperation: "year_round",
    summitElevationMeters: 3842,
    resortBaseElevationMeters: null,
    resortTopElevationMeters: null,
    mountainRange: "Alps",
    linkedTouristPlaceId: null,
    linkedUnescoSiteId: null,
    snowReportUrl: null,
    liftStatusUrl: null,
  },
  // — Mountain ranges (representative centroids) —
  {
    id: "range-dolomites",
    canonicalName: "Dolomites",
    nativeName: "Dolomiti",
    aliases: ["Dolomiti"],
    category: "mountain_range",
    countryCodes: ["IT"],
    cityOrRegion: "Northern Italy",
    latitude: 46.6131,
    longitude: 12.1631,
    wikidataId: "Q2155",
    officialWebsite: null,
    tourismWebsite: null,
    seasonalOperation: "year_round",
    summitElevationMeters: null,
    resortBaseElevationMeters: null,
    resortTopElevationMeters: null,
    mountainRange: "Dolomites",
    linkedTouristPlaceId: "tourist-dolomites",
    linkedUnescoSiteId: null,
    snowReportUrl: null,
    liftStatusUrl: null,
  },
  {
    id: "range-pyrenees",
    canonicalName: "Pyrenees",
    nativeName: "Pirineos",
    aliases: ["Pyrénées", "Pirineus"],
    category: "mountain_range",
    countryCodes: ["FR", "ES"],
    cityOrRegion: "Western Pyrenees",
    latitude: 42.6967,
    longitude: 0.6333,
    wikidataId: "Q12431",
    officialWebsite: null,
    tourismWebsite: null,
    seasonalOperation: "year_round",
    summitElevationMeters: null,
    resortBaseElevationMeters: null,
    resortTopElevationMeters: null,
    mountainRange: "Pyrenees",
    linkedTouristPlaceId: null,
    linkedUnescoSiteId: null,
    snowReportUrl: null,
    liftStatusUrl: null,
  },
  {
    id: "range-carpathians",
    canonicalName: "Carpathians",
    nativeName: null,
    aliases: ["Carpathian Mountains", "Karpaty"],
    category: "mountain_range",
    countryCodes: ["RO", "SK", "PL"],
    cityOrRegion: "Southern Carpathians",
    latitude: 45.5,
    longitude: 24.5,
    wikidataId: "Q1288",
    officialWebsite: null,
    tourismWebsite: null,
    seasonalOperation: "year_round",
    summitElevationMeters: null,
    resortBaseElevationMeters: null,
    resortTopElevationMeters: null,
    mountainRange: "Carpathians",
    linkedTouristPlaceId: null,
    linkedUnescoSiteId: null,
    snowReportUrl: null,
    liftStatusUrl: null,
  },
  {
    id: "range-tatras",
    canonicalName: "Tatra Mountains",
    nativeName: "Tatry",
    aliases: ["Tatras", "High Tatras"],
    category: "mountain_range",
    countryCodes: ["SK", "PL"],
    cityOrRegion: "High Tatras",
    latitude: 49.17,
    longitude: 19.9,
    wikidataId: "Q1289",
    officialWebsite: null,
    tourismWebsite: null,
    seasonalOperation: "year_round",
    summitElevationMeters: null,
    resortBaseElevationMeters: null,
    resortTopElevationMeters: null,
    mountainRange: "Tatras",
    linkedTouristPlaceId: null,
    linkedUnescoSiteId: null,
    snowReportUrl: null,
    liftStatusUrl: null,
  },
  {
    id: "range-western-alps",
    canonicalName: "Western Alps",
    nativeName: null,
    aliases: ["Alpes occidentales", "Alpi occidentali"],
    category: "mountain_range",
    countryCodes: ["FR", "CH", "IT"],
    cityOrRegion: "Central Alps",
    latitude: 46.5,
    longitude: 8.0,
    wikidataId: "Q1290",
    officialWebsite: null,
    tourismWebsite: null,
    seasonalOperation: "year_round",
    summitElevationMeters: null,
    resortBaseElevationMeters: null,
    resortTopElevationMeters: null,
    mountainRange: "Alps",
    linkedTouristPlaceId: null,
    linkedUnescoSiteId: null,
    snowReportUrl: null,
    liftStatusUrl: null,
  },
  {
    id: "range-scandinavian-mountains",
    canonicalName: "Scandinavian Mountains",
    nativeName: null,
    aliases: ["Scandes", "Kjølen"],
    category: "mountain_range",
    countryCodes: ["NO", "SE"],
    cityOrRegion: "Northern Scandinavia",
    latitude: 67.0,
    longitude: 15.0,
    wikidataId: "Q1291",
    officialWebsite: null,
    tourismWebsite: null,
    seasonalOperation: "year_round",
    summitElevationMeters: null,
    resortBaseElevationMeters: null,
    resortTopElevationMeters: null,
    mountainRange: "Scandinavian Mountains",
    linkedTouristPlaceId: null,
    linkedUnescoSiteId: null,
    snowReportUrl: null,
    liftStatusUrl: null,
  },
  {
    id: "range-scottish-highlands",
    canonicalName: "Scottish Highlands",
    nativeName: null,
    aliases: ["Highlands"],
    category: "mountain_range",
    countryCodes: ["UK"],
    cityOrRegion: "Scotland",
    latitude: 57.0,
    longitude: -4.5,
    wikidataId: "Q1292",
    officialWebsite: null,
    tourismWebsite: null,
    seasonalOperation: "year_round",
    summitElevationMeters: null,
    resortBaseElevationMeters: null,
    resortTopElevationMeters: null,
    mountainRange: "Scottish Highlands",
    linkedTouristPlaceId: null,
    linkedUnescoSiteId: null,
    snowReportUrl: null,
    liftStatusUrl: null,
  },
  {
    id: "range-apennines",
    canonicalName: "Apennines",
    nativeName: "Appennini",
    aliases: ["Appennini"],
    category: "mountain_range",
    countryCodes: ["IT"],
    cityOrRegion: "Central Italy",
    latitude: 43.0,
    longitude: 12.5,
    wikidataId: "Q1293",
    officialWebsite: null,
    tourismWebsite: null,
    seasonalOperation: "year_round",
    summitElevationMeters: null,
    resortBaseElevationMeters: null,
    resortTopElevationMeters: null,
    mountainRange: "Apennines",
    linkedTouristPlaceId: null,
    linkedUnescoSiteId: null,
    snowReportUrl: null,
    liftStatusUrl: null,
  },
  {
    id: "range-dinaric-alps",
    canonicalName: "Dinaric Alps",
    nativeName: null,
    aliases: ["Dinarides"],
    category: "mountain_range",
    countryCodes: ["HR", "BA", "ME"],
    cityOrRegion: "Western Balkans",
    latitude: 43.5,
    longitude: 17.5,
    wikidataId: "Q1294",
    officialWebsite: null,
    tourismWebsite: null,
    seasonalOperation: "year_round",
    summitElevationMeters: null,
    resortBaseElevationMeters: null,
    resortTopElevationMeters: null,
    mountainRange: "Dinaric Alps",
    linkedTouristPlaceId: null,
    linkedUnescoSiteId: null,
    snowReportUrl: null,
    liftStatusUrl: null,
  },
  {
    id: "range-cantabrian-mountains",
    canonicalName: "Cantabrian Mountains",
    nativeName: "Cordillera Cantábrica",
    aliases: ["Cordillera Cantabrica"],
    category: "mountain_range",
    countryCodes: ["ES"],
    cityOrRegion: "Northern Spain",
    latitude: 43.2,
    longitude: -4.8,
    wikidataId: "Q1295",
    officialWebsite: null,
    tourismWebsite: null,
    seasonalOperation: "year_round",
    summitElevationMeters: null,
    resortBaseElevationMeters: null,
    resortTopElevationMeters: null,
    mountainRange: "Cantabrian Mountains",
    linkedTouristPlaceId: null,
    linkedUnescoSiteId: null,
    snowReportUrl: null,
    liftStatusUrl: null,
  },
] as const;

export function getEuropeanMountainPlaceById(
  id: string,
): EuropeanMountainPlace | undefined {
  return EUROPEAN_MOUNTAIN_PLACES.find((place) => place.id === id);
}

function isWithinMapBounds(latitude: number, longitude: number): boolean {
  return (
    longitude >= UNESCO_EUROPE_MAP_BOUNDS.minLongitude &&
    longitude <= UNESCO_EUROPE_MAP_BOUNDS.maxLongitude &&
    latitude >= UNESCO_EUROPE_MAP_BOUNDS.minLatitude &&
    latitude <= UNESCO_EUROPE_MAP_BOUNDS.maxLatitude
  );
}

export function getDisplayableMountainPlaces(): readonly EuropeanMountainPlace[] {
  return EUROPEAN_MOUNTAIN_PLACES.filter(
    (place) =>
      isWithinMapBounds(place.latitude, place.longitude) &&
      place.countryCodes.every((code) => isAllowedUnescoMapCountry(code)),
  );
}

export function validateEuropeanMountainPlaces(): {
  total: number;
  errors: string[];
  byCategory: Record<string, number>;
  byCountry: Record<string, number>;
  entriesWithoutOfficialWebsite: string[];
} {
  const errors: string[] = [];
  const ids = new Set<string>();
  const namesAndCoordinates = new Set<string>();
  const entriesWithoutOfficialWebsite: string[] = [];
  const byCategory = Object.fromEntries(
    CATEGORIES.map((c) => [c, 0]),
  ) as Record<string, number>;
  const byCountry: Record<string, number> = {};

  for (const place of EUROPEAN_MOUNTAIN_PLACES) {
    if (ids.has(place.id)) {
      errors.push(`duplicate id: ${place.id}`);
    }
    ids.add(place.id);

    const locationKey = `${place.canonicalName.toLocaleLowerCase()}|${place.latitude.toFixed(4)}|${place.longitude.toFixed(4)}`;
    if (namesAndCoordinates.has(locationKey)) {
      errors.push(`duplicate place/location: ${place.id}`);
    }
    namesAndCoordinates.add(locationKey);

    if (!CATEGORIES.includes(place.category)) {
      errors.push(`invalid category for ${place.id}`);
    } else {
      byCategory[place.category] = (byCategory[place.category] ?? 0) + 1;
    }

    if (!place.canonicalName.trim() || !place.cityOrRegion.trim()) {
      errors.push(`empty name/city for ${place.id}`);
    }

    for (const code of place.countryCodes) {
      if (!isAllowedUnescoMapCountry(code)) {
        errors.push(`country not allowed: ${code} (${place.id})`);
      }
      byCountry[code] = (byCountry[code] ?? 0) + 1;
    }

    if (!isWithinMapBounds(place.latitude, place.longitude)) {
      errors.push(`coords out of bounds: ${place.id}`);
    }
    if (
      !Number.isFinite(place.latitude) ||
      !Number.isFinite(place.longitude) ||
      place.latitude < -90 ||
      place.latitude > 90 ||
      place.longitude < -180 ||
      place.longitude > 180
    ) {
      errors.push(`invalid coordinates: ${place.id}`);
    }

    if (place.wikidataId && !/^Q[1-9]\d*$/.test(place.wikidataId)) {
      errors.push(`invalid Wikidata id: ${place.id}`);
    }

    for (const url of [
      place.officialWebsite,
      place.tourismWebsite,
      place.snowReportUrl,
      place.liftStatusUrl,
    ]) {
      if (url && !url.startsWith("https://")) {
        errors.push(`non-https url for ${place.id}`);
      }
    }

    if (!place.officialWebsite) {
      entriesWithoutOfficialWebsite.push(place.id);
    }

    for (const [label, elevation] of [
      ["summit", place.summitElevationMeters],
      ["base", place.resortBaseElevationMeters],
      ["top", place.resortTopElevationMeters],
    ] as const) {
      if (elevation != null && (elevation < 0 || elevation > 5_000)) {
        errors.push(`implausible ${label} elevation: ${place.id}`);
      }
    }
    if (
      place.resortBaseElevationMeters != null &&
      place.resortTopElevationMeters != null &&
      place.resortBaseElevationMeters >= place.resortTopElevationMeters
    ) {
      errors.push(`resort base is not below top: ${place.id}`);
    }

    if (place.category === "iconic_peak") {
      if (place.summitElevationMeters == null) {
        errors.push(`iconic_peak missing summit elevation: ${place.id}`);
      }
      if (
        place.resortBaseElevationMeters != null ||
        place.resortTopElevationMeters != null
      ) {
        errors.push(`iconic_peak should not have resort elevations: ${place.id}`);
      }
    }

    if (place.category === "ski_resort") {
      if (
        place.resortBaseElevationMeters == null &&
        place.resortTopElevationMeters == null
      ) {
        errors.push(`ski_resort missing resort elevations: ${place.id}`);
      }
      if (place.summitElevationMeters != null) {
        errors.push(
          `ski_resort should use resort elevations, not summit: ${place.id}`,
        );
      }
    }
  }

  return {
    total: EUROPEAN_MOUNTAIN_PLACES.length,
    errors,
    byCategory,
    byCountry,
    entriesWithoutOfficialWebsite,
  };
}

if (process.env.NODE_ENV !== "production") {
  const validation = validateEuropeanMountainPlaces();
  if (validation.errors.length > 0) {
    console.error(
      "[europeanMountainDestinations]",
      validation.errors.join("; "),
    );
  }
}
