import type { Locale } from "@/lib/i18n/config";
import {
  UNESCO_EUROPE_MAP_BOUNDS,
  UNESCO_MAP_COUNTRY_CODES,
  isAllowedUnescoMapCountry,
} from "@/lib/tourism/unescoEuropeCoverage";
import { getUnescoSiteById } from "@/lib/tourism/unescoWorldHeritage";

export type TouristPlaceCategory =
  | "landmark"
  | "historic_area"
  | "museum"
  | "park_garden"
  | "natural_landscape"
  | "coastal_destination"
  | "mountain_destination";

export type MajorTouristPlace = {
  id: string;
  canonicalName: string;
  countryCode: string;
  cityOrRegion: string;
  latitude: number;
  longitude: number;
  category: TouristPlaceCategory;
  wikidataId: string;
  officialWebsite: string | null;
  tourismWebsite: string | null;
  wikipediaTitles?: Partial<Record<Locale, string>>;
  aliases: string[];
  unescoSiteId: string | null;
};

const CATEGORIES: readonly TouristPlaceCategory[] = [
  "landmark",
  "historic_area",
  "museum",
  "park_garden",
  "natural_landscape",
  "coastal_destination",
  "mountain_destination",
] as const;

export const MAJOR_TOURIST_PLACES: readonly MajorTouristPlace[] = [
  {
    id: "tourist-eiffel-tower",
    canonicalName: "Eiffel Tower",
    countryCode: "FR",
    cityOrRegion: "Paris",
    latitude: 48.8583,
    longitude: 2.29448,
    category: "landmark",
    wikidataId: "Q243",
    officialWebsite: "https://www.toureiffel.paris/en",
    tourismWebsite: null,
    aliases: ["Tour Eiffel", "Eiffel"],
    unescoSiteId: null,
  },
  {
    id: "tourist-louvre",
    canonicalName: "Louvre Museum",
    countryCode: "FR",
    cityOrRegion: "Paris",
    latitude: 48.86111,
    longitude: 2.33583,
    category: "museum",
    wikidataId: "Q19675",
    officialWebsite: "https://www.louvre.fr/en",
    tourismWebsite: null,
    aliases: ["Louvre", "Musée du Louvre"],
    unescoSiteId: null,
  },
  {
    id: "tourist-mont-saint-michel",
    canonicalName: "Mont-Saint-Michel",
    countryCode: "FR",
    cityOrRegion: "Normandy",
    latitude: 48.636,
    longitude: -1.511,
    category: "historic_area",
    wikidataId: "Q130846",
    officialWebsite: "https://www.abbaye-mont-saint-michel.fr/en/",
    tourismWebsite: null,
    aliases: ["Mont Saint-Michel"],
    unescoSiteId: "unesco-80",
  },
  {
    id: "tourist-versailles",
    canonicalName: "Palace of Versailles",
    countryCode: "FR",
    cityOrRegion: "Versailles",
    latitude: 48.80472,
    longitude: 2.12028,
    category: "historic_area",
    wikidataId: "Q2946",
    officialWebsite: "https://en.chateauversailles.fr/",
    tourismWebsite: null,
    aliases: ["Versailles"],
    unescoSiteId: "unesco-83",
  },
  {
    id: "tourist-notre-dame-paris",
    canonicalName: "Notre-Dame de Paris",
    countryCode: "FR",
    cityOrRegion: "Paris",
    latitude: 48.853,
    longitude: 2.3498,
    category: "landmark",
    wikidataId: "Q2981",
    officialWebsite: "https://www.notredamedeparis.fr/en/",
    tourismWebsite: null,
    aliases: ["Notre-Dame"],
    unescoSiteId: null,
  },
  {
    id: "tourist-chambord",
    canonicalName: "Château de Chambord",
    countryCode: "FR",
    cityOrRegion: "Loire Valley",
    latitude: 47.61611,
    longitude: 1.51722,
    category: "landmark",
    wikidataId: "Q205367",
    officialWebsite: "https://www.chambord.org/en/",
    tourismWebsite: null,
    aliases: ["Chambord"],
    unescoSiteId: null,
  },
  {
    id: "tourist-french-riviera",
    canonicalName: "French Riviera",
    countryCode: "FR",
    cityOrRegion: "Côte d'Azur",
    latitude: 43.32,
    longitude: 6.665,
    category: "coastal_destination",
    wikidataId: "Q182822",
    officialWebsite: "https://www.cotedazurfrance.fr/en/",
    tourismWebsite: null,
    aliases: ["Côte d'Azur"],
    unescoSiteId: null,
  },
  {
    id: "tourist-neuschwanstein",
    canonicalName: "Neuschwanstein Castle",
    countryCode: "DE",
    cityOrRegion: "Bavaria",
    latitude: 47.5576,
    longitude: 10.7498,
    category: "landmark",
    wikidataId: "Q4152",
    officialWebsite: "https://www.neuschwanstein.de/",
    tourismWebsite: null,
    aliases: ["Neuschwanstein"],
    unescoSiteId: "unesco-1726",
  },
  {
    id: "tourist-brandenburg-gate",
    canonicalName: "Brandenburg Gate",
    countryCode: "DE",
    cityOrRegion: "Berlin",
    latitude: 52.51627,
    longitude: 13.3777,
    category: "landmark",
    wikidataId: "Q82425",
    officialWebsite: "https://www.visitberlin.de/en/brandenburg-gate",
    tourismWebsite: null,
    aliases: ["Brandenburger Tor"],
    unescoSiteId: null,
  },
  {
    id: "tourist-cologne-cathedral",
    canonicalName: "Cologne Cathedral",
    countryCode: "DE",
    cityOrRegion: "Cologne",
    latitude: 50.9413,
    longitude: 6.9583,
    category: "landmark",
    wikidataId: "Q4176",
    officialWebsite: "https://www.koelner-dom.de/",
    tourismWebsite: null,
    aliases: ["Kölner Dom"],
    unescoSiteId: null,
  },
  {
    id: "tourist-east-side-gallery",
    canonicalName: "East Side Gallery",
    countryCode: "DE",
    cityOrRegion: "Berlin",
    latitude: 52.50306,
    longitude: 13.44472,
    category: "historic_area",
    wikidataId: "Q313746",
    officialWebsite: null,
    tourismWebsite: null,
    aliases: ["Berlin Wall Gallery"],
    unescoSiteId: null,
  },
  {
    id: "tourist-zugspitze",
    canonicalName: "Zugspitze",
    countryCode: "DE",
    cityOrRegion: "Bavarian Alps",
    latitude: 47.42122,
    longitude: 10.98631,
    category: "mountain_destination",
    wikidataId: "Q3375",
    officialWebsite: "https://zugspitze.de/en",
    tourismWebsite: null,
    aliases: ["Zugspitze"],
    unescoSiteId: null,
  },
  {
    id: "tourist-black-forest",
    canonicalName: "Black Forest",
    countryCode: "DE",
    cityOrRegion: "Baden-Württemberg",
    latitude: 48.3,
    longitude: 8.15,
    category: "natural_landscape",
    wikidataId: "Q4204",
    officialWebsite: "https://www.blackforest-tourism.com/",
    tourismWebsite: null,
    aliases: ["Schwarzwald"],
    unescoSiteId: null,
  },
  {
    id: "tourist-colosseum",
    canonicalName: "Colosseum",
    countryCode: "IT",
    cityOrRegion: "Rome",
    latitude: 41.89028,
    longitude: 12.49222,
    category: "landmark",
    wikidataId: "Q10285",
    officialWebsite: "https://colosseo.it/en/",
    tourismWebsite: null,
    aliases: ["Colosseo"],
    unescoSiteId: "unesco-91",
  },
  {
    id: "tourist-roman-forum",
    canonicalName: "Roman Forum",
    countryCode: "IT",
    cityOrRegion: "Rome",
    latitude: 41.8922,
    longitude: 12.4852,
    category: "historic_area",
    wikidataId: "Q180212",
    officialWebsite: "https://colosseo.it/en/area/foro-romano/",
    tourismWebsite: null,
    aliases: ["Foro Romano"],
    unescoSiteId: null,
  },
  {
    id: "tourist-uffizi",
    canonicalName: "Uffizi Gallery",
    countryCode: "IT",
    cityOrRegion: "Florence",
    latitude: 43.76833,
    longitude: 11.25528,
    category: "museum",
    wikidataId: "Q51252",
    officialWebsite: "https://www.uffizi.it/en",
    tourismWebsite: null,
    aliases: ["Uffizi"],
    unescoSiteId: "unesco-174",
  },
  {
    id: "tourist-cinque-terre",
    canonicalName: "Cinque Terre",
    countryCode: "IT",
    cityOrRegion: "Liguria",
    latitude: 44.12694,
    longitude: 9.70944,
    category: "coastal_destination",
    wikidataId: "Q275639",
    officialWebsite: "https://www.parconazionale5terre.it/Eindex.php",
    tourismWebsite: null,
    aliases: ["5 Terre"],
    unescoSiteId: "unesco-826",
  },
  {
    id: "tourist-dolomites",
    canonicalName: "Dolomites",
    countryCode: "IT",
    cityOrRegion: "Alps",
    latitude: 46.61306,
    longitude: 12.16306,
    category: "mountain_destination",
    wikidataId: "Q1283",
    officialWebsite: "https://www.dolomitiunesco.info/en/",
    tourismWebsite: null,
    aliases: ["Dolomiti"],
    unescoSiteId: "unesco-1237",
  },
  {
    id: "tourist-pantheon-rome",
    canonicalName: "Pantheon",
    countryCode: "IT",
    cityOrRegion: "Rome",
    latitude: 41.89861,
    longitude: 12.47694,
    category: "landmark",
    wikidataId: "Q99309",
    officialWebsite: "https://www.pantheonroma.com/en/",
    tourismWebsite: null,
    aliases: ["Pantheon"],
    unescoSiteId: null,
  },
  {
    id: "tourist-venice",
    canonicalName: "Venice Historic Centre",
    countryCode: "IT",
    cityOrRegion: "Venice",
    latitude: 45.4375,
    longitude: 12.3358,
    category: "historic_area",
    wikidataId: "Q641",
    officialWebsite: "https://www.visitvenezia.eu/en",
    tourismWebsite: null,
    aliases: ["Venezia"],
    unescoSiteId: null,
  },
  {
    id: "tourist-sagrada-familia",
    canonicalName: "Sagrada Família",
    countryCode: "ES",
    cityOrRegion: "Barcelona",
    latitude: 41.40369,
    longitude: 2.17403,
    category: "landmark",
    wikidataId: "Q48435",
    officialWebsite: "https://sagradafamilia.org/en/",
    tourismWebsite: null,
    aliases: ["Sagrada Familia"],
    unescoSiteId: null,
  },
  {
    id: "tourist-alhambra",
    canonicalName: "Alhambra",
    countryCode: "ES",
    cityOrRegion: "Granada",
    latitude: 37.17634,
    longitude: -3.58821,
    category: "historic_area",
    wikidataId: "Q47476",
    officialWebsite: "https://www.alhambra-patronato.es/en",
    tourismWebsite: null,
    aliases: ["Alhambra"],
    unescoSiteId: "unesco-314",
  },
  {
    id: "tourist-prado",
    canonicalName: "Prado Museum",
    countryCode: "ES",
    cityOrRegion: "Madrid",
    latitude: 40.41389,
    longitude: -3.69222,
    category: "museum",
    wikidataId: "Q160112",
    officialWebsite: "https://www.museodelprado.es/en",
    tourismWebsite: null,
    aliases: ["Museo del Prado"],
    unescoSiteId: null,
  },
  {
    id: "tourist-seville-cathedral",
    canonicalName: "Seville Cathedral",
    countryCode: "ES",
    cityOrRegion: "Seville",
    latitude: 37.3862,
    longitude: -5.9925,
    category: "landmark",
    wikidataId: "Q231606",
    officialWebsite: "https://www.catedraldesevilla.es/en/",
    tourismWebsite: null,
    aliases: ["Catedral de Sevilla"],
    unescoSiteId: null,
  },
  {
    id: "tourist-ibiza",
    canonicalName: "Ibiza",
    countryCode: "ES",
    cityOrRegion: "Balearic Islands",
    latitude: 38.98,
    longitude: 1.43,
    category: "coastal_destination",
    wikidataId: "Q52631",
    officialWebsite: "https://www.ibiza.travel/en/",
    tourismWebsite: null,
    aliases: ["Eivissa"],
    unescoSiteId: null,
  },
  {
    id: "tourist-tower-of-london",
    canonicalName: "Tower of London",
    countryCode: "UK",
    cityOrRegion: "London",
    latitude: 51.5082,
    longitude: -0.0762,
    category: "historic_area",
    wikidataId: "Q62378",
    officialWebsite: "https://www.hrp.org.uk/tower-of-london/",
    tourismWebsite: null,
    aliases: ["Tower of London"],
    unescoSiteId: "unesco-488",
  },
  {
    id: "tourist-british-museum",
    canonicalName: "British Museum",
    countryCode: "UK",
    cityOrRegion: "London",
    latitude: 51.51944,
    longitude: -0.12694,
    category: "museum",
    wikidataId: "Q6373",
    officialWebsite: "https://www.britishmuseum.org/",
    tourismWebsite: null,
    aliases: ["British Museum"],
    unescoSiteId: null,
  },
  {
    id: "tourist-stonehenge",
    canonicalName: "Stonehenge",
    countryCode: "UK",
    cityOrRegion: "Wiltshire",
    latitude: 51.17889,
    longitude: -1.82611,
    category: "landmark",
    wikidataId: "Q39671",
    officialWebsite: "https://www.english-heritage.org.uk/visit/places/stonehenge/",
    tourismWebsite: null,
    aliases: ["Stonehenge"],
    unescoSiteId: "unesco-373",
  },
  {
    id: "tourist-edinburgh-castle",
    canonicalName: "Edinburgh Castle",
    countryCode: "UK",
    cityOrRegion: "Edinburgh",
    latitude: 55.9486,
    longitude: -3.1999,
    category: "landmark",
    wikidataId: "Q212065",
    officialWebsite: "https://www.edinburghcastle.scot/",
    tourismWebsite: null,
    aliases: ["Edinburgh Castle"],
    unescoSiteId: null,
  },
  {
    id: "tourist-giants-causeway",
    canonicalName: "Giant's Causeway",
    countryCode: "UK",
    cityOrRegion: "Northern Ireland",
    latitude: 55.2408,
    longitude: -6.5116,
    category: "natural_landscape",
    wikidataId: "Q193479",
    officialWebsite: "https://www.nationaltrust.org.uk/visit/northern-ireland/giants-causeway",
    tourismWebsite: null,
    aliases: ["Giants Causeway"],
    unescoSiteId: null,
  },
  {
    id: "tourist-matterhorn",
    canonicalName: "Matterhorn",
    countryCode: "CH",
    cityOrRegion: "Zermatt",
    latitude: 45.9763,
    longitude: 7.6586,
    category: "mountain_destination",
    wikidataId: "Q1374",
    officialWebsite: "https://www.zermatt.ch/en",
    tourismWebsite: null,
    aliases: ["Cervin"],
    unescoSiteId: null,
  },
  {
    id: "tourist-jungfraujoch",
    canonicalName: "Jungfraujoch",
    countryCode: "CH",
    cityOrRegion: "Bernese Alps",
    latitude: 46.5476,
    longitude: 7.9851,
    category: "mountain_destination",
    wikidataId: "Q665676",
    officialWebsite: "https://www.jungfrau.ch/en-gb/",
    tourismWebsite: null,
    aliases: ["Top of Europe"],
    unescoSiteId: null,
  },
  {
    id: "tourist-geirangerfjord",
    canonicalName: "Geirangerfjord",
    countryCode: "NO",
    cityOrRegion: "Møre og Romsdal",
    latitude: 62.1042,
    longitude: 7.0942,
    category: "natural_landscape",
    wikidataId: "Q193989",
    officialWebsite: "https://www.visitnorway.com/",
    tourismWebsite: null,
    aliases: ["Geiranger"],
    unescoSiteId: null,
  },
  {
    id: "tourist-bryggen",
    canonicalName: "Bryggen",
    countryCode: "NO",
    cityOrRegion: "Bergen",
    latitude: 60.3975,
    longitude: 5.3242,
    category: "historic_area",
    wikidataId: "Q216085",
    officialWebsite: "https://www.visitbergen.com/",
    tourismWebsite: null,
    aliases: ["Bryggen"],
    unescoSiteId: null,
  },
  {
    id: "tourist-atomium",
    canonicalName: "Atomium",
    countryCode: "BE",
    cityOrRegion: "Brussels",
    latitude: 50.895,
    longitude: 4.34139,
    category: "landmark",
    wikidataId: "Q180901",
    officialWebsite: "https://atomium.be/",
    tourismWebsite: null,
    aliases: ["Atomium"],
    unescoSiteId: null,
  },
  {
    id: "tourist-grand-place-brussels",
    canonicalName: "Grand-Place Brussels",
    countryCode: "BE",
    cityOrRegion: "Brussels",
    latitude: 50.8467,
    longitude: 4.3525,
    category: "historic_area",
    wikidataId: "Q208099",
    officialWebsite: "https://www.brussels.be/grand-place",
    tourismWebsite: null,
    aliases: ["Grote Markt"],
    unescoSiteId: "unesco-857",
  },
  {
    id: "tourist-bruges",
    canonicalName: "Historic Centre of Bruges",
    countryCode: "BE",
    cityOrRegion: "Bruges",
    latitude: 51.2093,
    longitude: 3.2247,
    category: "historic_area",
    wikidataId: "Q12991",
    officialWebsite: "https://www.visitbruges.be/en",
    tourismWebsite: null,
    aliases: ["Brugge"],
    unescoSiteId: null,
  },
  {
    id: "tourist-rijksmuseum",
    canonicalName: "Rijksmuseum",
    countryCode: "NL",
    cityOrRegion: "Amsterdam",
    latitude: 52.36,
    longitude: 4.88528,
    category: "museum",
    wikidataId: "Q190804",
    officialWebsite: "https://www.rijksmuseum.nl/en",
    tourismWebsite: null,
    aliases: ["Rijksmuseum"],
    unescoSiteId: null,
  },
  {
    id: "tourist-anne-frank-house",
    canonicalName: "Anne Frank House",
    countryCode: "NL",
    cityOrRegion: "Amsterdam",
    latitude: 52.37515,
    longitude: 4.88404,
    category: "museum",
    wikidataId: "Q165366",
    officialWebsite: "https://www.annefrank.org/en/",
    tourismWebsite: null,
    aliases: ["Anne Frank"],
    unescoSiteId: null,
  },
  {
    id: "tourist-keukenhof",
    canonicalName: "Keukenhof",
    countryCode: "NL",
    cityOrRegion: "Lisse",
    latitude: 52.271,
    longitude: 4.5467,
    category: "park_garden",
    wikidataId: "Q153516",
    officialWebsite: "https://keukenhof.nl/en/",
    tourismWebsite: null,
    aliases: ["Keukenhof"],
    unescoSiteId: null,
  },
  {
    id: "tourist-amsterdam-canals",
    canonicalName: "Amsterdam Canal Ring",
    countryCode: "NL",
    cityOrRegion: "Amsterdam",
    latitude: 52.3667,
    longitude: 4.8945,
    category: "historic_area",
    wikidataId: "Q478538",
    officialWebsite: "https://www.iamsterdam.com/en",
    tourismWebsite: null,
    aliases: ["Grachtengordel"],
    unescoSiteId: null,
  },
  {
    id: "tourist-acropolis",
    canonicalName: "Acropolis of Athens",
    countryCode: "EL",
    cityOrRegion: "Athens",
    latitude: 37.97167,
    longitude: 23.72611,
    category: "landmark",
    wikidataId: "Q131013",
    officialWebsite: "https://www.acropolisofathens.gr/",
    tourismWebsite: null,
    aliases: ["Acropolis"],
    unescoSiteId: "unesco-404",
  },
  {
    id: "tourist-santorini",
    canonicalName: "Santorini",
    countryCode: "EL",
    cityOrRegion: "Cyclades",
    latitude: 36.415,
    longitude: 25.4325,
    category: "coastal_destination",
    wikidataId: "Q129296",
    officialWebsite: "https://www.santorini.gr/?lang=en",
    tourismWebsite: null,
    aliases: ["Thira"],
    unescoSiteId: null,
  },
  {
    id: "tourist-meteora",
    canonicalName: "Meteora",
    countryCode: "EL",
    cityOrRegion: "Thessaly",
    latitude: 39.7125,
    longitude: 21.62667,
    category: "natural_landscape",
    wikidataId: "Q3125051",
    officialWebsite: "https://www.visitgreece.gr/",
    tourismWebsite: null,
    aliases: ["Metéora"],
    unescoSiteId: null,
  },
  {
    id: "tourist-knossos",
    canonicalName: "Knossos",
    countryCode: "EL",
    cityOrRegion: "Crete",
    latitude: 35.29796,
    longitude: 25.16316,
    category: "historic_area",
    wikidataId: "Q173527",
    officialWebsite: "https://www.visitgreece.gr/",
    tourismWebsite: null,
    aliases: ["Knossos"],
    unescoSiteId: null,
  },
  {
    id: "tourist-ioannina",
    canonicalName: "Ioannina",
    countryCode: "EL",
    cityOrRegion: "Epirus",
    latitude: 39.6636,
    longitude: 20.8522,
    category: "historic_area",
    wikidataId: "Q183199",
    officialWebsite: "https://ioannina.gr/",
    tourismWebsite: "https://www.visitgreece.gr/mainland/epirus/ioannina/",
    wikipediaTitles: { en: "Ioannina", fr: "Ioannina" },
    aliases: ["Ιωάννινα", "Ioánnina", "Janina"],
    unescoSiteId: null,
  },
  {
    id: "tourist-cliffs-of-moher",
    canonicalName: "Cliffs of Moher",
    countryCode: "IE",
    cityOrRegion: "County Clare",
    latitude: 52.9715,
    longitude: -9.4309,
    category: "natural_landscape",
    wikidataId: "Q242947",
    officialWebsite: "https://www.cliffsofmoher.ie/",
    tourismWebsite: null,
    aliases: ["Cliffs of Moher"],
    unescoSiteId: null,
  },
  {
    id: "tourist-trinity-college-dublin",
    canonicalName: "Trinity College Dublin",
    countryCode: "IE",
    cityOrRegion: "Dublin",
    latitude: 53.3438,
    longitude: -6.2546,
    category: "historic_area",
    wikidataId: "Q258464",
    officialWebsite: "https://www.tcd.ie/",
    tourismWebsite: null,
    aliases: ["Trinity College"],
    unescoSiteId: null,
  },
  {
    id: "tourist-ring-of-kerry",
    canonicalName: "Ring of Kerry",
    countryCode: "IE",
    cityOrRegion: "County Kerry",
    latitude: 51.95,
    longitude: -9.9167,
    category: "natural_landscape",
    wikidataId: "Q1585862",
    officialWebsite: "https://www.ringofkerrytourism.com/",
    tourismWebsite: null,
    aliases: ["Ring of Kerry"],
    unescoSiteId: null,
  },
  {
    id: "tourist-jeronimos",
    canonicalName: "Jerónimos Monastery",
    countryCode: "PT",
    cityOrRegion: "Lisbon",
    latitude: 38.6977,
    longitude: -9.2065,
    category: "historic_area",
    wikidataId: "Q216985",
    officialWebsite: "https://www.mosteirojeronimos.gov.pt/en/",
    tourismWebsite: null,
    aliases: ["Jerónimos"],
    unescoSiteId: null,
  },
  {
    id: "tourist-pena-palace",
    canonicalName: "Pena Palace",
    countryCode: "PT",
    cityOrRegion: "Sintra",
    latitude: 38.7876,
    longitude: -9.3906,
    category: "landmark",
    wikidataId: "Q258053",
    officialWebsite: "https://www.parquesdesintra.pt/en/",
    tourismWebsite: null,
    aliases: ["Palácio da Pena"],
    unescoSiteId: null,
  },
  {
    id: "tourist-algarve",
    canonicalName: "Algarve",
    countryCode: "PT",
    cityOrRegion: "Algarve",
    latitude: 37.01444,
    longitude: -7.93528,
    category: "coastal_destination",
    wikidataId: "Q26831",
    officialWebsite: "https://www.visitalgarve.pt/en/",
    tourismWebsite: null,
    aliases: ["Algarve"],
    unescoSiteId: null,
  },
  {
    id: "tourist-wawel",
    canonicalName: "Wawel Castle",
    countryCode: "PL",
    cityOrRegion: "Kraków",
    latitude: 50.05437,
    longitude: 19.93558,
    category: "landmark",
    wikidataId: "Q188565",
    officialWebsite: "https://wawel.krakow.pl/en/",
    tourismWebsite: null,
    aliases: ["Wawel"],
    unescoSiteId: null,
  },
  {
    id: "tourist-auschwitz",
    canonicalName: "Auschwitz-Birkenau",
    countryCode: "PL",
    cityOrRegion: "Oświęcim",
    latitude: 50.0344,
    longitude: 19.1784,
    category: "historic_area",
    wikidataId: "Q7341",
    officialWebsite: "https://www.auschwitz.org/en/",
    tourismWebsite: null,
    aliases: ["Auschwitz"],
    unescoSiteId: null,
  },
  {
    id: "tourist-warsaw-old-town",
    canonicalName: "Warsaw Old Town",
    countryCode: "PL",
    cityOrRegion: "Warsaw",
    latitude: 52.2497,
    longitude: 21.0122,
    category: "historic_area",
    wikidataId: "Q270",
    officialWebsite: "https://warsawtour.pl/en/",
    tourismWebsite: null,
    aliases: ["Stare Miasto"],
    unescoSiteId: null,
  },
  {
    id: "tourist-schoenbrunn",
    canonicalName: "Schönbrunn Palace",
    countryCode: "AT",
    cityOrRegion: "Vienna",
    latitude: 48.1845,
    longitude: 16.3122,
    category: "park_garden",
    wikidataId: "Q46251",
    officialWebsite: "https://www.schoenbrunn.at/en/",
    tourismWebsite: null,
    aliases: ["Schönbrunn"],
    unescoSiteId: "unesco-786",
  },
  {
    id: "tourist-hofburg",
    canonicalName: "Hofburg",
    countryCode: "AT",
    cityOrRegion: "Vienna",
    latitude: 48.2066,
    longitude: 16.3655,
    category: "historic_area",
    wikidataId: "Q46213",
    officialWebsite: "https://www.hofburg-wien.at/en/",
    tourismWebsite: null,
    aliases: ["Hofburg"],
    unescoSiteId: null,
  },
  {
    id: "tourist-hallstatt",
    canonicalName: "Hallstatt",
    countryCode: "AT",
    cityOrRegion: "Salzkammergut",
    latitude: 47.5622,
    longitude: 13.6493,
    category: "natural_landscape",
    wikidataId: "Q102984",
    officialWebsite: "https://www.hallstatt.net/",
    tourismWebsite: null,
    aliases: ["Hallstatt"],
    unescoSiteId: null,
  },
  {
    id: "tourist-prague-castle",
    canonicalName: "Prague Castle",
    countryCode: "CZ",
    cityOrRegion: "Prague",
    latitude: 50.09,
    longitude: 14.4,
    category: "historic_area",
    wikidataId: "Q193369",
    officialWebsite: "https://www.hrad.cz/en",
    tourismWebsite: null,
    aliases: ["Pražský hrad"],
    unescoSiteId: "unesco-616",
  },
  {
    id: "tourist-charles-bridge",
    canonicalName: "Charles Bridge",
    countryCode: "CZ",
    cityOrRegion: "Prague",
    latitude: 50.0865,
    longitude: 14.4114,
    category: "landmark",
    wikidataId: "Q204871",
    officialWebsite: "https://www.prague.eu/en",
    tourismWebsite: null,
    aliases: ["Karlův most"],
    unescoSiteId: null,
  },
  {
    id: "tourist-cesky-krumlov",
    canonicalName: "Český Krumlov",
    countryCode: "CZ",
    cityOrRegion: "South Bohemia",
    latitude: 48.8106,
    longitude: 14.315,
    category: "historic_area",
    wikidataId: "Q188081",
    officialWebsite: "https://www.ckrumlov.info/en/",
    tourismWebsite: null,
    aliases: ["Český Krumlov"],
    unescoSiteId: null,
  },
  {
    id: "tourist-buda-castle",
    canonicalName: "Buda Castle",
    countryCode: "HU",
    cityOrRegion: "Budapest",
    latitude: 47.496,
    longitude: 19.0396,
    category: "historic_area",
    wikidataId: "Q216101",
    officialWebsite: "https://www.budapestinfo.hu/en",
    tourismWebsite: null,
    aliases: ["Budavár"],
    unescoSiteId: "unesco-400",
  },
  {
    id: "tourist-parliament-budapest",
    canonicalName: "Hungarian Parliament",
    countryCode: "HU",
    cityOrRegion: "Budapest",
    latitude: 47.5071,
    longitude: 19.0457,
    category: "landmark",
    wikidataId: "Q1183",
    officialWebsite: "https://www.parlament.hu/en/web/house-of-the-national-assembly",
    tourismWebsite: null,
    aliases: ["Országház"],
    unescoSiteId: null,
  },
  {
    id: "tourist-lake-balaton",
    canonicalName: "Lake Balaton",
    countryCode: "HU",
    cityOrRegion: "Transdanubia",
    latitude: 46.85,
    longitude: 17.75,
    category: "natural_landscape",
    wikidataId: "Q6383",
    officialWebsite: "https://www.balaton.hu/en",
    tourismWebsite: null,
    aliases: ["Balaton"],
    unescoSiteId: null,
  },
  {
    id: "tourist-dubrovnik",
    canonicalName: "Dubrovnik Old Town",
    countryCode: "HR",
    cityOrRegion: "Dubrovnik",
    latitude: 42.6507,
    longitude: 18.0944,
    category: "historic_area",
    wikidataId: "Q130963",
    officialWebsite: "https://www.visitdubrovnik.hr/",
    tourismWebsite: null,
    aliases: ["Dubrovnik"],
    unescoSiteId: "unesco-95",
  },
  {
    id: "tourist-plitvice",
    canonicalName: "Plitvice Lakes",
    countryCode: "HR",
    cityOrRegion: "Lika-Senj",
    latitude: 44.8809,
    longitude: 15.615,
    category: "natural_landscape",
    wikidataId: "Q203589",
    officialWebsite: "https://np-plitvicka-jezera.hr/en/",
    tourismWebsite: null,
    aliases: ["Plitvice"],
    unescoSiteId: "unesco-98",
  },
  {
    id: "tourist-diocletian-palace",
    canonicalName: "Diocletian's Palace",
    countryCode: "HR",
    cityOrRegion: "Split",
    latitude: 43.5081,
    longitude: 16.4402,
    category: "historic_area",
    wikidataId: "Q203885",
    officialWebsite: "https://www.visitsplit.com/",
    tourismWebsite: null,
    aliases: ["Split Palace"],
    unescoSiteId: null,
  },
  {
    id: "tourist-riga-old-town",
    canonicalName: "Riga Old Town",
    countryCode: "LV",
    cityOrRegion: "Riga",
    latitude: 56.9496,
    longitude: 24.1052,
    category: "historic_area",
    wikidataId: "Q216383",
    officialWebsite: "https://www.liveriga.com/en",
    tourismWebsite: null,
    aliases: ["Vecrīga"],
    unescoSiteId: null,
  },
  {
    id: "tourist-gauja-national-park",
    canonicalName: "Gauja National Park",
    countryCode: "LV",
    cityOrRegion: "Sigulda",
    latitude: 57.25,
    longitude: 25,
    category: "natural_landscape",
    wikidataId: "Q1495599",
    officialWebsite: "https://www.entergauja.com/",
    tourismWebsite: null,
    aliases: ["Gauja"],
    unescoSiteId: null,
  },
  {
    id: "tourist-vilnius-old-town",
    canonicalName: "Vilnius Old Town",
    countryCode: "LT",
    cityOrRegion: "Vilnius",
    latitude: 54.6872,
    longitude: 25.2797,
    category: "historic_area",
    wikidataId: "Q38988",
    officialWebsite: "https://www.govilnius.lt/visit-vilnius",
    tourismWebsite: null,
    aliases: ["Vilnius"],
    unescoSiteId: "unesco-541",
  },
  {
    id: "tourist-trakai-castle",
    canonicalName: "Trakai Island Castle",
    countryCode: "LT",
    cityOrRegion: "Trakai",
    latitude: 54.6528,
    longitude: 24.9342,
    category: "landmark",
    wikidataId: "Q1482013",
    officialWebsite: "https://www.trakai-visit.lt/en/",
    tourismWebsite: null,
    aliases: ["Trakai"],
    unescoSiteId: null,
  },
  {
    id: "tourist-tallinn-old-town",
    canonicalName: "Tallinn Old Town",
    countryCode: "EE",
    cityOrRegion: "Tallinn",
    latitude: 59.437,
    longitude: 24.7536,
    category: "historic_area",
    wikidataId: "Q726803",
    officialWebsite: "https://www.visittallinn.ee/eng",
    tourismWebsite: null,
    aliases: ["Tallinn"],
    unescoSiteId: "unesco-822",
  },
  {
    id: "tourist-lahemaa",
    canonicalName: "Lahemaa National Park",
    countryCode: "EE",
    cityOrRegion: "Harju County",
    latitude: 59.55,
    longitude: 25.75,
    category: "natural_landscape",
    wikidataId: "Q938271",
    officialWebsite: "https://loodusegakoos.ee/en/lahemaa-national-park",
    tourismWebsite: null,
    aliases: ["Lahemaa"],
    unescoSiteId: null,
  },
  {
    id: "tourist-suomenlinna",
    canonicalName: "Suomenlinna",
    countryCode: "FI",
    cityOrRegion: "Helsinki",
    latitude: 60.1477,
    longitude: 24.9885,
    category: "historic_area",
    wikidataId: "Q1291886",
    officialWebsite: "https://www.suomenlinna.fi/en/",
    tourismWebsite: null,
    aliases: ["Sveaborg"],
    unescoSiteId: null,
  },
  {
    id: "tourist-rovaniemi",
    canonicalName: "Santa Claus Village",
    countryCode: "FI",
    cityOrRegion: "Rovaniemi",
    latitude: 66.5438,
    longitude: 25.8475,
    category: "landmark",
    wikidataId: "Q7416366",
    officialWebsite: "https://santaclausvillage.info/",
    tourismWebsite: null,
    aliases: ["Rovaniemi"],
    unescoSiteId: null,
  },
  {
    id: "tourist-nyhavn",
    canonicalName: "Nyhavn",
    countryCode: "DK",
    cityOrRegion: "Copenhagen",
    latitude: 55.6794,
    longitude: 12.5911,
    category: "historic_area",
    wikidataId: "Q204218",
    officialWebsite: "https://www.visitcopenhagen.com/",
    tourismWebsite: null,
    aliases: ["Nyhavn"],
    unescoSiteId: null,
  },
  {
    id: "tourist-kronborg",
    canonicalName: "Kronborg Castle",
    countryCode: "DK",
    cityOrRegion: "Helsingør",
    latitude: 56.039,
    longitude: 12.6212,
    category: "historic_area",
    wikidataId: "Q206644",
    officialWebsite: "https://kongeligeslotte.dk/en/palaces-and-gardens/kronborg.html",
    tourismWebsite: null,
    aliases: ["Hamlet Castle"],
    unescoSiteId: null,
  },
  {
    id: "tourist-gamla-stan",
    canonicalName: "Gamla Stan",
    countryCode: "SE",
    cityOrRegion: "Stockholm",
    latitude: 59.3251,
    longitude: 18.0708,
    category: "historic_area",
    wikidataId: "Q216687",
    officialWebsite: "https://www.visitstockholm.com/",
    tourismWebsite: null,
    aliases: ["Old Town Stockholm"],
    unescoSiteId: null,
  },
  {
    id: "tourist-drottningholm",
    canonicalName: "Drottningholm Palace",
    countryCode: "SE",
    cityOrRegion: "Ekerö",
    latitude: 59.3217,
    longitude: 17.8869,
    category: "park_garden",
    wikidataId: "Q208583",
    officialWebsite: "https://www.kungligaslotten.se/english/",
    tourismWebsite: null,
    aliases: ["Drottningholm"],
    unescoSiteId: null,
  },
  {
    id: "tourist-abisko",
    canonicalName: "Abisko National Park",
    countryCode: "SE",
    cityOrRegion: "Lapland",
    latitude: 68.3492,
    longitude: 18.8311,
    category: "natural_landscape",
    wikidataId: "Q335922",
    officialWebsite: "https://www.swedishtouristassociation.com/",
    tourismWebsite: null,
    aliases: ["Abisko"],
    unescoSiteId: null,
  },
  {
    id: "tourist-valletta",
    canonicalName: "Valletta",
    countryCode: "MT",
    cityOrRegion: "Valletta",
    latitude: 35.89778,
    longitude: 14.5125,
    category: "historic_area",
    wikidataId: "Q23800",
    officialWebsite: "https://www.visitmalta.com/",
    tourismWebsite: null,
    aliases: ["Valletta"],
    unescoSiteId: "unesco-131",
  },
  {
    id: "tourist-mdina",
    canonicalName: "Mdina",
    countryCode: "MT",
    cityOrRegion: "Mdina",
    latitude: 35.8861,
    longitude: 14.4031,
    category: "historic_area",
    wikidataId: "Q207277",
    officialWebsite: "https://www.visitmalta.com/",
    tourismWebsite: null,
    aliases: ["Silent City"],
    unescoSiteId: null,
  },
  {
    id: "tourist-luxembourg-old-town",
    canonicalName: "Luxembourg Old Quarters",
    countryCode: "LU",
    cityOrRegion: "Luxembourg City",
    latitude: 49.61139,
    longitude: 6.13,
    category: "historic_area",
    wikidataId: "Q1842",
    officialWebsite: "https://www.visitluxembourg.com/en",
    tourismWebsite: null,
    aliases: ["Luxembourg City"],
    unescoSiteId: "unesco-699",
  },
  {
    id: "tourist-vianden-castle",
    canonicalName: "Vianden Castle",
    countryCode: "LU",
    cityOrRegion: "Vianden",
    latitude: 49.9347,
    longitude: 6.2075,
    category: "landmark",
    wikidataId: "Q1519611",
    officialWebsite: "https://www.castle-vianden.lu/en/",
    tourismWebsite: null,
    aliases: ["Vianden"],
    unescoSiteId: null,
  },
  {
    id: "tourist-bratislava-castle",
    canonicalName: "Bratislava Castle",
    countryCode: "SK",
    cityOrRegion: "Bratislava",
    latitude: 48.142,
    longitude: 17.1001,
    category: "landmark",
    wikidataId: "Q217414",
    officialWebsite: "https://www.bratislava-hrad.sk/",
    tourismWebsite: null,
    aliases: ["Bratislavský hrad"],
    unescoSiteId: null,
  },
  {
    id: "tourist-spis-castle",
    canonicalName: "Spiš Castle",
    countryCode: "SK",
    cityOrRegion: "Spiš",
    latitude: 49.0005,
    longitude: 20.7683,
    category: "historic_area",
    wikidataId: "Q845039",
    officialWebsite: "https://www.spisskyhrad.sk/",
    tourismWebsite: null,
    aliases: ["Spišský hrad"],
    unescoSiteId: null,
  },
  {
    id: "tourist-lake-bled",
    canonicalName: "Lake Bled",
    countryCode: "SI",
    cityOrRegion: "Bled",
    latitude: 46.3636,
    longitude: 14.0945,
    category: "natural_landscape",
    wikidataId: "Q648902",
    officialWebsite: "https://www.bled.si/en/",
    tourismWebsite: null,
    aliases: ["Bled"],
    unescoSiteId: null,
  },
  {
    id: "tourist-ljubljana-castle",
    canonicalName: "Ljubljana Castle",
    countryCode: "SI",
    cityOrRegion: "Ljubljana",
    latitude: 46.0489,
    longitude: 14.5083,
    category: "landmark",
    wikidataId: "Q1269297",
    officialWebsite: "https://www.ljubljanskigrad.si/en/",
    tourismWebsite: null,
    aliases: ["Ljubljanski grad"],
    unescoSiteId: null,
  },
  {
    id: "tourist-postojna-cave",
    canonicalName: "Postojna Cave",
    countryCode: "SI",
    cityOrRegion: "Postojna",
    latitude: 45.7817,
    longitude: 14.2039,
    category: "natural_landscape",
    wikidataId: "Q15903",
    officialWebsite: "https://www.postojnska-jama.eu/en/",
    tourismWebsite: null,
    aliases: ["Postojna"],
    unescoSiteId: null,
  },
  {
    id: "tourist-bran-castle",
    canonicalName: "Bran Castle",
    countryCode: "RO",
    cityOrRegion: "Brașov",
    latitude: 45.5151,
    longitude: 25.3672,
    category: "landmark",
    wikidataId: "Q843776",
    officialWebsite: "https://www.bran-castle.com/",
    tourismWebsite: null,
    aliases: ["Dracula Castle"],
    unescoSiteId: null,
  },
  {
    id: "tourist-transfagarasan",
    canonicalName: "Transfăgărășan",
    countryCode: "RO",
    cityOrRegion: "Carpathians",
    latitude: 45.5986,
    longitude: 24.6167,
    category: "mountain_destination",
    wikidataId: "Q934803",
    officialWebsite: "https://www.romania.travel/",
    tourismWebsite: null,
    aliases: ["Transfăgărășan"],
    unescoSiteId: null,
  },
  {
    id: "tourist-painted-monasteries",
    canonicalName: "Painted Monasteries of Bucovina",
    countryCode: "RO",
    cityOrRegion: "Suceava",
    latitude: 47.7833,
    longitude: 26.2667,
    category: "historic_area",
    wikidataId: "Q209010",
    officialWebsite: "https://www.romania.travel/",
    tourismWebsite: null,
    aliases: ["Bucovina Monasteries"],
    unescoSiteId: null,
  },
  {
    id: "tourist-alexander-nevsky",
    canonicalName: "Alexander Nevsky Cathedral",
    countryCode: "BG",
    cityOrRegion: "Sofia",
    latitude: 42.6958,
    longitude: 23.3328,
    category: "landmark",
    wikidataId: "Q43282",
    officialWebsite: "https://www.visitsofia.bg/en/",
    tourismWebsite: null,
    aliases: ["Alexander Nevsky"],
    unescoSiteId: null,
  },
  {
    id: "tourist-rila-monastery",
    canonicalName: "Rila Monastery",
    countryCode: "BG",
    cityOrRegion: "Rila",
    latitude: 42.1339,
    longitude: 23.3405,
    category: "historic_area",
    wikidataId: "Q64617589",
    officialWebsite: "https://www.rilamonastery.pmg-blg.com/",
    tourismWebsite: null,
    aliases: ["Rila"],
    unescoSiteId: null,
  },
  {
    id: "tourist-troodos",
    canonicalName: "Troodos Mountains",
    countryCode: "CY",
    cityOrRegion: "Troodos",
    latitude: 34.9167,
    longitude: 32.85,
    category: "mountain_destination",
    wikidataId: "Q466628",
    officialWebsite: "https://www.visitcyprus.com/",
    tourismWebsite: null,
    aliases: ["Troodos"],
    unescoSiteId: null,
  },
  {
    id: "tourist-paphos",
    canonicalName: "Paphos Archaeological Park",
    countryCode: "CY",
    cityOrRegion: "Paphos",
    latitude: 34.7556,
    longitude: 32.4083,
    category: "historic_area",
    wikidataId: "Q212873",
    officialWebsite: "https://www.visitcyprus.com/",
    tourismWebsite: null,
    aliases: ["Paphos"],
    unescoSiteId: null,
  },
  {
    id: "tourist-blue-lagoon",
    canonicalName: "Blue Lagoon",
    countryCode: "IS",
    cityOrRegion: "Grindavík",
    latitude: 63.8804,
    longitude: -22.4495,
    category: "natural_landscape",
    wikidataId: "Q886946",
    officialWebsite: "https://www.bluelagoon.com/",
    tourismWebsite: null,
    aliases: ["Blue Lagoon"],
    unescoSiteId: null,
  },
  {
    id: "tourist-golden-circle",
    canonicalName: "Golden Circle",
    countryCode: "IS",
    cityOrRegion: "South Iceland",
    latitude: 64.2558,
    longitude: -21.1299,
    category: "natural_landscape",
    wikidataId: "Q1495724",
    officialWebsite: "https://www.visiticeland.com/",
    tourismWebsite: null,
    aliases: ["Golden Circle"],
    unescoSiteId: null,
  },
  {
    id: "tourist-vaduz-castle",
    canonicalName: "Vaduz Castle",
    countryCode: "LI",
    cityOrRegion: "Vaduz",
    latitude: 47.1396,
    longitude: 9.5245,
    category: "landmark",
    wikidataId: "Q694782",
    officialWebsite: "https://www.tourismus.li/en/",
    tourismWebsite: null,
    aliases: ["Vaduz Castle"],
    unescoSiteId: null,
  },
  {
    id: "tourist-malbun",
    canonicalName: "Malbun",
    countryCode: "LI",
    cityOrRegion: "Triesenberg",
    latitude: 47.1028,
    longitude: 9.6097,
    category: "mountain_destination",
    wikidataId: "Q1880843",
    officialWebsite: "https://www.tourismus.li/en/",
    tourismWebsite: null,
    aliases: ["Malbun"],
    unescoSiteId: null,
  },
  {
    id: "tourist-hagia-sophia",
    canonicalName: "Hagia Sophia",
    countryCode: "TR",
    cityOrRegion: "Istanbul",
    latitude: 41.00833,
    longitude: 28.98,
    category: "landmark",
    wikidataId: "Q12506",
    officialWebsite: "https://muze.gen.tr/",
    tourismWebsite: null,
    aliases: ["Ayasofya"],
    unescoSiteId: "unesco-356",
  },
  {
    id: "tourist-topkapi",
    canonicalName: "Topkapi Palace",
    countryCode: "TR",
    cityOrRegion: "Istanbul",
    latitude: 41.0115,
    longitude: 28.9833,
    category: "historic_area",
    wikidataId: "Q170684",
    officialWebsite: "https://muze.gen.tr/",
    tourismWebsite: null,
    aliases: ["Topkapı"],
    unescoSiteId: "unesco-356",
  },
  {
    id: "tourist-blue-mosque",
    canonicalName: "Blue Mosque",
    countryCode: "TR",
    cityOrRegion: "Istanbul",
    latitude: 41.0054,
    longitude: 28.9768,
    category: "landmark",
    wikidataId: "Q43269",
    officialWebsite: "https://www.turkeytourism.com/",
    tourismWebsite: null,
    aliases: ["Sultan Ahmed Mosque"],
    unescoSiteId: null,
  },
  {
    id: "tourist-lviv-old-town",
    canonicalName: "Lviv Old Town",
    countryCode: "UA",
    cityOrRegion: "Lviv",
    latitude: 49.8419,
    longitude: 24.0315,
    category: "historic_area",
    wikidataId: "Q156732",
    officialWebsite: "https://lviv.travel/en",
    tourismWebsite: null,
    aliases: ["Lviv"],
    unescoSiteId: null,
  },
  {
    id: "tourist-kyiv-lavra",
    canonicalName: "Kyiv Pechersk Lavra",
    countryCode: "UA",
    cityOrRegion: "Kyiv",
    latitude: 50.4347,
    longitude: 30.5586,
    category: "historic_area",
    wikidataId: "Q203065",
    officialWebsite: "https://www.kplavra.kiev.ua/",
    tourismWebsite: null,
    aliases: ["Pechersk Lavra"],
    unescoSiteId: null,
  },
  {
    id: "tourist-belgrade-fortress",
    canonicalName: "Belgrade Fortress",
    countryCode: "RS",
    cityOrRegion: "Belgrade",
    latitude: 44.8236,
    longitude: 20.4505,
    category: "historic_area",
    wikidataId: "Q477677",
    officialWebsite: "https://www.tob.rs/en",
    tourismWebsite: null,
    aliases: ["Kalemegdan"],
    unescoSiteId: null,
  },
  {
    id: "tourist-studenica",
    canonicalName: "Studenica Monastery",
    countryCode: "RS",
    cityOrRegion: "Kraljevo",
    latitude: 43.2739,
    longitude: 20.5367,
    category: "historic_area",
    wikidataId: "Q1269298",
    officialWebsite: "https://www.serbia.travel/",
    tourismWebsite: null,
    aliases: ["Studenica"],
    unescoSiteId: null,
  },
  {
    id: "tourist-stari-most",
    canonicalName: "Stari Most",
    countryCode: "BA",
    cityOrRegion: "Mostar",
    latitude: 43.3373,
    longitude: 17.815,
    category: "landmark",
    wikidataId: "Q188528",
    officialWebsite: "https://www.turizam.ba/",
    tourismWebsite: null,
    aliases: ["Mostar Bridge"],
    unescoSiteId: null,
  },
  {
    id: "tourist-sarajevo-bascarsija",
    canonicalName: "Sarajevo Baščaršija",
    countryCode: "BA",
    cityOrRegion: "Sarajevo",
    latitude: 43.8594,
    longitude: 18.4314,
    category: "historic_area",
    wikidataId: "Q125823",
    officialWebsite: "https://www.sarajevo.travel/",
    tourismWebsite: null,
    aliases: ["Baščaršija"],
    unescoSiteId: null,
  },
  {
    id: "tourist-berat",
    canonicalName: "Berat",
    countryCode: "AL",
    cityOrRegion: "Berat",
    latitude: 40.70494,
    longitude: 19.94967,
    category: "historic_area",
    wikidataId: "Q170244",
    officialWebsite: "https://albania.al/",
    tourismWebsite: null,
    aliases: ["Berat"],
    unescoSiteId: null,
  },
  {
    id: "tourist-butrint",
    canonicalName: "Butrint",
    countryCode: "AL",
    cityOrRegion: "Sarandë",
    latitude: 39.7453,
    longitude: 20.0206,
    category: "historic_area",
    wikidataId: "Q188694",
    officialWebsite: "https://butrint.org/",
    tourismWebsite: null,
    aliases: ["Butrint"],
    unescoSiteId: null,
  },
  {
    id: "tourist-lake-ohrid",
    canonicalName: "Lake Ohrid",
    countryCode: "MK",
    cityOrRegion: "Ohrid",
    latitude: 41.1217,
    longitude: 20.8014,
    category: "natural_landscape",
    wikidataId: "Q156258",
    officialWebsite: "https://macedonia-timeless.com/",
    tourismWebsite: null,
    aliases: ["Ohrid"],
    unescoSiteId: null,
  },
  {
    id: "tourist-skopje",
    canonicalName: "Skopje Old Bazaar",
    countryCode: "MK",
    cityOrRegion: "Skopje",
    latitude: 41.9965,
    longitude: 21.4314,
    category: "historic_area",
    wikidataId: "Q384",
    officialWebsite: "https://www.exploringmacedonia.com/",
    tourismWebsite: null,
    aliases: ["Skopje"],
    unescoSiteId: null,
  },
  {
    id: "tourist-bay-of-kotor",
    canonicalName: "Bay of Kotor",
    countryCode: "ME",
    cityOrRegion: "Kotor",
    latitude: 42.4247,
    longitude: 18.7712,
    category: "coastal_destination",
    wikidataId: "Q216520",
    officialWebsite: "https://www.montenegro.travel/",
    tourismWebsite: null,
    aliases: ["Boka Kotorska"],
    unescoSiteId: null,
  },
  {
    id: "tourist-durmitor",
    canonicalName: "Durmitor National Park",
    countryCode: "ME",
    cityOrRegion: "Žabljak",
    latitude: 43.1333,
    longitude: 19.0167,
    category: "mountain_destination",
    wikidataId: "Q386854",
    officialWebsite: "https://www.montenegro.travel/",
    tourismWebsite: null,
    aliases: ["Durmitor"],
    unescoSiteId: null,
  },
  {
    id: "tourist-mtskheta",
    canonicalName: "Mtskheta",
    countryCode: "GE",
    cityOrRegion: "Mtskheta",
    latitude: 41.8456,
    longitude: 44.7181,
    category: "historic_area",
    wikidataId: "Q172415",
    officialWebsite: "https://georgia.travel/",
    tourismWebsite: null,
    aliases: ["Mtskheta"],
    unescoSiteId: null,
  },
  {
    id: "tourist-tbilisi-old-town",
    canonicalName: "Tbilisi Old Town",
    countryCode: "GE",
    cityOrRegion: "Tbilisi",
    latitude: 41.6938,
    longitude: 44.8015,
    category: "historic_area",
    wikidataId: "Q994",
    officialWebsite: "https://georgia.travel/",
    tourismWebsite: null,
    aliases: ["Tbilisi"],
    unescoSiteId: null,
  },
  {
    id: "tourist-orheiul-vechi",
    canonicalName: "Orheiul Vechi",
    countryCode: "MD",
    cityOrRegion: "Orhei",
    latitude: 47.3056,
    longitude: 28.9786,
    category: "historic_area",
    wikidataId: "Q2035904",
    officialWebsite: "https://moldova.travel/",
    tourismWebsite: null,
    aliases: ["Orheiul Vechi"],
    unescoSiteId: null,
  },
  {
    id: "tourist-cricova",
    canonicalName: "Cricova Winery",
    countryCode: "MD",
    cityOrRegion: "Cricova",
    latitude: 47.1389,
    longitude: 28.8611,
    category: "landmark",
    wikidataId: "Q1137434",
    officialWebsite: "https://moldova.travel/",
    tourismWebsite: null,
    aliases: ["Cricova"],
    unescoSiteId: null,
  },
  {
    id: "tourist-prizren",
    canonicalName: "Prizren",
    countryCode: "XK",
    cityOrRegion: "Prizren",
    latitude: 42.2139,
    longitude: 20.7397,
    category: "historic_area",
    wikidataId: "Q200061",
    officialWebsite: null,
    tourismWebsite: null,
    aliases: ["Prizren"],
    unescoSiteId: null,
  },
  {
    id: "tourist-gracanica",
    canonicalName: "Gračanica Monastery",
    countryCode: "XK",
    cityOrRegion: "Gračanica",
    latitude: 42.6011,
    longitude: 21.1944,
    category: "historic_area",
    wikidataId: "Q1544186",
    officialWebsite: null,
    tourismWebsite: null,
    aliases: ["Gračanica"],
    unescoSiteId: null,
  }];

export function getMajorTouristPlaceById(
  id: string,
): MajorTouristPlace | undefined {
  return MAJOR_TOURIST_PLACES.find((place) => place.id === id);
}

export function getMajorTouristPlacesByCategory(
  category: TouristPlaceCategory,
): MajorTouristPlace[] {
  return MAJOR_TOURIST_PLACES.filter((place) => place.category === category);
}

export function validateMajorTouristPlaces(): {
  ok: boolean;
  errors: string[];
  total: number;
  byCategory: Record<TouristPlaceCategory, number>;
  byCountry: Record<string, number>;
  countriesWithoutPlace: string[];
  anomalies: string[];
} {
  const errors: string[] = [];
  const anomalies: string[] = [];
  const ids = new Set<string>();
  const wikidataIds = new Set<string>();
  const coords = new Set<string>();
  const byCategory = Object.fromEntries(
    CATEGORIES.map((c) => [c, 0]),
  ) as Record<TouristPlaceCategory, number>;
  const byCountry: Record<string, number> = {};

  for (const place of MAJOR_TOURIST_PLACES) {
    if (!place.id.startsWith("tourist-")) {
      errors.push(`invalid id prefix: ${place.id}`);
    }
    if (ids.has(place.id)) errors.push(`duplicate id: ${place.id}`);
    ids.add(place.id);
    if (wikidataIds.has(place.wikidataId)) {
      errors.push(`duplicate wikidataId: ${place.wikidataId}`);
    }
    wikidataIds.add(place.wikidataId);
    if (!CATEGORIES.includes(place.category)) {
      errors.push(`invalid category for ${place.id}`);
    } else {
      byCategory[place.category] += 1;
    }
    if (!isAllowedUnescoMapCountry(place.countryCode)) {
      errors.push(`country not allowed: ${place.countryCode} (${place.id})`);
    }
    byCountry[place.countryCode] = (byCountry[place.countryCode] ?? 0) + 1;
    if (!place.canonicalName.trim() || !place.cityOrRegion.trim()) {
      errors.push(`empty name/city for ${place.id}`);
    }
    if (
      place.longitude < UNESCO_EUROPE_MAP_BOUNDS.minLongitude ||
      place.longitude > UNESCO_EUROPE_MAP_BOUNDS.maxLongitude ||
      place.latitude < UNESCO_EUROPE_MAP_BOUNDS.minLatitude ||
      place.latitude > UNESCO_EUROPE_MAP_BOUNDS.maxLatitude
    ) {
      errors.push(`coords out of bounds: ${place.id}`);
    }
    if (
      place.countryCode === "TR" &&
      (place.longitude > 29.2 || place.latitude < 40.5)
    ) {
      errors.push(`Turkish place outside European Thrace: ${place.id}`);
    }
    for (const url of [place.officialWebsite, place.tourismWebsite]) {
      if (url && !url.startsWith("https://")) {
        errors.push(`non-https url for ${place.id}`);
      }
    }
    if (place.unescoSiteId && !getUnescoSiteById(place.unescoSiteId)) {
      errors.push(`unknown unescoSiteId ${place.unescoSiteId} for ${place.id}`);
    }
    const key = `${place.latitude.toFixed(5)},${place.longitude.toFixed(5)}`;
    if (coords.has(key)) errors.push(`duplicate coords: ${place.id}`);
    coords.add(key);
  }

  const countriesWithoutPlace = UNESCO_MAP_COUNTRY_CODES.filter(
    (code) => !(byCountry[code] > 0),
  );
  if (countriesWithoutPlace.length > 0) {
    anomalies.push(
      `countries without place: ${countriesWithoutPlace.join(", ")}`,
    );
  }

  const total = MAJOR_TOURIST_PLACES.length;
  if (total < 120 || total > 145) {
    anomalies.push(`total ${total} outside preferred 120-145 range`);
  }

  return {
    ok: errors.length === 0,
    errors,
    total,
    byCategory,
    byCountry,
    countriesWithoutPlace: [...countriesWithoutPlace],
    anomalies,
  };
}

if (process.env.NODE_ENV !== "production") {
  const validation = validateMajorTouristPlaces();
  if (!validation.ok) {
    console.error("[majorTouristPlaces]", validation.errors.join("; "));
  }
}
