/**
 * Dún Laoghaire-Rathdown County Council WiFi4EU access points (CC-BY).
 * Source: https://data.gov.ie/dataset/wifi4eu-access-points-dlr
 * Generated from official GeoJSON — 49 deduplicated records.
 */

import type { Wifi4EuRecord } from "./types";
import { makeHotspotRecord } from "./providers/types";
import { DATA_LAYER_SOURCE_IDS } from "@/lib/map/dataLayers/sourceIds";

const SOURCE_IDS = [DATA_LAYER_SOURCE_IDS.WIFI4EU_MUNICIPAL_OPEN_DATA];

export const WIFI4EU_DLR_HOTSPOTS: readonly Wifi4EuRecord[] = [
  makeHotspotRecord({
    id: "wifi4eu-dlr-blackrock-park-out",
    name: "Blackrock Park",
    municipality: "Dún Laoghaire-Rathdown",
    countryCode: "IE",
    longitude: -6.184878000417738,
    latitude: 53.30424999999531,
    sourceType: "municipal_official",
    sourceIds: SOURCE_IDS,
    address: null,
    indoorOutdoor: "outdoor",
    locationType: "Voucher A",
  }),
  makeHotspotRecord({
    id: "wifi4eu-dlr-dalkey-library-out",
    name: "Dalkey Library",
    municipality: "Dún Laoghaire-Rathdown",
    countryCode: "IE",
    longitude: -6.104495999901312,
    latitude: 53.27744299965025,
    sourceType: "municipal_official",
    sourceIds: SOURCE_IDS,
    address: null,
    indoorOutdoor: "outdoor",
    locationType: "Voucher A",
  }),
  makeHotspotRecord({
    id: "wifi4eu-dlr-dlr-baths-caf-out",
    name: "DLR Baths Café",
    municipality: "Dún Laoghaire-Rathdown",
    countryCode: "IE",
    longitude: -6.127965000503297,
    latitude: 53.291018999855766,
    sourceType: "municipal_official",
    sourceIds: SOURCE_IDS,
    address: null,
    indoorOutdoor: "outdoor",
    locationType: "Voucher A",
  }),
  makeHotspotRecord({
    id: "wifi4eu-dlr-dlr-baths-lobby-out",
    name: "DLR BATHS Lobby",
    municipality: "Dún Laoghaire-Rathdown",
    countryCode: "IE",
    longitude: -6.12780500071918,
    latitude: 53.2910339997285,
    sourceType: "municipal_official",
    sourceIds: SOURCE_IDS,
    address: null,
    indoorOutdoor: "outdoor",
    locationType: "Voucher A",
  }),
  makeHotspotRecord({
    id: "wifi4eu-dlr-dlr-baths-outdoor-out",
    name: "DLR Baths Outdoor",
    municipality: "Dún Laoghaire-Rathdown",
    countryCode: "IE",
    longitude: -6.128007000292994,
    latitude: 53.291076999715635,
    sourceType: "municipal_official",
    sourceIds: SOURCE_IDS,
    address: null,
    indoorOutdoor: "outdoor",
    locationType: "Voucher A",
  }),
  makeHotspotRecord({
    id: "wifi4eu-dlr-dlr-dock-tower-out",
    name: "DLR Dock Tower",
    municipality: "Dún Laoghaire-Rathdown",
    countryCode: "IE",
    longitude: -6.133232000531281,
    latitude: 53.29694199993864,
    sourceType: "municipal_official",
    sourceIds: SOURCE_IDS,
    address: null,
    indoorOutdoor: "outdoor",
    locationType: "Voucher A",
  }),
  makeHotspotRecord({
    id: "wifi4eu-dlr-dlr-pier-out",
    name: "DLR Pier",
    municipality: "Dún Laoghaire-Rathdown",
    countryCode: "IE",
    longitude: -6.132620000164406,
    latitude: 53.29593999961111,
    sourceType: "municipal_official",
    sourceIds: SOURCE_IDS,
    address: null,
    indoorOutdoor: "outdoor",
    locationType: "Voucher A",
  }),
  makeHotspotRecord({
    id: "wifi4eu-dlr-dlr-plaza-out",
    name: "DLR Plaza",
    municipality: "Dún Laoghaire-Rathdown",
    countryCode: "IE",
    longitude: -6.1339410005851045,
    latitude: 53.29547500012689,
    sourceType: "municipal_official",
    sourceIds: SOURCE_IDS,
    address: null,
    indoorOutdoor: "outdoor",
    locationType: "Voucher A",
  }),
  makeHotspotRecord({
    id: "wifi4eu-dlr-killiney-beach-lifeguard-hut-out",
    name: "Killiney beach, Lifeguard Hut",
    municipality: "Dún Laoghaire-Rathdown",
    countryCode: "IE",
    longitude: -6.112484000449956,
    latitude: 53.25791199979879,
    sourceType: "municipal_official",
    sourceIds: SOURCE_IDS,
    address: null,
    indoorOutdoor: "outdoor",
    locationType: "Voucher A",
  }),
  makeHotspotRecord({
    id: "wifi4eu-dlr-killiney-hill-caf-out",
    name: "Killiney Hill  Café",
    municipality: "Dún Laoghaire-Rathdown",
    countryCode: "IE",
    longitude: -6.114806000667022,
    latitude: 53.26661699977524,
    sourceType: "municipal_official",
    sourceIds: SOURCE_IDS,
    address: null,
    indoorOutdoor: "outdoor",
    locationType: "Voucher A",
  }),
  makeHotspotRecord({
    id: "wifi4eu-dlr-peoples-park-near-caf-out",
    name: "Peoples Park, near Café",
    municipality: "Dún Laoghaire-Rathdown",
    countryCode: "IE",
    longitude: -6.129349999252652,
    latitude: 53.28966700036608,
    sourceType: "municipal_official",
    sourceIds: SOURCE_IDS,
    address: null,
    indoorOutdoor: "outdoor",
    locationType: "Voucher A",
  }),
  makeHotspotRecord({
    id: "wifi4eu-dlr-sallynoggin-community-ctr-ind",
    name: "Sallynoggin Community Ctr",
    municipality: "Dún Laoghaire-Rathdown",
    countryCode: "IE",
    longitude: -6.1370679996429,
    latitude: 53.27463299995639,
    sourceType: "municipal_official",
    sourceIds: SOURCE_IDS,
    address: null,
    indoorOutdoor: "indoor",
    locationType: "Voucher A",
  }),
  makeHotspotRecord({
    id: "wifi4eu-dlr-sandycove-the-battery-out",
    name: "Sandycove, The Battery",
    municipality: "Dún Laoghaire-Rathdown",
    countryCode: "IE",
    longitude: -6.114244000563414,
    latitude: 53.28909899990589,
    sourceType: "municipal_official",
    sourceIds: SOURCE_IDS,
    address: null,
    indoorOutdoor: "outdoor",
    locationType: "Voucher A",
  }),
  makeHotspotRecord({
    id: "wifi4eu-dlr-seapoint-out",
    name: "Seapoint",
    municipality: "Dún Laoghaire-Rathdown",
    countryCode: "IE",
    longitude: -6.159872000329901,
    latitude: 53.297675000357664,
    sourceType: "municipal_official",
    sourceIds: SOURCE_IDS,
    address: null,
    indoorOutdoor: "outdoor",
    locationType: "Voucher A",
  }),
  makeHotspotRecord({
    id: "wifi4eu-dlr-ballyogan-parish-hall-ind",
    name: "Ballyogan Parish Hall",
    municipality: "Dún Laoghaire-Rathdown",
    countryCode: "IE",
    longitude: -6.1891460001263034,
    latitude: 53.25717799993912,
    sourceType: "municipal_official",
    sourceIds: SOURCE_IDS,
    address: null,
    indoorOutdoor: "indoor",
    locationType: "Voucher B",
  }),
  makeHotspotRecord({
    id: "wifi4eu-dlr-deerpark-tenis-club-ind",
    name: "Deerpark, Tenis Club",
    municipality: "Dún Laoghaire-Rathdown",
    countryCode: "IE",
    longitude: -6.215574000469132,
    latitude: 53.294787999918675,
    sourceType: "municipal_official",
    sourceIds: SOURCE_IDS,
    address: null,
    indoorOutdoor: "indoor",
    locationType: "Voucher B",
  }),
  makeHotspotRecord({
    id: "wifi4eu-dlr-deerpark-tenis-club-out",
    name: "Deerpark, Tenis Club",
    municipality: "Dún Laoghaire-Rathdown",
    countryCode: "IE",
    longitude: -6.215574000469132,
    latitude: 53.294787999918675,
    sourceType: "municipal_official",
    sourceIds: SOURCE_IDS,
    address: null,
    indoorOutdoor: "outdoor",
    locationType: "Voucher B",
  }),
  makeHotspotRecord({
    id: "wifi4eu-dlr-fernhill-gardens-out",
    name: "Fernhill Gardens",
    municipality: "Dún Laoghaire-Rathdown",
    countryCode: "IE",
    longitude: -6.224921000667186,
    latitude: 53.25744900021575,
    sourceType: "municipal_official",
    sourceIds: SOURCE_IDS,
    address: null,
    indoorOutdoor: "outdoor",
    locationType: "Voucher B",
  }),
  makeHotspotRecord({
    id: "wifi4eu-dlr-glencullen-community-ctr-ind",
    name: "Glencullen Community Ctr.",
    municipality: "Dún Laoghaire-Rathdown",
    countryCode: "IE",
    longitude: -6.215428999873119,
    latitude: 53.22301999974316,
    sourceType: "municipal_official",
    sourceIds: SOURCE_IDS,
    address: null,
    indoorOutdoor: "indoor",
    locationType: "Voucher B",
  }),
  makeHotspotRecord({
    id: "wifi4eu-dlr-kirwan-park-delasalle-ind",
    name: "Kirwan park, DeLaSalle",
    municipality: "Dún Laoghaire-Rathdown",
    countryCode: "IE",
    longitude: -6.199021999829488,
    latitude: 53.24587799992238,
    sourceType: "municipal_official",
    sourceIds: SOURCE_IDS,
    address: null,
    indoorOutdoor: "indoor",
    locationType: "Voucher B",
  }),
  makeHotspotRecord({
    id: "wifi4eu-dlr-kirwan-park-delasalle-out",
    name: "Kirwan park, DeLaSalle",
    municipality: "Dún Laoghaire-Rathdown",
    countryCode: "IE",
    longitude: -6.199021999829488,
    latitude: 53.24587799992238,
    sourceType: "municipal_official",
    sourceIds: SOURCE_IDS,
    address: null,
    indoorOutdoor: "outdoor",
    locationType: "Voucher B",
  }),
  makeHotspotRecord({
    id: "wifi4eu-dlr-patrician-villas-community-ctr-out",
    name: "Patrician Villas Community Ctr",
    municipality: "Dún Laoghaire-Rathdown",
    countryCode: "IE",
    longitude: -6.194622999270978,
    latitude: 53.29012699986777,
    sourceType: "municipal_official",
    sourceIds: SOURCE_IDS,
    address: null,
    indoorOutdoor: "outdoor",
    locationType: "Voucher B",
  }),
  makeHotspotRecord({
    id: "wifi4eu-dlr-rochestown-house-community-ctr-ind",
    name: "Rochestown House Community Ctr",
    municipality: "Dún Laoghaire-Rathdown",
    countryCode: "IE",
    longitude: -6.145670999932498,
    latitude: 53.274272000036675,
    sourceType: "municipal_official",
    sourceIds: SOURCE_IDS,
    address: null,
    indoorOutdoor: "indoor",
    locationType: "Voucher B",
  }),
  makeHotspotRecord({
    id: "wifi4eu-dlr-sandyford-village-nectar-ind",
    name: "Sandyford Village, Nectar",
    municipality: "Dún Laoghaire-Rathdown",
    countryCode: "IE",
    longitude: -6.224784000154828,
    latitude: 53.27000099969994,
    sourceType: "municipal_official",
    sourceIds: SOURCE_IDS,
    address: null,
    indoorOutdoor: "indoor",
    locationType: "Voucher B",
  }),
  makeHotspotRecord({
    id: "wifi4eu-dlr-sandyford-village-nectar-out",
    name: "Sandyford Village, Nectar",
    municipality: "Dún Laoghaire-Rathdown",
    countryCode: "IE",
    longitude: -6.224784000154828,
    latitude: 53.27000099969994,
    sourceType: "municipal_official",
    sourceIds: SOURCE_IDS,
    address: null,
    indoorOutdoor: "outdoor",
    locationType: "Voucher B",
  }),
  makeHotspotRecord({
    id: "wifi4eu-dlr-stepaside-all-weather-pitches-out",
    name: "Stepaside All Weather pitches",
    municipality: "Dún Laoghaire-Rathdown",
    countryCode: "IE",
    longitude: -6.201417000735888,
    latitude: 53.2476560000691,
    sourceType: "municipal_official",
    sourceIds: SOURCE_IDS,
    address: null,
    indoorOutdoor: "outdoor",
    locationType: "Voucher B",
  }),
  makeHotspotRecord({
    id: "wifi4eu-dlr-stepaside-public-golf-course-out",
    name: "Stepaside Public Golf Course",
    municipality: "Dún Laoghaire-Rathdown",
    countryCode: "IE",
    longitude: -6.202570999877863,
    latitude: 53.248780999730094,
    sourceType: "municipal_official",
    sourceIds: SOURCE_IDS,
    address: null,
    indoorOutdoor: "outdoor",
    locationType: "Voucher B",
  }),
  makeHotspotRecord({
    id: "wifi4eu-dlr-ballybrack-project-centre-ind",
    name: "Ballybrack Project Centre",
    municipality: "Dún Laoghaire-Rathdown",
    countryCode: "IE",
    longitude: -6.136042000647135,
    latitude: 53.25425699997827,
    sourceType: "municipal_official",
    sourceIds: SOURCE_IDS,
    address: null,
    indoorOutdoor: "indoor",
    locationType: "Voucher C",
  }),
  makeHotspotRecord({
    id: "wifi4eu-dlr-cabinteely-fc-kilbogget-ind",
    name: "Cabinteely FC, Kilbogget",
    municipality: "Dún Laoghaire-Rathdown",
    countryCode: "IE",
    longitude: -6.138596000272957,
    latitude: 53.259077000426224,
    sourceType: "municipal_official",
    sourceIds: SOURCE_IDS,
    address: null,
    indoorOutdoor: "indoor",
    locationType: "Voucher C",
  }),
  makeHotspotRecord({
    id: "wifi4eu-dlr-cabinteely-fc-kilbogget-out",
    name: "Cabinteely FC, Kilbogget",
    municipality: "Dún Laoghaire-Rathdown",
    countryCode: "IE",
    longitude: -6.138596000272957,
    latitude: 53.259077000426224,
    sourceType: "municipal_official",
    sourceIds: SOURCE_IDS,
    address: null,
    indoorOutdoor: "outdoor",
    locationType: "Voucher C",
  }),
  makeHotspotRecord({
    id: "wifi4eu-dlr-cabinteely-grainstore-out",
    name: "Cabinteely Grainstore",
    municipality: "Dún Laoghaire-Rathdown",
    countryCode: "IE",
    longitude: -6.161374000426887,
    latitude: 53.260245999773886,
    sourceType: "municipal_official",
    sourceIds: SOURCE_IDS,
    address: null,
    indoorOutdoor: "outdoor",
    locationType: "Voucher C",
  }),
  makeHotspotRecord({
    id: "wifi4eu-dlr-cabinteely-park-playground-out",
    name: "Cabinteely Park Playground",
    municipality: "Dún Laoghaire-Rathdown",
    countryCode: "IE",
    longitude: -6.1582070004743334,
    latitude: 53.2614070000231,
    sourceType: "municipal_official",
    sourceIds: SOURCE_IDS,
    address: null,
    indoorOutdoor: "outdoor",
    locationType: "Voucher C",
  }),
  makeHotspotRecord({
    id: "wifi4eu-dlr-cois-cairn-community-centre-ind",
    name: "Cois Cairn Community Centre",
    municipality: "Dún Laoghaire-Rathdown",
    countryCode: "IE",
    longitude: -6.12149900038512,
    latitude: 53.21143199973014,
    sourceType: "municipal_official",
    sourceIds: SOURCE_IDS,
    address: null,
    indoorOutdoor: "indoor",
    locationType: "Voucher C",
  }),
  makeHotspotRecord({
    id: "wifi4eu-dlr-furry-hill-ind",
    name: "Furry Hill",
    municipality: "Dún Laoghaire-Rathdown",
    countryCode: "IE",
    longitude: -6.2297660003024244,
    latitude: 53.27846200011906,
    sourceType: "municipal_official",
    sourceIds: SOURCE_IDS,
    address: null,
    indoorOutdoor: "indoor",
    locationType: "Voucher C",
  }),
  makeHotspotRecord({
    id: "wifi4eu-dlr-loughlinstown-community-rooms-ind",
    name: "Loughlinstown Community Rooms",
    municipality: "Dún Laoghaire-Rathdown",
    countryCode: "IE",
    longitude: -6.129893999448701,
    latitude: 53.24700299998693,
    sourceType: "municipal_official",
    sourceIds: SOURCE_IDS,
    address: null,
    indoorOutdoor: "indoor",
    locationType: "Voucher C",
  }),
  makeHotspotRecord({
    id: "wifi4eu-dlr-loughlinstown-community-rooms-out",
    name: "Loughlinstown Community Rooms",
    municipality: "Dún Laoghaire-Rathdown",
    countryCode: "IE",
    longitude: -6.129893999448701,
    latitude: 53.24700299998693,
    sourceType: "municipal_official",
    sourceIds: SOURCE_IDS,
    address: null,
    indoorOutdoor: "outdoor",
    locationType: "Voucher C",
  }),
  makeHotspotRecord({
    id: "wifi4eu-dlr-shangannah-park-house-ind",
    name: "Shangannah Park House",
    municipality: "Dún Laoghaire-Rathdown",
    countryCode: "IE",
    longitude: -6.119995000443569,
    latitude: 53.23866599969796,
    sourceType: "municipal_official",
    sourceIds: SOURCE_IDS,
    address: null,
    indoorOutdoor: "indoor",
    locationType: "Voucher C",
  }),
  makeHotspotRecord({
    id: "wifi4eu-dlr-shangannah-park-house-out",
    name: "Shangannah Park House",
    municipality: "Dún Laoghaire-Rathdown",
    countryCode: "IE",
    longitude: -6.119995000443569,
    latitude: 53.23866599969796,
    sourceType: "municipal_official",
    sourceIds: SOURCE_IDS,
    address: null,
    indoorOutdoor: "outdoor",
    locationType: "Voucher C",
  }),
  makeHotspotRecord({
    id: "wifi4eu-dlr-dundrum-library-out",
    name: "Dundrum Library",
    municipality: "Dún Laoghaire-Rathdown",
    countryCode: "IE",
    longitude: -6.246841000394751,
    latitude: 53.292619999728736,
    sourceType: "municipal_official",
    sourceIds: SOURCE_IDS,
    address: null,
    indoorOutdoor: "outdoor",
    locationType: "Voucher D",
  }),
  makeHotspotRecord({
    id: "wifi4eu-dlr-essence-caf-dundrum-out",
    name: "Essence Café Dundrum",
    municipality: "Dún Laoghaire-Rathdown",
    countryCode: "IE",
    longitude: -6.244500000289937,
    latitude: 53.29001900024551,
    sourceType: "municipal_official",
    sourceIds: SOURCE_IDS,
    address: null,
    indoorOutdoor: "outdoor",
    locationType: "Voucher D",
  }),
  makeHotspotRecord({
    id: "wifi4eu-dlr-loreto-court-community-rooms-ind",
    name: "Loreto Court Community Rooms",
    municipality: "Dún Laoghaire-Rathdown",
    countryCode: "IE",
    longitude: -6.271655000287384,
    latitude: 53.292021000328376,
    sourceType: "municipal_official",
    sourceIds: SOURCE_IDS,
    address: null,
    indoorOutdoor: "indoor",
    locationType: "Voucher D",
  }),
  makeHotspotRecord({
    id: "wifi4eu-dlr-loreto-court-community-rooms-out",
    name: "Loreto Court Community Rooms",
    municipality: "Dún Laoghaire-Rathdown",
    countryCode: "IE",
    longitude: -6.271655000287384,
    latitude: 53.292021000328376,
    sourceType: "municipal_official",
    sourceIds: SOURCE_IDS,
    address: null,
    indoorOutdoor: "outdoor",
    locationType: "Voucher D",
  }),
  makeHotspotRecord({
    id: "wifi4eu-dlr-nutgrove-loreto-community-facility-ind",
    name: "Nutgrove Loreto Community Facility",
    municipality: "Dún Laoghaire-Rathdown",
    countryCode: "IE",
    longitude: -6.27482100044638,
    latitude: 53.29189099959874,
    sourceType: "municipal_official",
    sourceIds: SOURCE_IDS,
    address: null,
    indoorOutdoor: "indoor",
    locationType: "Voucher D",
  }),
  makeHotspotRecord({
    id: "wifi4eu-dlr-nutgrove-loreto-community-facility-out",
    name: "Nutgrove Loreto Community Facility",
    municipality: "Dún Laoghaire-Rathdown",
    countryCode: "IE",
    longitude: -6.27482100044638,
    latitude: 53.29189099959874,
    sourceType: "municipal_official",
    sourceIds: SOURCE_IDS,
    address: null,
    indoorOutdoor: "outdoor",
    locationType: "Voucher D",
  }),
  makeHotspotRecord({
    id: "wifi4eu-dlr-sjog-burton-hall-ind",
    name: "SJOG  Burton Hall",
    municipality: "Dún Laoghaire-Rathdown",
    countryCode: "IE",
    longitude: -6.206607000546214,
    latitude: 53.27261499964203,
    sourceType: "municipal_official",
    sourceIds: SOURCE_IDS,
    address: null,
    indoorOutdoor: "indoor",
    locationType: "Voucher D",
  }),
  makeHotspotRecord({
    id: "wifi4eu-dlr-sjog-burton-hall-out",
    name: "SJOG  Burton Hall",
    municipality: "Dún Laoghaire-Rathdown",
    countryCode: "IE",
    longitude: -6.206607000546214,
    latitude: 53.27261499964203,
    sourceType: "municipal_official",
    sourceIds: SOURCE_IDS,
    address: null,
    indoorOutdoor: "outdoor",
    locationType: "Voucher D",
  }),
  makeHotspotRecord({
    id: "wifi4eu-dlr-st-nathys-community-centrei-ind",
    name: "St. Nathys Community CentreI",
    municipality: "Dún Laoghaire-Rathdown",
    countryCode: "IE",
    longitude: -6.258226999477479,
    latitude: 53.29498199990289,
    sourceType: "municipal_official",
    sourceIds: SOURCE_IDS,
    address: null,
    indoorOutdoor: "indoor",
    locationType: "Voucher D",
  }),
  makeHotspotRecord({
    id: "wifi4eu-dlr-st-nathys-community-centrei-out",
    name: "St. Nathys Community CentreI",
    municipality: "Dún Laoghaire-Rathdown",
    countryCode: "IE",
    longitude: -6.258226999477479,
    latitude: 53.29498199990289,
    sourceType: "municipal_official",
    sourceIds: SOURCE_IDS,
    address: null,
    indoorOutdoor: "outdoor",
    locationType: "Voucher D",
  }),
  makeHotspotRecord({
    id: "wifi4eu-dlr-stepaside-flemings-out",
    name: "Stepaside,   Flemings",
    municipality: "Dún Laoghaire-Rathdown",
    countryCode: "IE",
    longitude: -6.214491999940246,
    latitude: 53.25270100014327,
    sourceType: "municipal_official",
    sourceIds: SOURCE_IDS,
    address: null,
    indoorOutdoor: "outdoor",
    locationType: "Voucher D",
  }),
];
