import type { Locale } from "@/lib/i18n/config";

type MountainTranslation = {
  group: string;
  layer: string;
  ski: string;
  destination: string;
  peak: string;
  range: string;
  summitElevation: string;
  baseElevation: string;
  topElevation: string;
  winter: string;
  summer: string;
  yearRound: string;
  liftStatus: string;
  snowReport: string;
  warning: string;
  unavailable: string;
};

export const mountainTranslations: Record<Locale, MountainTranslation> = {
  en: { group: "Mountain & winter sports", layer: "Ski resorts and mountain destinations", ski: "Ski resort", destination: "Mountain destination", peak: "Iconic peak", range: "Mountain range", summitElevation: "Summit elevation", baseElevation: "Base elevation", topElevation: "Top elevation", winter: "Mainly winter activity", summer: "Mainly summer activity", yearRound: "Year-round destination", liftStatus: "Official lift status", snowReport: "Official snow report", warning: "Check the official source before travelling. Conditions and openings can change rapidly.", unavailable: "Detailed information is temporarily unavailable." },
  fr: { group: "Montagne et sports d’hiver", layer: "Stations de ski et destinations de montagne", ski: "Station de ski", destination: "Destination de montagne", peak: "Sommet emblématique", range: "Massif montagneux", summitElevation: "Altitude du sommet", baseElevation: "Altitude basse", topElevation: "Altitude haute", winter: "Activité principalement hivernale", summer: "Activité principalement estivale", yearRound: "Destination ouverte toute l’année", liftStatus: "État officiel des remontées", snowReport: "Bulletin neige officiel", warning: "Consultez la source officielle avant votre déplacement. Les conditions et ouvertures peuvent évoluer rapidement.", unavailable: "Informations détaillées temporairement indisponibles." },
  de: { group: "Berge und Wintersport", layer: "Skigebiete und Bergreiseziele", ski: "Skigebiet", destination: "Bergreiseziel", peak: "Berühmter Gipfel", range: "Gebirge", summitElevation: "Gipfelhöhe", baseElevation: "Talhöhe", topElevation: "Bergstation", winter: "Vorwiegend Winterbetrieb", summer: "Vorwiegend Sommerbetrieb", yearRound: "Ganzjähriges Reiseziel", liftStatus: "Offizieller Liftstatus", snowReport: "Offizieller Schneebericht", warning: "Prüfen Sie vor der Reise die offizielle Quelle. Bedingungen und Öffnungen können sich schnell ändern.", unavailable: "Detaillierte Informationen sind vorübergehend nicht verfügbar." },
  es: { group: "Montaña y deportes de invierno", layer: "Estaciones de esquí y destinos de montaña", ski: "Estación de esquí", destination: "Destino de montaña", peak: "Cumbre emblemática", range: "Macizo montañoso", summitElevation: "Altitud de la cumbre", baseElevation: "Altitud baja", topElevation: "Altitud alta", winter: "Actividad principalmente invernal", summer: "Actividad principalmente estival", yearRound: "Destino abierto todo el año", liftStatus: "Estado oficial de los remontes", snowReport: "Parte de nieve oficial", warning: "Consulte la fuente oficial antes de viajar. Las condiciones y aperturas pueden cambiar rápidamente.", unavailable: "La información detallada no está disponible temporalmente." },
  it: { group: "Montagna e sport invernali", layer: "Stazioni sciistiche e destinazioni montane", ski: "Stazione sciistica", destination: "Destinazione montana", peak: "Vetta iconica", range: "Massiccio montuoso", summitElevation: "Altitudine della vetta", baseElevation: "Quota minima", topElevation: "Quota massima", winter: "Attività prevalentemente invernale", summer: "Attività prevalentemente estiva", yearRound: "Destinazione aperta tutto l’anno", liftStatus: "Stato ufficiale degli impianti", snowReport: "Bollettino neve ufficiale", warning: "Consultare la fonte ufficiale prima del viaggio. Condizioni e aperture possono cambiare rapidamente.", unavailable: "Informazioni dettagliate temporaneamente non disponibili." },
  pt: { group: "Montanha e desportos de inverno", layer: "Estâncias de esqui e destinos de montanha", ski: "Estância de esqui", destination: "Destino de montanha", peak: "Pico emblemático", range: "Maciço montanhoso", summitElevation: "Altitude do cume", baseElevation: "Altitude mínima", topElevation: "Altitude máxima", winter: "Atividade sobretudo de inverno", summer: "Atividade sobretudo de verão", yearRound: "Destino aberto todo o ano", liftStatus: "Estado oficial dos meios mecânicos", snowReport: "Boletim de neve oficial", warning: "Consulte a fonte oficial antes de viajar. As condições e aberturas podem mudar rapidamente.", unavailable: "Informação detalhada temporariamente indisponível." },
  nl: { group: "Bergen en wintersport", layer: "Skigebieden en bergbestemmingen", ski: "Skigebied", destination: "Bergbestemming", peak: "Iconische top", range: "Bergmassief", summitElevation: "Tophoogte", baseElevation: "Laagste hoogte", topElevation: "Hoogste hoogte", winter: "Voornamelijk winteractiviteit", summer: "Voornamelijk zomeractiviteit", yearRound: "Bestemming het hele jaar open", liftStatus: "Officiële liftstatus", snowReport: "Officieel sneeuwbericht", warning: "Raadpleeg vóór vertrek de officiële bron. Omstandigheden en openstellingen kunnen snel veranderen.", unavailable: "Gedetailleerde informatie is tijdelijk niet beschikbaar." },
  bg: { group: "Планини и зимни спортове", layer: "Ски курорти и планински дестинации", ski: "Ски курорт", destination: "Планинска дестинация", peak: "Емблематичен връх", range: "Планински масив", summitElevation: "Височина на върха", baseElevation: "Долна височина", topElevation: "Горна височина", winter: "Предимно зимна дейност", summer: "Предимно лятна дейност", yearRound: "Целогодишна дестинация", liftStatus: "Официален статус на лифтовете", snowReport: "Официален снежен бюлетин", warning: "Проверете официалния източник преди пътуване. Условията и работното време могат да се променят бързо.", unavailable: "Подробната информация временно не е налична." },
  cs: { group: "Hory a zimní sporty", layer: "Lyžařská střediska a horské destinace", ski: "Lyžařské středisko", destination: "Horská destinace", peak: "Ikonický vrchol", range: "Pohoří", summitElevation: "Nadmořská výška vrcholu", baseElevation: "Dolní nadmořská výška", topElevation: "Horní nadmořská výška", winter: "Převážně zimní provoz", summer: "Převážně letní provoz", yearRound: "Celoroční destinace", liftStatus: "Oficiální stav lanovek", snowReport: "Oficiální sněhové zpravodajství", warning: "Před cestou ověřte oficiální zdroj. Podmínky a provoz se mohou rychle měnit.", unavailable: "Podrobné informace jsou dočasně nedostupné." },
  da: { group: "Bjerge og vintersport", layer: "Skisportssteder og bjergdestinationer", ski: "Skisportssted", destination: "Bjergdestination", peak: "Ikonisk bjergtop", range: "Bjergkæde", summitElevation: "Tophøjde", baseElevation: "Laveste højde", topElevation: "Højeste højde", winter: "Primært vinteraktivitet", summer: "Primært sommeraktivitet", yearRound: "Helårsdestination", liftStatus: "Officiel liftstatus", snowReport: "Officiel snerapport", warning: "Kontrollér den officielle kilde før rejsen. Forhold og åbninger kan ændre sig hurtigt.", unavailable: "Detaljerede oplysninger er midlertidigt utilgængelige." },
  el: { group: "Βουνά και χειμερινά σπορ", layer: "Χιονοδρομικά κέντρα και ορεινοί προορισμοί", ski: "Χιονοδρομικό κέντρο", destination: "Ορεινός προορισμός", peak: "Εμβληματική κορυφή", range: "Οροσειρά", summitElevation: "Υψόμετρο κορυφής", baseElevation: "Χαμηλό υψόμετρο", topElevation: "Υψηλό υψόμετρο", winter: "Κυρίως χειμερινή δραστηριότητα", summer: "Κυρίως θερινή δραστηριότητα", yearRound: "Προορισμός όλο τον χρόνο", liftStatus: "Επίσημη κατάσταση αναβατήρων", snowReport: "Επίσημο δελτίο χιονιού", warning: "Ελέγξτε την επίσημη πηγή πριν ταξιδέψετε. Οι συνθήκες και η λειτουργία αλλάζουν γρήγορα.", unavailable: "Οι λεπτομερείς πληροφορίες δεν είναι προσωρινά διαθέσιμες." },
  et: { group: "Mäed ja talisport", layer: "Suusakuurordid ja mägisihtkohad", ski: "Suusakuurort", destination: "Mägisihtkoht", peak: "Ikooniline tipp", range: "Mäestik", summitElevation: "Tipu kõrgus", baseElevation: "Alumine kõrgus", topElevation: "Ülemine kõrgus", winter: "Peamiselt talvine tegevus", summer: "Peamiselt suvine tegevus", yearRound: "Aastaringne sihtkoht", liftStatus: "Ametlik tõstukite olek", snowReport: "Ametlik lumeteade", warning: "Kontrollige enne reisi ametlikku allikat. Tingimused ja lahtiolekuajad võivad kiiresti muutuda.", unavailable: "Üksikasjalik teave pole ajutiselt saadaval." },
  fi: { group: "Vuoret ja talviurheilu", layer: "Hiihtokeskukset ja vuoristokohteet", ski: "Hiihtokeskus", destination: "Vuoristokohde", peak: "Ikoninen huippu", range: "Vuoristo", summitElevation: "Huipun korkeus", baseElevation: "Alakorkeus", topElevation: "Yläkorkeus", winter: "Pääasiassa talvitoimintaa", summer: "Pääasiassa kesätoimintaa", yearRound: "Ympärivuotinen kohde", liftStatus: "Hissien virallinen tila", snowReport: "Virallinen lumiraportti", warning: "Tarkista virallinen lähde ennen matkaa. Olosuhteet ja aukiolot voivat muuttua nopeasti.", unavailable: "Yksityiskohtaiset tiedot eivät ole tilapäisesti saatavilla." },
  ga: { group: "Sléibhte agus spóirt gheimhridh", layer: "Ionaid sciála agus cinn scríbe sléibhe", ski: "Ionad sciála", destination: "Ceann scríbe sléibhe", peak: "Buaic íocónach", range: "Sliabhraon", summitElevation: "Airde na buaice", baseElevation: "Airde íseal", topElevation: "Airde ard", winter: "Gníomhaíocht gheimhridh den chuid is mó", summer: "Gníomhaíocht samhraidh den chuid is mó", yearRound: "Ceann scríbe ar feadh na bliana", liftStatus: "Stádas oifigiúil na n-ardaitheoirí", snowReport: "Tuairisc oifigiúil sneachta", warning: "Seiceáil an fhoinse oifigiúil roimh thaisteal. Féadfaidh coinníollacha agus oscailtí athrú go tapa.", unavailable: "Níl faisnéis mhionsonraithe ar fáil go sealadach." },
  hr: { group: "Planine i zimski sportovi", layer: "Skijališta i planinska odredišta", ski: "Skijalište", destination: "Planinsko odredište", peak: "Kultni vrh", range: "Planinski masiv", summitElevation: "Visina vrha", baseElevation: "Donja visina", topElevation: "Gornja visina", winter: "Pretežno zimska aktivnost", summer: "Pretežno ljetna aktivnost", yearRound: "Cjelogodišnje odredište", liftStatus: "Službeno stanje žičara", snowReport: "Službeno izvješće o snijegu", warning: "Prije putovanja provjerite službeni izvor. Uvjeti i otvorenost mogu se brzo promijeniti.", unavailable: "Detaljne informacije privremeno nisu dostupne." },
  hu: { group: "Hegyek és téli sportok", layer: "Síközpontok és hegyi úti célok", ski: "Síközpont", destination: "Hegyi úti cél", peak: "Ikonikus csúcs", range: "Hegység", summitElevation: "Csúcsmagasság", baseElevation: "Alsó magasság", topElevation: "Felső magasság", winter: "Főként téli tevékenység", summer: "Főként nyári tevékenység", yearRound: "Egész éves úti cél", liftStatus: "Felvonók hivatalos állapota", snowReport: "Hivatalos hójelentés", warning: "Utazás előtt ellenőrizze a hivatalos forrást. A körülmények és nyitvatartások gyorsan változhatnak.", unavailable: "A részletes információ átmenetileg nem érhető el." },
  lt: { group: "Kalnai ir žiemos sportas", layer: "Slidinėjimo kurortai ir kalnų vietovės", ski: "Slidinėjimo kurortas", destination: "Kalnų vietovė", peak: "Ikoniška viršūnė", range: "Kalnų masyvas", summitElevation: "Viršūnės aukštis", baseElevation: "Apatinis aukštis", topElevation: "Viršutinis aukštis", winter: "Daugiausia žiemos veikla", summer: "Daugiausia vasaros veikla", yearRound: "Visus metus veikianti vietovė", liftStatus: "Oficiali keltuvų būklė", snowReport: "Oficiali sniego ataskaita", warning: "Prieš kelionę patikrinkite oficialų šaltinį. Sąlygos ir darbo laikas gali greitai keistis.", unavailable: "Išsami informacija laikinai nepasiekiama." },
  lv: { group: "Kalni un ziemas sports", layer: "Slēpošanas kūrorti un kalnu galamērķi", ski: "Slēpošanas kūrorts", destination: "Kalnu galamērķis", peak: "Ikoniska virsotne", range: "Kalnu masīvs", summitElevation: "Virsotnes augstums", baseElevation: "Apakšējais augstums", topElevation: "Augšējais augstums", winter: "Galvenokārt ziemas aktivitātes", summer: "Galvenokārt vasaras aktivitātes", yearRound: "Galamērķis visu gadu", liftStatus: "Oficiālais pacēlāju statuss", snowReport: "Oficiālais sniega ziņojums", warning: "Pirms brauciena pārbaudiet oficiālo avotu. Apstākļi un darba laiks var strauji mainīties.", unavailable: "Detalizēta informācija īslaicīgi nav pieejama." },
  mt: { group: "Muntanji u sport tax-xitwa", layer: "Resorts tal-iskijjar u destinazzjonijiet tal-muntanji", ski: "Resort tal-iskijjar", destination: "Destinazzjoni tal-muntanji", peak: "Quċċata emblematika", range: "Katina muntanjuża", summitElevation: "Għoli tal-quċċata", baseElevation: "Għoli baxx", topElevation: "Għoli għoli", winter: "Attività prinċipalment fix-xitwa", summer: "Attività prinċipalment fis-sajf", yearRound: "Destinazzjoni miftuħa s-sena kollha", liftStatus: "Status uffiċjali tal-lifts", snowReport: "Rapport uffiċjali tas-silġ", warning: "Iċċekkja s-sors uffiċjali qabel tivvjaġġa. Il-kundizzjonijiet u l-ftuħ jistgħu jinbidlu malajr.", unavailable: "Informazzjoni dettaljata temporanjament mhux disponibbli." },
  pl: { group: "Góry i sporty zimowe", layer: "Ośrodki narciarskie i kierunki górskie", ski: "Ośrodek narciarski", destination: "Kierunek górski", peak: "Ikoniczny szczyt", range: "Masyw górski", summitElevation: "Wysokość szczytu", baseElevation: "Dolna wysokość", topElevation: "Górna wysokość", winter: "Głównie działalność zimowa", summer: "Głównie działalność letnia", yearRound: "Kierunek całoroczny", liftStatus: "Oficjalny status wyciągów", snowReport: "Oficjalny raport śniegowy", warning: "Przed podróżą sprawdź oficjalne źródło. Warunki i otwarcia mogą szybko się zmieniać.", unavailable: "Szczegółowe informacje są tymczasowo niedostępne." },
  ro: { group: "Munte și sporturi de iarnă", layer: "Stațiuni de schi și destinații montane", ski: "Stațiune de schi", destination: "Destinație montană", peak: "Vârf emblematic", range: "Masiv muntos", summitElevation: "Altitudinea vârfului", baseElevation: "Altitudine joasă", topElevation: "Altitudine înaltă", winter: "Activitate predominant de iarnă", summer: "Activitate predominant de vară", yearRound: "Destinație deschisă tot anul", liftStatus: "Starea oficială a instalațiilor", snowReport: "Buletin oficial de zăpadă", warning: "Consultați sursa oficială înainte de călătorie. Condițiile și deschiderile se pot schimba rapid.", unavailable: "Informațiile detaliate sunt temporar indisponibile." },
  sk: { group: "Hory a zimné športy", layer: "Lyžiarske strediská a horské destinácie", ski: "Lyžiarske stredisko", destination: "Horská destinácia", peak: "Ikonický vrchol", range: "Pohorie", summitElevation: "Nadmorská výška vrcholu", baseElevation: "Dolná nadmorská výška", topElevation: "Horná nadmorská výška", winter: "Prevažne zimná prevádzka", summer: "Prevažne letná prevádzka", yearRound: "Celoročná destinácia", liftStatus: "Oficiálny stav lanoviek", snowReport: "Oficiálna snehová správa", warning: "Pred cestou skontrolujte oficiálny zdroj. Podmienky a prevádzka sa môžu rýchlo meniť.", unavailable: "Podrobné informácie sú dočasne nedostupné." },
  sl: { group: "Gore in zimski športi", layer: "Smučišča in gorske destinacije", ski: "Smučišče", destination: "Gorska destinacija", peak: "Znameniti vrh", range: "Gorski masiv", summitElevation: "Nadmorska višina vrha", baseElevation: "Spodnja nadmorska višina", topElevation: "Zgornja nadmorska višina", winter: "Pretežno zimska dejavnost", summer: "Pretežno poletna dejavnost", yearRound: "Celoletna destinacija", liftStatus: "Uradno stanje žičnic", snowReport: "Uradno snežno poročilo", warning: "Pred potovanjem preverite uradni vir. Razmere in odprtost se lahko hitro spremenijo.", unavailable: "Podrobne informacije začasno niso na voljo." },
  sv: { group: "Berg och vintersport", layer: "Skidorter och bergsdestinationer", ski: "Skidort", destination: "Bergsdestination", peak: "Ikonisk topp", range: "Bergsmassiv", summitElevation: "Topphöjd", baseElevation: "Lägsta höjd", topElevation: "Högsta höjd", winter: "Främst vinteraktivitet", summer: "Främst sommaraktivitet", yearRound: "Året-runt-destination", liftStatus: "Officiell liftstatus", snowReport: "Officiell snörapport", warning: "Kontrollera den officiella källan före resan. Förhållanden och öppettider kan ändras snabbt.", unavailable: "Detaljerad information är tillfälligt otillgänglig." },
};
