import type { Map as MapLibreMap } from "maplibre-gl";
import {
  FLIGHT_LAYER_AIRPORT_LABELS,
  FLIGHT_LAYER_AIRPORTS,
  FLIGHT_LAYER_HALO,
  FLIGHT_LAYER_MAIN,
} from "@/lib/routing/flightMapLayers";
import {
  ROUTE_PLANNER_LAYER_ALT,
  ROUTE_PLANNER_LAYER_HALO,
  ROUTE_PLANNER_LAYER_MAIN,
  ROUTE_PLANNER_LAYER_POINT_LABELS,
  ROUTE_PLANNER_LAYER_POINTS,
  ROUTE_PLANNER_LAYER_TRAFFIC,
} from "@/lib/routing/routeMapLayers";
import {
  TRANSIT_LAYER_HALO,
  TRANSIT_LAYER_MAIN,
  TRANSIT_LAYER_POINT_LABELS,
  TRANSIT_LAYER_POINTS,
  TRANSIT_LAYER_WALK,
  TRANSIT_LAYER_WALK_HALO,
} from "@/lib/routing/transitMapLayers";

/**
 * Bottom → top stack for EUIM custom layers.
 * Traffic stays below interactive POI / photo markers / user location.
 */
export const EUIM_LAYER_STACK_BOTTOM_TO_TOP: readonly string[] = [
  // Economy / membership fills (below traffic & POI)
  "european-economic-area-fill",
  "european-economic-area-border",
  // Tourism Travel V2: Natura 2000 raster (below traffic, commit 2)
  "natura2000-raster",
  // Wildfire / satellite history fills
  "firms-recent-history-fill",
  "firms-recent-history-border",
  "firms-recent-history-selected-fill",
  "firms-recent-history-selected",
  "firms-incident-footprints-fill",
  "firms-incident-footprints-border",
  "firms-incident-footprints-selected-fill",
  "firms-incident-footprints-selected",
  "effis-burned-areas-layer",
  "effis-burned-area-snapshots-fill",
  "effis-burned-area-snapshots-border",
  "effis-burned-area-snapshots-selected",
  "wildfire-wind-arrows",
  // Road traffic (under markers / photos / route points)
  "tomtom-traffic-flow-layer",
  "tomtom-traffic-incidents-overview",
  "traffic-incident-lines-casing",
  "traffic-incident-lines-layer",
  "traffic-incident-clusters",
  "traffic-incident-cluster-count",
  "traffic-incident-markers",
  "traffic-incident-labels",
  // Incident / alert overlays
  "cems-activation-aois-fill",
  "cems-activation-aois-line",
  "cems-activation-products-line",
  "storm-uncertainty-fill",
  "normalized-alert-zones-fill",
  "normalized-alert-zones-line",
  "storm-tracks-line",
  "storm-forecast-tracks-line",
  "normalized-alert-points",
  "gdacs-flood-event-clusters",
  "gdacs-flood-event-cluster-count",
  "gdacs-flood-event-marker-ring",
  "gdacs-flood-event-marker",
  "gdacs-flood-event-wave",
  "gdacs-flood-event-label",
  "geological-alert-clusters",
  "geological-alert-cluster-count",
  "earthquake-marker-wave",
  "earthquake-marker",
  "volcano-marker",
  "geological-alert-label",
  "cems-landslide-clusters",
  "cems-industrial-clusters",
  "cems-landslide-markers",
  "cems-industrial-markers",
  "cems-landslide-labels",
  "cems-industrial-labels",
  "normalized-alert-selected",
  "normalized-alert-selected-point",
  "geological-alert-selected",
  "traffic-incident-selected",
  // Tourism Travel V2: outdoor routes (commit 3) — below Directions/route planner lines
  "outdoor-hiking-routes-halo",
  "outdoor-hiking-routes-line-layer",
  "outdoor-cycling-routes-halo",
  "outdoor-cycling-routes-line-layer",
  "outdoor-running-routes-halo",
  "outdoor-running-routes-line-layer",
  // Route geometries
  "eurostar-routes-line",
  ROUTE_PLANNER_LAYER_ALT,
  ROUTE_PLANNER_LAYER_HALO,
  ROUTE_PLANNER_LAYER_MAIN,
  ROUTE_PLANNER_LAYER_TRAFFIC,
  TRANSIT_LAYER_WALK_HALO,
  TRANSIT_LAYER_WALK,
  TRANSIT_LAYER_HALO,
  TRANSIT_LAYER_MAIN,
  FLIGHT_LAYER_HALO,
  FLIGHT_LAYER_MAIN,
  // Route stops / points
  ROUTE_PLANNER_LAYER_POINTS,
  ROUTE_PLANNER_LAYER_POINT_LABELS,
  TRANSIT_LAYER_POINTS,
  TRANSIT_LAYER_POINT_LABELS,
  FLIGHT_LAYER_AIRPORTS,
  FLIGHT_LAYER_AIRPORT_LABELS,
  // Security overlays
  "schengen-temporary-control-fill",
  "schengen-temporary-control-line",
  "schengen-temporary-control-symbol",
  "schengen-temporary-control-selected",
  "schengen-border-clusters",
  "schengen-border-cluster-count",
  "schengen-border-crossing-selected",
  "schengen-border-crossing-symbol",
  "schengen-border-crossing-label",
  // POI / photo markers
  "eu-capitals-halo",
  "eu-capitals-symbol",
  "eu-capitals-label",
  "eu-main-institutions-halo",
  "eu-main-institutions-symbol",
  "eu-main-institutions-label",
  "eu-bodies-agencies-clusters",
  "eu-bodies-agencies-cluster-count",
  "eu-bodies-agencies-halo",
  "eu-bodies-agencies-symbol",
  "eu-bodies-agencies-label",
  "international-organisations-halo",
  "international-organisations-symbol",
  "international-organisations-label",
  "european-capitals-of-culture-halo",
  "european-capitals-of-culture-symbol",
  "european-capitals-of-culture-label",
  "eu-projects-halo",
  "eu-projects-symbol",
  "eu-projects-label",
  "major-business-districts-halo",
  "major-business-districts-symbol",
  "major-business-districts-label",
  "major-freight-ports-halo",
  "major-freight-ports-symbol",
  "major-freight-ports-label",
  "unesco-world-heritage-halo",
  "unesco-world-heritage-symbol",
  "unesco-world-heritage-labels",
  "unesco-clusters",
  "unesco-cluster-count",
  "ehl-selected-site",
  "ehl-sites-symbol",
  "ehl-sites-label",
  "ehl-clusters",
  "ehl-cluster-count",
  "tourist-places-halo",
  "tourist-places-symbol",
  "tourist-places-labels",
  "tourist-clusters",
  "tourist-cluster-count",
  "mountain-place-selected",
  "mountain-places-symbol",
  "mountain-places-label",
  "mountain-place-clusters",
  "mountain-place-cluster-count",
  "civil-engineering-selected",
  "civil-engineering-symbol",
  "civil-engineering-label",
  "civil-engineering-clusters",
  "civil-engineering-cluster-count",
  "airport-clusters",
  "airport-cluster-count",
  "major-airport-selected",
  "major-airports-symbol",
  "major-airports-label",
  "eurostar-selected-station",
  "eurostar-stations-symbol",
  "eurostar-stations-label",
  // Tourism Travel V2: visitor services (commit 1)
  "wifi4eu-clusters",
  "wifi4eu-cluster-count",
  "wifi4eu-halo",
  "wifi4eu-symbol",
  "tourist-information-offices-halo",
  "tourist-information-offices-symbol",
  "tourist-information-offices-label",
  "diplomatic-missions-clusters",
  "diplomatic-missions-cluster-count",
  "diplomatic-missions-halo",
  "diplomatic-missions-symbol",
  "visitor-safety-assistance-halo",
  "visitor-safety-assistance-symbol",
  "visitor-safety-assistance-label",
  // Tourism Travel V2: bathing waters & beaches (above traffic, commit 2)
  "bathing-waters-clusters",
  "bathing-waters-cluster-count",
  "bathing-waters-halo",
  "bathing-waters-symbol",
  "major-beaches-halo",
  "major-beaches-symbol",
  "major-beaches-label",
  // User location on top
  "user-location-accuracy",
  "user-location-halo",
  "user-location-pulse",
  "user-location-dot",
];

/** Move existing layers into the canonical EUIM stack order (bottom → top). */
export function ensureEUIMLayerOrder(map: MapLibreMap): void {
  for (const layerId of EUIM_LAYER_STACK_BOTTOM_TO_TOP) {
    if (map.getLayer(layerId)) {
      map.moveLayer(layerId);
    }
  }
}
